// Package crudquerydefs generates querydefs Go source files that define CRUD
// queries using the query builder DSL. The generated files are written into the
// user's project so they can inspect and customise the queries.
package crudquerydefs

import (
	"fmt"
	"go/format"
	"strings"

	topcodegen "github.com/shipq/shipq/codegen"
	"github.com/shipq/shipq/db/portsql/codegen"
	"github.com/shipq/shipq/db/portsql/ddl"
	"github.com/shipq/shipq/dbstrings"
)

// Config holds everything needed to generate the CRUD querydefs file for a single table.
type Config struct {
	ModulePath  string
	TableName   string
	Table       ddl.Table
	ScopeColumn string
	Schema      map[string]ddl.Table // all tables (for FK resolution)
	ExposeEmail bool
}

// GenerateCRUDQueryDefs generates a Go source file containing query.MustDefine*
// calls for the five CRUD operations on the given table. The generated code
// references the schema package so it uses the same typed column helpers as
// user-defined queries.
func GenerateCRUDQueryDefs(cfg Config) ([]byte, error) {
	analysis := codegen.AnalyzeTable(cfg.Table)

	schemaPkg := cfg.ModulePath + "/shipq/db/schema"
	queryPkg := cfg.ModulePath + "/shipq/lib/db/portsql/query"

	pkgName := cfg.TableName // e.g. "posts"

	// Collect extra imports needed by Param types (e.g. "time" for time.Time params)
	extraImports := collectParamImports(cfg, analysis)

	var buf strings.Builder

	buf.WriteString("// Code generated by shipq. You may edit this file to customise your CRUD queries.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	buf.WriteString("import (\n")
	if len(extraImports) > 0 {
		for imp := range extraImports {
			buf.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		buf.WriteString("\n")
	}
	buf.WriteString(fmt.Sprintf("\t%q\n", schemaPkg))
	buf.WriteString(fmt.Sprintf("\t%q\n", queryPkg))
	buf.WriteString(")\n\n")
	buf.WriteString("func init() {\n")

	schemaVar := dbstrings.ToPascalCase(cfg.TableName) // e.g. "Posts"

	writeGetQuery(&buf, cfg, analysis, schemaVar)
	writeListQuery(&buf, cfg, analysis, schemaVar)
	writeCreateQuery(&buf, cfg, analysis, schemaVar)
	writeUpdateQuery(&buf, cfg, analysis, schemaVar)
	writeDeleteQuery(&buf, cfg, analysis, schemaVar)

	buf.WriteString("}\n")

	return formatSource([]byte(buf.String()))
}

// schemaCol returns code like "schema.Posts.Title()" for a column.
func schemaCol(schemaVar, colName string) string {
	return fmt.Sprintf("schema.%s.%s()", schemaVar, dbstrings.ToPascalCase(colName))
}

// paramExpr returns code like `query.Param[string]("title")` for the given Go type and param name.
func paramExpr(goType, name string) string {
	return fmt.Sprintf("query.Param[%s](%q)", goType, name)
}

// lowerCamel converts a snake_case column name to lowerCamelCase for use as a param name.
func lowerCamel(snakeCase string) string {
	return dbstrings.ToLowerCamel(dbstrings.ToPascalCase(snakeCase))
}

// fkSubquery returns the DSL code for resolving a FK column's public_id to
// its internal id via a scalar subquery, e.g.:
//
//	query.Subquery(
//	    query.From(schema.Categories).
//	        Select(schema.Categories.Id()).
//	        Where(schema.Categories.PublicId().Eq(query.Param[string]("categoryId"))))
func fkSubquery(refTable, paramName string) string {
	refVar := dbstrings.ToPascalCase(refTable)
	return fmt.Sprintf("query.Subquery(\n\t\t\t\tquery.From(schema.%s).\n\t\t\t\t\tSelect(schema.%s.Id()).\n\t\t\t\t\tWhere(schema.%s.PublicId().Eq(query.Param[string](%q))))",
		refVar, refVar, refVar, paramName)
}

// ---------- JOIN alias helpers ----------

// joinDescriptor describes a single JOIN to emit, with optional alias metadata
// for cases where the same table is joined more than once.
type joinDescriptor struct {
	col         ddl.ColumnDefinition // FK column definition (zero value for author join)
	refTable    string               // e.g., "accounts"
	refVar      string               // e.g., "Accounts" (PascalCase schema variable)
	alias       string               // e.g., "account" or "author" (only used when needsAs)
	needsAs     bool                 // true when the referenced table appears more than once
	joinType    string               // "Join" or "LeftJoin"
	isAuthor    bool                 // true for the hardcoded author join
	exposeEmail bool                 // true when author email should be included
	colName     string               // FK column name, e.g., "account_id"
}

// buildJoinPlan builds a slice of joinDescriptors from FK columns and the optional
// author join. When the same referenced table appears more than once, each descriptor
// gets needsAs=true and a deterministic alias derived from the FK column name.
func buildJoinPlan(fkCols []ddl.ColumnDefinition, fkRefTables []string, hasAuthorJoin bool, exposeEmail bool) []joinDescriptor {
	// Build raw descriptors
	var plan []joinDescriptor
	for i, col := range fkCols {
		jt := "Join"
		if col.Nullable {
			jt = "LeftJoin"
		}
		plan = append(plan, joinDescriptor{
			col:      col,
			refTable: fkRefTables[i],
			refVar:   dbstrings.ToPascalCase(fkRefTables[i]),
			joinType: jt,
			colName:  col.Name,
		})
	}
	if hasAuthorJoin && !authorJoinCollidesWithFK(fkCols) {
		plan = append(plan, joinDescriptor{
			refTable:    "accounts",
			refVar:      "Accounts",
			joinType:    "LeftJoin",
			isAuthor:    true,
			exposeEmail: exposeEmail,
			colName:     "author_account_id",
		})
	}

	// Count how many times each referenced table appears
	tableRefCount := make(map[string]int)
	for _, j := range plan {
		tableRefCount[j.refTable]++
	}

	// Assign aliases when a table is referenced more than once.
	for i := range plan {
		if tableRefCount[plan[i].refTable] > 1 {
			plan[i].needsAs = true
			if plan[i].isAuthor {
				plan[i].alias = "author"
			} else {
				// Derive alias from FK column name by stripping "_id" suffix.
				// e.g., "account_id" → "account", "sender_account_id" → "sender_account"
				plan[i].alias = strings.TrimSuffix(plan[i].colName, "_id")
			}
		}
	}

	return plan
}

// authorJoinCollidesWithFK returns true when any FK column's resolved
// SelectAs alias would clash with the hard-coded author-account aliases
// ("author_id", "author_email", …).  The most common case is a
// user-defined `author_id` FK column pointing at a domain table.
func authorJoinCollidesWithFK(fkCols []ddl.ColumnDefinition) bool {
	authorAliases := map[string]bool{
		"author_id":         true,
		"author_email":      true,
		"author_first_name": true,
		"author_last_name":  true,
	}
	for _, col := range fkCols {
		if authorAliases[col.Name] {
			return true
		}
	}
	return false
}

// emitJoin writes a single JOIN clause for the given descriptor.
func emitJoin(buf *strings.Builder, schemaVar string, j joinDescriptor) {
	if j.needsAs {
		buf.WriteString(fmt.Sprintf("\t\t\t%s(schema.%s).As(%q).On(schema.%s.Id().WithTable(%q).Eq(%s)).\n",
			j.joinType, j.refVar, j.alias, j.refVar, j.alias, schemaCol(schemaVar, j.colName)))
	} else {
		buf.WriteString(fmt.Sprintf("\t\t\t%s(schema.%s).On(schema.%s.Id().Eq(%s)).\n",
			j.joinType, j.refVar, j.refVar, schemaCol(schemaVar, j.colName)))
	}
}

// emitSelectAs writes the SelectAs calls for a join descriptor.
// For FK joins it selects the referenced table's public_id aliased to the FK column name.
// For author joins it selects the four author fields.
func emitSelectAs(buf *strings.Builder, j joinDescriptor) {
	if j.isAuthor {
		if j.needsAs {
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.PublicId().WithTable(%q), \"author_id\").\n", j.refVar, j.alias))
			if j.exposeEmail {
				buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.Email().WithTable(%q), \"author_email\").\n", j.refVar, j.alias))
			}
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.FirstName().WithTable(%q), \"author_first_name\").\n", j.refVar, j.alias))
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.LastName().WithTable(%q), \"author_last_name\").\n", j.refVar, j.alias))
		} else {
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.PublicId(), \"author_id\").\n", j.refVar))
			if j.exposeEmail {
				buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.Email(), \"author_email\").\n", j.refVar))
			}
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.FirstName(), \"author_first_name\").\n", j.refVar))
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.LastName(), \"author_last_name\").\n", j.refVar))
		}
	} else {
		if j.needsAs {
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.PublicId().WithTable(%q), %q).\n",
				j.refVar, j.alias, j.col.Name))
		} else {
			buf.WriteString(fmt.Sprintf("\t\t\tSelectAs(schema.%s.PublicId(), %q).\n",
				j.refVar, j.col.Name))
		}
	}
}

// ---------- GET ----------

func writeGetQuery(buf *strings.Builder, cfg Config, analysis codegen.TableAnalysis, schemaVar string) {
	queryName := topcodegen.CRUD.GetMethodName(cfg.TableName)

	// Collect FK columns that need JOIN resolution
	var fkCols []ddl.ColumnDefinition
	var fkRefTables []string

	var plainCols []ddl.ColumnDefinition
	for _, col := range cfg.Table.Columns {
		// Never select internal-only columns into the result struct
		if col.Name == "id" || col.Name == "author_account_id" {
			continue
		}
		// Scope column is only used in the WHERE clause — never exposed
		// in API responses (it's an internal integer FK).
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		// Skip FK columns from the plain Select — they'll use SelectAs after JOINs
		if col.References != "" {
			fkCols = append(fkCols, col)
			fkRefTables = append(fkRefTables, col.References)
			continue
		}
		plainCols = append(plainCols, col)
	}

	// Build a join plan with alias tracking for duplicate tables
	joinPlan := buildJoinPlan(fkCols, fkRefTables, analysis.HasAuthorAccountID, cfg.ExposeEmail)

	buf.WriteString(fmt.Sprintf("\tquery.MustDefineOne(%q,\n", queryName))
	buf.WriteString(fmt.Sprintf("\t\tquery.From(schema.%s).\n", schemaVar))

	// Emit JOIN clauses
	for _, j := range joinPlan {
		emitJoin(buf, schemaVar, j)
	}

	buf.WriteString("\t\t\tSelect(\n")

	// Select plain columns (no FK, no id, no author_account_id)
	for _, col := range plainCols {
		buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", schemaCol(schemaVar, col.Name)))
	}
	buf.WriteString("\t\t\t).\n")

	// Emit SelectAs for all joins (FK columns + author)
	for _, j := range joinPlan {
		emitSelectAs(buf, j)
	}

	// WHERE clause
	whereCol := "public_id"
	if !analysis.HasPublicID && analysis.PrimaryKey != nil {
		whereCol = analysis.PrimaryKey.Name
	}

	mapping := codegen.MapColumnType(colByName(cfg.Table, whereCol))

	var whereParts []string
	whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, whereCol), paramExpr(mapping.GoType, lowerCamel(whereCol))))
	if analysis.HasDeletedAt {
		whereParts = append(whereParts, fmt.Sprintf("%s.IsNull()", schemaCol(schemaVar, "deleted_at")))
	}
	if cfg.ScopeColumn != "" {
		scopeMapping := codegen.MapColumnType(colByName(cfg.Table, cfg.ScopeColumn))
		whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, cfg.ScopeColumn), paramExpr(scopeMapping.GoType, lowerCamel(cfg.ScopeColumn))))
	}

	writeWhere(buf, whereParts)
	buf.WriteString("\t\t\tBuild())\n\n")
}

// ---------- LIST ----------

func writeListQuery(buf *strings.Builder, cfg Config, analysis codegen.TableAnalysis, schemaVar string) {
	queryName := fmt.Sprintf("List%s", dbstrings.ToPascalCase(cfg.TableName))

	// Use MustDefinePaginated when table has created_at + public_id (cursor support),
	// otherwise fall back to MustDefineMany (no cursor pagination).
	// We use public_id (not id) as the tiebreaker because id is excluded from SELECT.
	supportsCursor := analysis.HasCreatedAt && analysis.HasPublicID

	// Collect FK columns that need JOIN resolution
	var fkCols []ddl.ColumnDefinition
	var fkRefTables []string

	var plainCols []ddl.ColumnDefinition
	for _, col := range cfg.Table.Columns {
		// Never select internal-only columns into the result struct
		if col.Name == "id" || col.Name == "author_account_id" {
			continue
		}
		// Scope column is only used in the WHERE clause — never exposed
		// in API responses (it's an internal integer FK).
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		// Skip FK columns from the plain Select — they'll use SelectAs after JOINs
		if col.References != "" {
			fkCols = append(fkCols, col)
			fkRefTables = append(fkRefTables, col.References)
			continue
		}
		plainCols = append(plainCols, col)
	}

	// Build a join plan with alias tracking for duplicate tables
	joinPlan := buildJoinPlan(fkCols, fkRefTables, analysis.HasAuthorAccountID, cfg.ExposeEmail)

	if supportsCursor {
		buf.WriteString(fmt.Sprintf("\tquery.MustDefinePaginated(%q,\n", queryName))
	} else {
		buf.WriteString(fmt.Sprintf("\tquery.MustDefineMany(%q,\n", queryName))
	}

	buf.WriteString(fmt.Sprintf("\t\tquery.From(schema.%s).\n", schemaVar))

	// Emit JOIN clauses
	for _, j := range joinPlan {
		emitJoin(buf, schemaVar, j)
	}

	buf.WriteString("\t\t\tSelect(\n")

	// Select plain columns (no FK, no id, no author_account_id)
	for _, col := range plainCols {
		buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", schemaCol(schemaVar, col.Name)))
	}
	buf.WriteString("\t\t\t).\n")

	// Emit SelectAs for all joins (FK columns + author)
	for _, j := range joinPlan {
		emitSelectAs(buf, j)
	}

	var whereParts []string
	if analysis.HasDeletedAt {
		whereParts = append(whereParts, fmt.Sprintf("%s.IsNull()", schemaCol(schemaVar, "deleted_at")))
	}
	if cfg.ScopeColumn != "" {
		scopeMapping := codegen.MapColumnType(colByName(cfg.Table, cfg.ScopeColumn))
		whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, cfg.ScopeColumn), paramExpr(scopeMapping.GoType, lowerCamel(cfg.ScopeColumn))))
	}

	if len(whereParts) > 0 {
		writeWhere(buf, whereParts)
	}

	if supportsCursor {
		// Close the Build(), then add cursor columns
		// Use public_id as tiebreaker (not id, which is excluded from SELECT)
		buf.WriteString("\t\t\tBuild(),\n")
		buf.WriteString(fmt.Sprintf("\t\t%s.Desc(),\n", schemaCol(schemaVar, "created_at")))
		buf.WriteString(fmt.Sprintf("\t\t%s.Desc(),\n", schemaCol(schemaVar, "public_id")))
		buf.WriteString("\t)\n\n")
	} else {
		buf.WriteString("\t\t\tBuild())\n\n")
	}
}

// ---------- CREATE ----------

func writeCreateQuery(buf *strings.Builder, cfg Config, analysis codegen.TableAnalysis, schemaVar string) {
	singular := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
	queryName := fmt.Sprintf("Create%s", singular)

	buf.WriteString(fmt.Sprintf("\tquery.MustDefineOne(%q,\n", queryName))
	buf.WriteString(fmt.Sprintf("\t\tquery.InsertInto(schema.%s).\n", schemaVar))

	// Columns
	buf.WriteString("\t\t\tColumns(\n")

	type insertCol struct {
		colName string
		value   string
	}
	var insertCols []insertCol

	// public_id first
	if analysis.HasPublicID {
		insertCols = append(insertCols, insertCol{
			colName: "public_id",
			value:   paramExpr("string", "publicId"),
		})
	}

	// author_account_id (auto-populated from session)
	if analysis.HasAuthorAccountID {
		insertCols = append(insertCols, insertCol{
			colName: "author_account_id",
			value:   paramExpr("int64", "authorAccountId"),
		})
	}

	// User columns (everything except auto-filled)
	for _, col := range cfg.Table.Columns {
		if col.Name == "id" || col.Name == "public_id" || col.Name == "created_at" ||
			col.Name == "updated_at" || col.Name == "deleted_at" || col.Name == "author_account_id" {
			continue
		}
		mapping := codegen.MapColumnType(col)
		paramName := lowerCamel(col.Name)

		var value string
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			value = paramExpr(mapping.GoType, paramName)
		} else if col.References != "" {
			value = fkSubquery(col.References, paramName)
		} else {
			value = paramExpr(mapping.GoType, paramName)
		}

		insertCols = append(insertCols, insertCol{
			colName: col.Name,
			value:   value,
		})
	}

	for _, ic := range insertCols {
		buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", schemaCol(schemaVar, ic.colName)))
	}
	buf.WriteString("\t\t\t).\n")

	// Values
	buf.WriteString("\t\t\tValues(\n")
	for _, ic := range insertCols {
		buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", ic.value))
	}
	buf.WriteString("\t\t\t).\n")

	// Always return the internal id — fixtures and scope-column resolution
	// need the raw integer PK from CreateResult types.
	// This value is NEVER exposed in API responses. See isResponseExcluded()
	// in handlergen and the SELECT exclusion in writeGetQuery/writeListQuery.
	buf.WriteString("\t\t\tReturning(\n")
	buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", schemaCol(schemaVar, "id")))
	if analysis.HasPublicID {
		buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", schemaCol(schemaVar, "public_id")))
	}
	buf.WriteString("\t\t\t).\n")

	buf.WriteString("\t\t\tBuild())\n\n")
}

// ---------- UPDATE ----------

func writeUpdateQuery(buf *strings.Builder, cfg Config, analysis codegen.TableAnalysis, schemaVar string) {
	queryName := topcodegen.CRUD.UpdateMethodName(cfg.TableName)

	buf.WriteString(fmt.Sprintf("\tquery.MustDefineExec(%q,\n", queryName))
	buf.WriteString(fmt.Sprintf("\t\tquery.Update(schema.%s).\n", schemaVar))

	// SET clauses: user columns (excluding auto-filled, scope, author_account_id)
	for _, col := range cfg.Table.Columns {
		if col.Name == "id" || col.Name == "public_id" || col.Name == "created_at" ||
			col.Name == "updated_at" || col.Name == "deleted_at" || col.Name == "author_account_id" {
			continue
		}
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}

		mapping := codegen.MapColumnType(col)
		paramName := lowerCamel(col.Name)

		var value string
		if col.References != "" {
			value = fkSubquery(col.References, paramName)
		} else {
			value = paramExpr(mapping.GoType, paramName)
		}

		buf.WriteString(fmt.Sprintf("\t\t\tSet(%s, %s).\n", schemaCol(schemaVar, col.Name), value))
	}

	// Set updated_at = NOW() if present
	if analysis.HasUpdatedAt {
		buf.WriteString(fmt.Sprintf("\t\t\tSet(%s, query.Now()).\n", schemaCol(schemaVar, "updated_at")))
	}

	// WHERE clause
	whereCol := "public_id"
	if !analysis.HasPublicID && analysis.PrimaryKey != nil {
		whereCol = analysis.PrimaryKey.Name
	}
	whereMapping := codegen.MapColumnType(colByName(cfg.Table, whereCol))

	var whereParts []string
	whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, whereCol), paramExpr(whereMapping.GoType, lowerCamel(whereCol))))
	if cfg.ScopeColumn != "" {
		scopeMapping := codegen.MapColumnType(colByName(cfg.Table, cfg.ScopeColumn))
		whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, cfg.ScopeColumn), paramExpr(scopeMapping.GoType, lowerCamel(cfg.ScopeColumn))))
	}

	writeWhere(buf, whereParts)
	buf.WriteString("\t\t\tBuild())\n\n")
}

// ---------- DELETE ----------

func writeDeleteQuery(buf *strings.Builder, cfg Config, analysis codegen.TableAnalysis, schemaVar string) {
	whereCol := "public_id"
	if !analysis.HasPublicID && analysis.PrimaryKey != nil {
		whereCol = analysis.PrimaryKey.Name
	}
	whereMapping := codegen.MapColumnType(colByName(cfg.Table, whereCol))

	var whereParts []string
	whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, whereCol), paramExpr(whereMapping.GoType, lowerCamel(whereCol))))
	if cfg.ScopeColumn != "" {
		scopeMapping := codegen.MapColumnType(colByName(cfg.Table, cfg.ScopeColumn))
		whereParts = append(whereParts, fmt.Sprintf("%s.Eq(%s)", schemaCol(schemaVar, cfg.ScopeColumn), paramExpr(scopeMapping.GoType, lowerCamel(cfg.ScopeColumn))))
	}

	if analysis.HasDeletedAt {
		// Soft delete: UPDATE ... SET deleted_at = NOW()
		queryName := topcodegen.CRUD.SoftDeleteMethodName(cfg.TableName)
		buf.WriteString(fmt.Sprintf("\tquery.MustDefineExec(%q,\n", queryName))
		buf.WriteString(fmt.Sprintf("\t\tquery.Update(schema.%s).\n", schemaVar))
		buf.WriteString(fmt.Sprintf("\t\t\tSet(%s, query.Now()).\n", schemaCol(schemaVar, "deleted_at")))
		writeWhere(buf, whereParts)
		buf.WriteString("\t\t\tBuild())\n\n")
	} else {
		// Hard delete: DELETE FROM ...
		singular := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
		queryName := fmt.Sprintf("Delete%s", singular)
		buf.WriteString(fmt.Sprintf("\tquery.MustDefineExec(%q,\n", queryName))
		buf.WriteString(fmt.Sprintf("\t\tquery.Delete(schema.%s).\n", schemaVar))
		writeWhere(buf, whereParts)
		buf.WriteString("\t\t\tBuild())\n\n")
	}
}

// ---------- Helpers ----------

func writeWhere(buf *strings.Builder, parts []string) {
	if len(parts) == 0 {
		return
	}
	if len(parts) == 1 {
		buf.WriteString(fmt.Sprintf("\t\t\tWhere(%s).\n", parts[0]))
		return
	}
	buf.WriteString("\t\t\tWhere(query.And(\n")
	for _, p := range parts {
		buf.WriteString(fmt.Sprintf("\t\t\t\t%s,\n", p))
	}
	buf.WriteString("\t\t\t)).\n")
}

func colByName(table ddl.Table, name string) ddl.ColumnDefinition {
	for _, col := range table.Columns {
		if col.Name == name {
			return col
		}
	}
	return ddl.ColumnDefinition{Name: name, Type: ddl.StringType}
}

// collectParamImports determines which extra imports the generated code needs
// by checking what column types appear as query.Param[T] arguments.
func collectParamImports(cfg Config, analysis codegen.TableAnalysis) map[string]bool {
	imports := make(map[string]bool)

	addIfNeeded := func(col ddl.ColumnDefinition) {
		mapping := codegen.MapColumnType(col)
		if mapping.NeedsImport != "" {
			imports[mapping.NeedsImport] = true
		}
	}

	// WHERE clause columns (public_id or PK, scope column)
	whereCol := "public_id"
	if !analysis.HasPublicID && analysis.PrimaryKey != nil {
		whereCol = analysis.PrimaryKey.Name
	}
	addIfNeeded(colByName(cfg.Table, whereCol))
	if cfg.ScopeColumn != "" {
		addIfNeeded(colByName(cfg.Table, cfg.ScopeColumn))
	}

	// INSERT/UPDATE value columns (user columns + author_account_id)
	if analysis.HasAuthorAccountID {
		addIfNeeded(colByName(cfg.Table, "author_account_id"))
	}
	for _, col := range cfg.Table.Columns {
		if col.Name == "id" || col.Name == "public_id" || col.Name == "created_at" ||
			col.Name == "updated_at" || col.Name == "deleted_at" || col.Name == "author_account_id" {
			continue
		}
		// FK columns use query.Param[string] for the public_id, not the column's own type
		if col.References != "" && !(cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn) {
			continue
		}
		addIfNeeded(col)
	}

	return imports
}

func formatSource(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return src, fmt.Errorf("failed to format generated code: %w (source:\n%s)", err, string(src))
	}
	return formatted, nil
}
