package resourcegen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/shipq/shipq/codegen"
	"github.com/shipq/shipq/db/portsql/ddl"
	"github.com/shipq/shipq/dbstrings"
)

func testNeedsJSONImport(table ddl.Table) bool {
	for _, col := range table.Columns {
		if col.Type == ddl.JSONType && !isFixtureAutoColumn(col.Name) {
			return true
		}
	}
	return false
}

// PerOpTestGenConfig holds configuration for generating per-operation test files.
type PerOpTestGenConfig struct {
	ModulePath      string               // e.g., "myapp"
	TableName       string               // e.g., "books"
	Table           ddl.Table            // The table definition
	Schema          map[string]ddl.Table // Full schema for FK detection
	RequireAuth     bool                 // true if handlers require authentication
	Dialect         string               // "postgres", "mysql", or "sqlite"
	TestDatabaseURL string               // test database URL
	ScopeColumn     string               // e.g., "organization_id" (empty if unscoped)
}

// GenerateCreateTest generates create_test.go for a resource.
// The create test calls the route directly (not via fixture).
func GenerateCreateTest(cfg PerOpTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer
	res := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
	pkgName := cfg.TableName

	buf.WriteString("// Code generated by shipq.\n")
	buf.WriteString("package spec\n\n")

	// Imports -- create test needs resource pkg + any FK dep fixtures
	writeCreateTestImports(&buf, cfg)

	// TestCreate_Success -- call the route directly
	buf.WriteString(fmt.Sprintf("func TestCreate%s_Success(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")

	// Create non-nullable FK dependencies via their fixtures
	// (skip scope column -- the auth middleware provides it from session context)
	for _, col := range cfg.Table.Columns {
		if col.References == "" || col.Nullable || isFixtureAutoColumn(col.Name) {
			continue
		}
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		depSingular := dbstrings.ToSingular(col.References)
		depAlias := depSingular + "fixture"
		buf.WriteString(fmt.Sprintf("\t%s := %s.Create(t, ctx, tx)\n", depSingular, depAlias))
	}

	// Build the create request inline with sample values
	buf.WriteString(fmt.Sprintf("\tresp, err := client.Create%s(ctx, %s.Create%sRequest{\n", res, pkgName, res))
	for _, col := range cfg.Table.Columns {
		if isFixtureAutoColumn(col.Name) || col.Nullable {
			continue
		}
		// Scope column is injected by the handler from auth context, not from the request
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		fieldName := dbstrings.ToPascalCase(col.Name)
		if col.References != "" {
			depSingular := dbstrings.ToSingular(col.References)
			buf.WriteString(fmt.Sprintf("\t\t%s: %s.PublicId,\n", fieldName, depSingular))
		} else {
			sampleVal := getSampleValue(goBaseTypeForFixture(col.Type), col.Name)
			buf.WriteString(fmt.Sprintf("\t\t%s: %s,\n", fieldName, sampleVal))
		}
	}
	buf.WriteString("\t})\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"Create%s failed: %%v\", err)\n", res))
	buf.WriteString("\t}\n")
	buf.WriteString("\tif resp.PublicId == \"\" {\n")
	buf.WriteString("\t\tt.Fatal(\"expected non-empty public_id\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// Nullable FK tests: with and without optional dep
	for _, col := range cfg.Table.Columns {
		if col.References == "" || !col.Nullable {
			continue
		}
		depRes := dbstrings.ToPascalCase(dbstrings.ToSingular(col.References))
		fieldName := dbstrings.ToPascalCase(col.Name)

		// TestCreate_WithOptionalDep
		buf.WriteString(fmt.Sprintf("func TestCreate%s_WithOptional%s(t *testing.T) {\n", res, depRes))
		writeTestSetup(&buf, cfg)
		buf.WriteString("\n")
		// Create the optional dep via fixture
		depSingular := dbstrings.ToSingular(col.References)
		depAlias := depSingular + "fixture"
		buf.WriteString(fmt.Sprintf("\t%s := %s.Create(t, ctx, tx)\n\n", depSingular, depAlias))

		writeCreateRequestWithOptionalFK(&buf, cfg, res, pkgName, col, true)
		buf.WriteString(fmt.Sprintf("\tresp, err := client.Create%s(ctx, req)\n", res))
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"Create%s with optional %s failed: %%v\", err)\n", res, depRes))
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\tif resp.%s == nil {\n", fieldName))
		buf.WriteString(fmt.Sprintf("\t\tt.Error(\"expected %s to be set\")\n", fieldName))
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")

		// TestCreate_WithoutOptionalDep
		buf.WriteString(fmt.Sprintf("func TestCreate%s_WithoutOptional%s(t *testing.T) {\n", res, depRes))
		writeTestSetup(&buf, cfg)
		buf.WriteString("\n")

		writeCreateRequestWithOptionalFK(&buf, cfg, res, pkgName, col, false)
		buf.WriteString(fmt.Sprintf("\tresp, err := client.Create%s(ctx, req)\n", res))
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"Create%s without optional %s failed: %%v\", err)\n", res, depRes))
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\tif resp.%s != nil {\n", fieldName))
		buf.WriteString(fmt.Sprintf("\t\tt.Error(\"expected %s to be nil\")\n", fieldName))
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	// TestCreate_Unauthenticated (if auth required)
	if cfg.RequireAuth {
		buf.WriteString(fmt.Sprintf("func TestCreate%s_Unauthenticated(t *testing.T) {\n", res))
		writeUnauthTestSetup(&buf, cfg)
		buf.WriteString(fmt.Sprintf("\t_, createErr := unauthClient.Create%s(ctx, %s.Create%sRequest{})\n", res, pkgName, res))
		buf.WriteString("\tif createErr == nil {\n")
		buf.WriteString("\t\tt.Error(\"expected error for unauthenticated request\")\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return formatSource(buf.Bytes())
}

// GenerateGetOneTest generates get_one_test.go for a resource.
func GenerateGetOneTest(cfg PerOpTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer
	res := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
	pkgName := cfg.TableName

	buf.WriteString("// Code generated by shipq.\n")
	buf.WriteString("package spec\n\n")

	writeSimpleTestImports(&buf, cfg, true)

	// TestGet_Success
	buf.WriteString(fmt.Sprintf("func TestGet%s_Success(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	if cfg.ScopeColumn != "" {
		writeCreateDeps(&buf, cfg)
		writeScopedCreateHelper(&buf, cfg)
		buf.WriteString("\tcreated := createResource()\n\n")
	} else {
		buf.WriteString("\tcreated := fixture.Create(t, ctx, tx)\n\n")
	}
	buf.WriteString(fmt.Sprintf("\tgot, err := client.Get%s(ctx, %s.Get%sRequest{ID: created.PublicId})\n", res, pkgName, res))
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"Get%s failed: %%v\", err)\n", res))
	buf.WriteString("\t}\n")
	buf.WriteString("\tif got.PublicId != created.PublicId {\n")
	buf.WriteString("\t\tt.Errorf(\"ID mismatch: got %q, want %q\", got.PublicId, created.PublicId)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestGet_NotFound
	buf.WriteString(fmt.Sprintf("func TestGet%s_NotFound(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("\t_, getErr := client.Get%s(ctx, %s.Get%sRequest{ID: \"nonexistent\"})\n", res, pkgName, res))
	buf.WriteString("\tif getErr == nil {\n")
	buf.WriteString("\t\tt.Error(\"expected error for nonexistent resource\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestGet_Unauthenticated (if auth required)
	if cfg.RequireAuth {
		buf.WriteString(fmt.Sprintf("func TestGet%s_Unauthenticated(t *testing.T) {\n", res))
		writeUnauthTestSetup(&buf, cfg)
		buf.WriteString(fmt.Sprintf("\t_, getErr := unauthClient.Get%s(ctx, %s.Get%sRequest{ID: \"any\"})\n", res, pkgName, res))
		buf.WriteString("\tif getErr == nil {\n")
		buf.WriteString("\t\tt.Error(\"expected error for unauthenticated request\")\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return formatSource(buf.Bytes())
}

// GenerateListTest generates list_test.go for a resource.
func GenerateListTest(cfg PerOpTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer
	plural := dbstrings.ToPascalCase(cfg.TableName)
	pkgName := cfg.TableName

	buf.WriteString("// Code generated by shipq.\n")
	buf.WriteString("package spec\n\n")

	writeSimpleTestImports(&buf, cfg, true)

	// TestList_Success
	buf.WriteString(fmt.Sprintf("func TestList%s_Success(t *testing.T) {\n", plural))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	if cfg.ScopeColumn != "" {
		writeCreateDeps(&buf, cfg)
		writeScopedCreateHelper(&buf, cfg)
		buf.WriteString("\tc1 := createResource()\n")
		buf.WriteString("\tc2 := createResource()\n\n")
	} else {
		buf.WriteString("\tc1 := fixture.Create(t, ctx, tx)\n")
		buf.WriteString("\tc2 := fixture.Create(t, ctx, tx)\n\n")
	}
	buf.WriteString(fmt.Sprintf("\tresp, err := client.List%s(ctx, %s.List%sRequest{})\n", plural, pkgName, plural))
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"List%s failed: %%v\", err)\n", plural))
	buf.WriteString("\t}\n")
	buf.WriteString("\tif len(resp.Items) < 2 {\n")
	buf.WriteString("\t\tt.Fatalf(\"expected at least 2 items, got %d\", len(resp.Items))\n")
	buf.WriteString("\t}\n\n")
	// Verify both items are present
	buf.WriteString("\tfound1, found2 := false, false\n")
	buf.WriteString("\tfor _, item := range resp.Items {\n")
	buf.WriteString("\t\tif item.PublicId == c1.PublicId {\n")
	buf.WriteString("\t\t\tfound1 = true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tif item.PublicId == c2.PublicId {\n")
	buf.WriteString("\t\t\tfound2 = true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif !found1 || !found2 {\n")
	buf.WriteString("\t\tt.Error(\"not all created resources found in list\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestList_Pagination
	buf.WriteString(fmt.Sprintf("func TestList%s_Pagination(t *testing.T) {\n", plural))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	if cfg.ScopeColumn != "" {
		writeCreateDeps(&buf, cfg)
		writeScopedCreateHelper(&buf, cfg)
		buf.WriteString("\tfor i := 0; i < 3; i++ {\n")
		buf.WriteString("\t\tcreateResource()\n")
		buf.WriteString("\t}\n\n")
	} else {
		buf.WriteString("\tfor i := 0; i < 3; i++ {\n")
		buf.WriteString("\t\tfixture.Create(t, ctx, tx)\n")
		buf.WriteString("\t}\n\n")
	}
	// Fetch page 1 with limit 2
	buf.WriteString(fmt.Sprintf("\tpage1, err := client.List%s(ctx, %s.List%sRequest{Limit: 2})\n", plural, pkgName, plural))
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"List%s page 1 failed: %%v\", err)\n", plural))
	buf.WriteString("\t}\n")
	buf.WriteString("\tif len(page1.Items) == 0 {\n")
	buf.WriteString("\t\tt.Fatal(\"expected at least 1 item on page 1\")\n")
	buf.WriteString("\t}\n\n")
	// If the server returned a next cursor, verify page 2 works
	buf.WriteString("\tif page1.NextCursor != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tpage2, page2Err := client.List%s(ctx, %s.List%sRequest{Limit: 2, Cursor: page1.NextCursor})\n", plural, pkgName, plural))
	buf.WriteString("\t\tif page2Err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"List%s page 2 failed: %%v\", page2Err)\n", plural))
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tif len(page2.Items) < 1 {\n")
	buf.WriteString("\t\t\tt.Fatal(\"expected at least 1 item on page 2\")\n")
	buf.WriteString("\t\t}\n\n")
	// Verify no overlap between pages
	buf.WriteString("\t\tpage1IDs := make(map[string]bool)\n")
	buf.WriteString("\t\tfor _, item := range page1.Items {\n")
	buf.WriteString("\t\t\tpage1IDs[item.PublicId] = true\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tfor _, item := range page2.Items {\n")
	buf.WriteString("\t\t\tif page1IDs[item.PublicId] {\n")
	buf.WriteString("\t\t\t\tt.Errorf(\"item %s appears on both page 1 and page 2\", item.PublicId)\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestList_Unauthenticated (if auth required)
	if cfg.RequireAuth {
		buf.WriteString(fmt.Sprintf("func TestList%s_Unauthenticated(t *testing.T) {\n", plural))
		writeUnauthTestSetup(&buf, cfg)
		buf.WriteString(fmt.Sprintf("\t_, listErr := unauthClient.List%s(ctx, %s.List%sRequest{})\n", plural, pkgName, plural))
		buf.WriteString("\tif listErr == nil {\n")
		buf.WriteString("\t\tt.Error(\"expected error for unauthenticated request\")\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return formatSource(buf.Bytes())
}

// GenerateUpdateTest generates update_test.go for a resource.
func GenerateUpdateTest(cfg PerOpTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer
	res := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
	pkgName := cfg.TableName

	buf.WriteString("// Code generated by shipq.\n")
	buf.WriteString("package spec\n\n")

	writeUpdateTestImports(&buf, cfg)

	// Collect updatable columns (non-auto, non-nullable).
	// The generated SQL sets ALL columns in the UPDATE, so we must supply
	// values for every NOT NULL column to avoid constraint violations.
	type updCol struct {
		Name    string
		Pascal  string
		GoType  string
		IsFK    bool
		FKTable string // e.g., "authors"
	}
	var updCols []updCol
	updateField := ""
	for _, col := range cfg.Table.Columns {
		if isFixtureAutoColumn(col.Name) || col.Nullable {
			continue
		}
		// Scope column is not updatable (excluded from update request)
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		pascal := dbstrings.ToPascalCase(col.Name)
		if col.References != "" {
			updCols = append(updCols, updCol{Name: col.Name, Pascal: pascal, GoType: "string", IsFK: true, FKTable: col.References})
		} else {
			goType := goBaseTypeForFixture(col.Type)
			updCols = append(updCols, updCol{Name: col.Name, Pascal: pascal, GoType: goType})
			if updateField == "" && goType == "string" {
				updateField = col.Name
			}
		}
	}

	// TestUpdate_Success
	buf.WriteString(fmt.Sprintf("func TestUpdate%s_Success(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	if cfg.ScopeColumn != "" {
		writeCreateDeps(&buf, cfg)
		writeScopedCreateHelper(&buf, cfg)
		buf.WriteString("\tcreated := createResource()\n\n")
	} else {
		buf.WriteString("\tcreated := fixture.Create(t, ctx, tx)\n\n")
	}

	// Emit updated value for the target field
	if updateField != "" {
		buf.WriteString(fmt.Sprintf("\tupdatedVal := \"updated_%s\"\n", updateField))
	}

	// Build the update request with ALL updatable fields.
	// For non-target, non-FK columns we use sample values because
	// CreateResult only has Id/PublicId — we cannot reference created.<Field>.
	// For FK columns, create the dependency via its fixture to get a valid
	// public_id (since the create response returns the internal integer).
	for _, uc := range updCols {
		if uc.IsFK {
			depSingular := dbstrings.ToSingular(uc.FKTable)
			depAlias := depSingular + "fixture"
			buf.WriteString(fmt.Sprintf("\t%sForUpdate := %s.Create(t, ctx, tx)\n", depSingular, depAlias))
		} else if uc.Name != updateField {
			sampleVal := getSampleValue(uc.GoType, uc.Name)
			varName := "keep" + uc.Pascal
			buf.WriteString(fmt.Sprintf("\t%s := %s\n", varName, sampleVal))
		}
	}

	buf.WriteString(fmt.Sprintf("\tupdated, err := client.Update%s(ctx, %s.Update%sRequest{\n", res, pkgName, res))
	buf.WriteString("\t\tID: created.PublicId,\n")
	for _, uc := range updCols {
		if uc.Name == updateField {
			buf.WriteString(fmt.Sprintf("\t\t%s: &updatedVal,\n", uc.Pascal))
		} else if uc.IsFK {
			depSingular := dbstrings.ToSingular(uc.FKTable)
			buf.WriteString(fmt.Sprintf("\t\t%s: &%sForUpdate.PublicId,\n", uc.Pascal, depSingular))
		} else {
			// Use a sample value — CreateResult only has Id/PublicId,
			// so we cannot reference created.<Field>.
			varName := "keep" + uc.Pascal
			buf.WriteString(fmt.Sprintf("\t\t%s: &%s,\n", uc.Pascal, varName))
		}
	}
	buf.WriteString("\t})\n")

	buf.WriteString("\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"Update%s failed: %%v\", err)\n", res))
	buf.WriteString("\t}\n")

	if updateField != "" {
		fieldPascal := dbstrings.ToPascalCase(updateField)
		buf.WriteString(fmt.Sprintf("\tif updated.%s != updatedVal {\n", fieldPascal))
		buf.WriteString(fmt.Sprintf("\t\tt.Errorf(\"%s mismatch: got %%q, want %%q\", updated.%s, updatedVal)\n", fieldPascal, fieldPascal))
		buf.WriteString("\t}\n")
	} else {
		buf.WriteString("\t_ = updated\n")
	}
	buf.WriteString("}\n\n")

	// TestUpdate_NotFound
	buf.WriteString(fmt.Sprintf("func TestUpdate%s_NotFound(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("\t_, updateErr := client.Update%s(ctx, %s.Update%sRequest{ID: \"nonexistent\"})\n", res, pkgName, res))
	buf.WriteString("\tif updateErr == nil {\n")
	buf.WriteString("\t\tt.Error(\"expected error for nonexistent resource\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestUpdate_Unauthenticated (if auth required)
	if cfg.RequireAuth {
		buf.WriteString(fmt.Sprintf("func TestUpdate%s_Unauthenticated(t *testing.T) {\n", res))
		writeUnauthTestSetup(&buf, cfg)
		buf.WriteString(fmt.Sprintf("\t_, updateErr := unauthClient.Update%s(ctx, %s.Update%sRequest{ID: \"any\"})\n", res, pkgName, res))
		buf.WriteString("\tif updateErr == nil {\n")
		buf.WriteString("\t\tt.Error(\"expected error for unauthenticated request\")\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return formatSource(buf.Bytes())
}

// GenerateSoftDeleteTest generates soft_delete_test.go for a resource.
func GenerateSoftDeleteTest(cfg PerOpTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer
	res := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
	plural := dbstrings.ToPascalCase(cfg.TableName)
	pkgName := cfg.TableName

	buf.WriteString("// Code generated by shipq.\n")
	buf.WriteString("package spec\n\n")

	writeSimpleTestImports(&buf, cfg, true)

	// TestSoftDelete_Success
	buf.WriteString(fmt.Sprintf("func TestSoftDelete%s_Success(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	if cfg.ScopeColumn != "" {
		writeCreateDeps(&buf, cfg)
		writeScopedCreateHelper(&buf, cfg)
		buf.WriteString("\tcreated := createResource()\n\n")
	} else {
		buf.WriteString("\tcreated := fixture.Create(t, ctx, tx)\n\n")
	}
	buf.WriteString(fmt.Sprintf("\t_, deleteErr := client.SoftDelete%s(ctx, %s.SoftDelete%sRequest{ID: created.PublicId})\n", res, pkgName, res))
	buf.WriteString("\tif deleteErr != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"SoftDelete%s failed: %%v\", deleteErr)\n", res))
	buf.WriteString("\t}\n\n")
	// Verify GetOne returns 404
	buf.WriteString(fmt.Sprintf("\t_, getErr := client.Get%s(ctx, %s.Get%sRequest{ID: created.PublicId})\n", res, pkgName, res))
	buf.WriteString("\tif getErr == nil {\n")
	buf.WriteString("\t\tt.Error(\"expected 404 after soft delete\")\n")
	buf.WriteString("\t}\n\n")
	// Verify List excludes deleted item
	buf.WriteString(fmt.Sprintf("\tlistResp, listErr := client.List%s(ctx, %s.List%sRequest{})\n", plural, pkgName, plural))
	buf.WriteString("\tif listErr != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"List%s failed: %%v\", listErr)\n", plural))
	buf.WriteString("\t}\n")
	buf.WriteString("\tfor _, item := range listResp.Items {\n")
	buf.WriteString("\t\tif item.PublicId == created.PublicId {\n")
	buf.WriteString("\t\t\tt.Error(\"deleted resource should not appear in list\")\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestSoftDelete_NotFound -- soft delete is idempotent, so a
	// nonexistent resource returns success (not an error).
	buf.WriteString(fmt.Sprintf("func TestSoftDelete%s_NotFound(t *testing.T) {\n", res))
	writeTestSetup(&buf, cfg)
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("\t_, delErr := client.SoftDelete%s(ctx, %s.SoftDelete%sRequest{ID: \"nonexistent\"})\n", res, pkgName, res))
	buf.WriteString("\tif delErr != nil {\n")
	buf.WriteString("\t\tt.Errorf(\"soft delete of nonexistent resource should succeed (idempotent): %v\", delErr)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// TestSoftDelete_Unauthenticated (if auth required)
	if cfg.RequireAuth {
		buf.WriteString(fmt.Sprintf("func TestSoftDelete%s_Unauthenticated(t *testing.T) {\n", res))
		writeUnauthTestSetup(&buf, cfg)
		buf.WriteString(fmt.Sprintf("\t_, delErr := unauthClient.SoftDelete%s(ctx, %s.SoftDelete%sRequest{ID: \"any\"})\n", res, pkgName, res))
		buf.WriteString("\tif delErr == nil {\n")
		buf.WriteString("\t\tt.Error(\"expected error for unauthenticated request\")\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return formatSource(buf.Bytes())
}

// ---- Shared helpers ----

// GenerateTestHelpers generates helpers_test.go with TestMain, DB setup, and
// setupTest / setupAuthenticatedTest / setupUnauthenticatedTest helper functions.
// This is the single source of truth for all test infrastructure in a resource
// test package.
func GenerateTestHelpers(cfg PerOpTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by shipq.\n")
	buf.WriteString("package spec\n\n")

	// --- Imports ---
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"database/sql\"\n")
	buf.WriteString("\t\"os\"\n")
	buf.WriteString("\t\"testing\"\n")
	buf.WriteString("\t\"time\"\n")
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("\t%s\n", codegen.DriverImportForDialect(cfg.Dialect)))
	buf.WriteString("\n")
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/api"))
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/config"))
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/shipq/lib/crypto"))
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/shipq/lib/nanoid"))
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/shipq/queries"))
	buf.WriteString(fmt.Sprintf("\tdbrunner %q\n", cfg.ModulePath+"/shipq/queries/"+cfg.Dialect))
	buf.WriteString(")\n\n")

	// --- Package-level DB ---
	buf.WriteString("var testDB *sql.DB\n\n")

	// --- TestMain ---
	buf.WriteString("func TestMain(m *testing.M) {\n")
	// Always set COOKIE_SECRET -- the test server may have auth middleware
	// even when this particular resource is public.
	buf.WriteString("\tos.Setenv(\"COOKIE_SECRET\", \"test-secret-key-for-testing-only\")\n\n")
	buf.WriteString("\tdbURL := os.Getenv(\"TEST_DATABASE_URL\")\n")
	buf.WriteString("\tif dbURL == \"\" {\n")
	buf.WriteString(fmt.Sprintf("\t\tdbURL = %q\n", cfg.TestDatabaseURL))
	buf.WriteString("\t}\n")
	buf.WriteString("\tif dbURL == \"\" {\n")
	buf.WriteString("\t\tpanic(\"TEST_DATABASE_URL not set and no fallback configured\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif !config.IsLocalhostURL(dbURL) {\n")
	buf.WriteString("\t\tpanic(\"test database URL must point to localhost\")\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\tdriver, dsn := config.ParseDatabaseURL(dbURL)\n\n")
	buf.WriteString("\tvar err error\n")
	buf.WriteString("\ttestDB, err = sql.Open(driver, dsn)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tpanic(\"failed to connect to test database: \" + err.Error())\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer testDB.Close()\n\n")
	buf.WriteString("\tos.Exit(m.Run())\n")
	buf.WriteString("}\n\n")

	// --- setupTest (for public / non-auth resources) ---
	buf.WriteString("// setupTest creates an isolated test server and returns an unauthenticated client\n")
	buf.WriteString("// plus the underlying transaction for fixture creation.\n")
	buf.WriteString("func setupTest(t *testing.T) (context.Context, *api.Client, *sql.Tx) {\n")
	buf.WriteString("\tt.Helper()\n")
	buf.WriteString("\tts := api.NewUnauthenticatedTestServer(t, testDB)\n")
	buf.WriteString("\tclient := api.NewUnauthenticatedTestClient(ts.Server)\n")
	buf.WriteString("\treturn context.Background(), client, ts.Tx()\n")
	buf.WriteString("}\n\n")

	// --- createTestUser helper ---
	buf.WriteString("// createTestUser inserts a test account with an organization and session\n")
	buf.WriteString("// directly via the query runner, returning a signed session cookie value.\n")
	buf.WriteString("// This avoids depending on the /signup endpoint which is generated separately.\n")
	buf.WriteString("func createTestUser(t *testing.T, ts *api.TestServer, email, password, firstName, lastName string) string {\n")
	buf.WriteString("\tt.Helper()\n")
	buf.WriteString("\tctx := context.Background()\n")
	buf.WriteString("\trunner := dbrunner.NewQueryRunner(ts.Tx())\n\n")
	buf.WriteString("\tpasswordHash, err := crypto.HashPassword(password)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tt.Fatalf(\"failed to hash password: %v\", err)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\torg, err := runner.SignupCreateOrganization(ctx, queries.SignupCreateOrganizationParams{\n")
	buf.WriteString("\t\tPublicId:    nanoid.New(),\n")
	buf.WriteString("\t\tName:        firstName + \"'s Organization \" + nanoid.New(),\n")
	buf.WriteString("\t\tDescription: \"\",\n")
	buf.WriteString("\t})\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tt.Fatalf(\"failed to create organization: %v\", err)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\taccount, err := runner.SignupCreateAccount(ctx, queries.SignupCreateAccountParams{\n")
	buf.WriteString("\t\tPublicId:              nanoid.New(),\n")
	buf.WriteString("\t\tFirstName:             firstName,\n")
	buf.WriteString("\t\tLastName:              lastName,\n")
	buf.WriteString("\t\tEmail:                 email,\n")
	buf.WriteString("\t\tPasswordHash:          passwordHash,\n")
	buf.WriteString("\t\tDefaultOrganizationId: org.Id,\n")
	buf.WriteString("\t})\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tt.Fatalf(\"failed to create account: %v\", err)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\t_, err = runner.SignupCreateOrganizationUser(ctx, queries.SignupCreateOrganizationUserParams{\n")
	buf.WriteString("\t\tPublicId:       nanoid.New(),\n")
	buf.WriteString("\t\tOrganizationId: org.Id,\n")
	buf.WriteString("\t\tAccountId:      account.Id,\n")
	buf.WriteString("\t})\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tt.Fatalf(\"failed to link account to organization: %v\", err)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\tsession, err := runner.SignupCreateSession(ctx, queries.SignupCreateSessionParams{\n")
	buf.WriteString("\t\tPublicId:  nanoid.New(),\n")
	buf.WriteString("\t\tAccountId: account.Id,\n")
	buf.WriteString("\t\tExpiresAt: time.Now().UTC().Add(14 * 24 * time.Hour).Format(\"2006-01-02 15:04:05\"),\n")
	buf.WriteString("\t})\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\tt.Fatalf(\"failed to create session: %v\", err)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\treturn crypto.SignCookie(session.PublicId, []byte(config.Settings.COOKIE_SECRET))\n")
	buf.WriteString("}\n\n")

	// --- setupAuthenticatedTest ---
	buf.WriteString("// setupAuthenticatedTest creates an isolated test server, inserts a test\n")
	buf.WriteString("// user directly via the query runner, and returns an authenticated client\n")
	buf.WriteString("// plus the underlying transaction for fixture creation.\n")
	buf.WriteString("func setupAuthenticatedTest(t *testing.T) (context.Context, *api.Client, *sql.Tx) {\n")
	buf.WriteString("\tt.Helper()\n")
	buf.WriteString("\tts := api.NewUnauthenticatedTestServer(t, testDB)\n")
	buf.WriteString("\tctx := context.Background()\n\n")
	buf.WriteString("\ttestEmail := \"test-\" + nanoid.New() + \"@example.com\"\n")
	buf.WriteString("\tsessionCookie := createTestUser(t, ts, testEmail, \"testpass123\", \"Test\", \"User\")\n\n")
	buf.WriteString("\tclient := api.NewAuthenticatedTestClient(ts.Server, sessionCookie)\n")
	buf.WriteString("\treturn ctx, client, ts.Tx()\n")
	buf.WriteString("}\n\n")

	// --- setupUnauthenticatedTest ---
	buf.WriteString("// setupUnauthenticatedTest creates an isolated test server and returns an\n")
	buf.WriteString("// unauthenticated client. Used for negative auth tests.\n")
	buf.WriteString("func setupUnauthenticatedTest(t *testing.T) (context.Context, *api.Client, *sql.Tx) {\n")
	buf.WriteString("\tt.Helper()\n")
	buf.WriteString("\tts := api.NewUnauthenticatedTestServer(t, testDB)\n")
	buf.WriteString("\tclient := api.NewUnauthenticatedTestClient(ts.Server)\n")
	buf.WriteString("\treturn context.Background(), client, ts.Tx()\n")
	buf.WriteString("}\n\n")

	return formatSource(buf.Bytes())
}

// ---- Import helpers ----

// writeSimpleTestImports writes imports for test files that only need the
// resource package and the fixture package (get_one, list, delete tests).
func writeSimpleTestImports(buf *bytes.Buffer, cfg PerOpTestGenConfig, needsFixture bool) {
	buf.WriteString("import (\n")
	buf.WriteString("\t\"testing\"\n\n")
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/api/"+cfg.TableName))
	if needsFixture && cfg.ScopeColumn == "" {
		// Only import the resource fixture for unscoped resources.
		// Scoped resources create via the HTTP client instead.
		buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/api/"+cfg.TableName+"/fixture"))
	}
	// FK dep fixtures (both nullable deps and non-nullable deps for scoped resources)
	for _, col := range cfg.Table.Columns {
		if col.References == "" || isFixtureAutoColumn(col.Name) {
			continue
		}
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		// For scoped resources, import all non-nullable FK dep fixtures
		// (they're needed by writeCreateDeps/writeScopedCreateHelper).
		// For unscoped resources, only import nullable FK dep fixtures.
		if col.Nullable || (cfg.ScopeColumn != "" && needsFixture) {
			depSingular := dbstrings.ToSingular(col.References)
			depAlias := depSingular + "fixture"
			buf.WriteString(fmt.Sprintf("\t%s %q\n", depAlias, cfg.ModulePath+"/api/"+col.References+"/fixture"))
		}
	}
	buf.WriteString(")\n\n")
}

// writeCreateTestImports writes imports for the create test file.
// It needs the resource package and any FK dependency fixture packages
// (both nullable and non-nullable) since create calls the route directly.
func writeCreateTestImports(buf *bytes.Buffer, cfg PerOpTestGenConfig) {
	buf.WriteString("import (\n")
	if testNeedsJSONImport(cfg.Table) {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	buf.WriteString("\t\"testing\"\n\n")
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/api/"+cfg.TableName))
	// All FK dep fixtures (create needs them to set up dependencies)
	// Scope column deps are excluded -- the auth middleware provides the org ID
	for _, col := range cfg.Table.Columns {
		if col.References != "" && !isFixtureAutoColumn(col.Name) {
			if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
				continue
			}
			depSingular := dbstrings.ToSingular(col.References)
			depAlias := depSingular + "fixture"
			buf.WriteString(fmt.Sprintf("\t%s %q\n", depAlias, cfg.ModulePath+"/api/"+col.References+"/fixture"))
		}
	}
	buf.WriteString(")\n\n")
}

// writeUpdateTestImports writes imports for the update test file.
// It needs the resource package, fixture package, and FK dependency fixtures.
func writeUpdateTestImports(buf *bytes.Buffer, cfg PerOpTestGenConfig) {
	buf.WriteString("import (\n")
	if testNeedsJSONImport(cfg.Table) {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	buf.WriteString("\t\"testing\"\n\n")
	buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/api/"+cfg.TableName))
	if cfg.ScopeColumn == "" {
		buf.WriteString(fmt.Sprintf("\t%q\n", cfg.ModulePath+"/api/"+cfg.TableName+"/fixture"))
	}
	// FK dep fixtures (both nullable and non-nullable needed for update)
	// Scope column deps are excluded -- the auth middleware provides the org ID
	for _, col := range cfg.Table.Columns {
		if col.References != "" && !isFixtureAutoColumn(col.Name) {
			if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
				continue
			}
			depSingular := dbstrings.ToSingular(col.References)
			depAlias := depSingular + "fixture"
			buf.WriteString(fmt.Sprintf("\t%s %q\n", depAlias, cfg.ModulePath+"/api/"+col.References+"/fixture"))
		}
	}
	buf.WriteString(")\n\n")
}

// ---- Test setup helpers ----

// writeTestSetup emits a one-line call to the appropriate setup function.
func writeTestSetup(buf *bytes.Buffer, cfg PerOpTestGenConfig) {
	if cfg.RequireAuth {
		buf.WriteString("\tctx, client, tx := setupAuthenticatedTest(t)\n")
		buf.WriteString("\t_ = tx\n")
	} else {
		buf.WriteString("\tctx, client, tx := setupTest(t)\n")
		buf.WriteString("\t_ = tx\n")
	}
}

// writeUnauthTestSetup emits a one-line call to setupUnauthenticatedTest.
func writeUnauthTestSetup(buf *bytes.Buffer, cfg PerOpTestGenConfig) {
	buf.WriteString("\tctx, unauthClient, _ := setupUnauthenticatedTest(t)\n")
}

// ---- Other helpers ----

func writeCreateRequestWithOptionalFK(buf *bytes.Buffer, cfg PerOpTestGenConfig, res, pkgName string, targetCol ddl.ColumnDefinition, includeOptional bool) {
	// For the optional FK test, we still need non-nullable FK deps
	// via their fixtures (skip scope column)
	for _, col := range cfg.Table.Columns {
		if col.References != "" && !col.Nullable && !isFixtureAutoColumn(col.Name) {
			if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
				continue
			}
			depSingular := dbstrings.ToSingular(col.References)
			depAlias := depSingular + "fixture"
			buf.WriteString(fmt.Sprintf("\t%sDep := %s.Create(t, ctx, tx)\n", depSingular, depAlias))
		}
	}

	buf.WriteString(fmt.Sprintf("\treq := %s.Create%sRequest{\n", pkgName, res))
	for _, col := range cfg.Table.Columns {
		if isFixtureAutoColumn(col.Name) {
			continue
		}
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		fieldName := dbstrings.ToPascalCase(col.Name)
		if col.Name == targetCol.Name {
			if includeOptional {
				depSingular := dbstrings.ToSingular(col.References)
				buf.WriteString(fmt.Sprintf("\t\t%s: &%s.PublicId,\n", fieldName, depSingular))
			}
			continue
		}
		if col.Nullable {
			continue
		}
		if col.References != "" {
			depSingular := dbstrings.ToSingular(col.References)
			buf.WriteString(fmt.Sprintf("\t\t%s: %sDep.PublicId,\n", fieldName, depSingular))
		} else {
			sampleVal := getSampleValue(goBaseTypeForFixture(col.Type), col.Name)
			buf.WriteString(fmt.Sprintf("\t\t%s: %s,\n", fieldName, sampleVal))
		}
	}
	buf.WriteString("\t}\n")
}

// writeScopedCreateHelper generates a test-local createResource helper function
// that creates a resource via the HTTP client. FK dependencies are created once
// at the enclosing scope via writeCreateDeps. This avoids scoping issues where
// fixtures create resources in a different org than the test user.
func writeScopedCreateHelper(buf *bytes.Buffer, cfg PerOpTestGenConfig) {
	res := dbstrings.ToPascalCase(dbstrings.ToSingular(cfg.TableName))
	pkgName := cfg.TableName
	singular := dbstrings.ToSingular(cfg.TableName)

	buf.WriteString(fmt.Sprintf("\tcreateResource := func() %s.Create%sResponse {\n", pkgName, res))
	buf.WriteString("\t\tt.Helper()\n")
	buf.WriteString(fmt.Sprintf("\t\tresp, err := client.Create%s(ctx, %s.Create%sRequest{\n", res, pkgName, res))
	for _, col := range cfg.Table.Columns {
		if isFixtureAutoColumn(col.Name) || col.Nullable {
			continue
		}
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		fieldName := dbstrings.ToPascalCase(col.Name)
		if col.References != "" {
			depSingular := dbstrings.ToSingular(col.References)
			buf.WriteString(fmt.Sprintf("\t\t\t%s: %sDep.PublicId,\n", fieldName, depSingular))
		} else {
			sampleVal := getSampleValue(goBaseTypeForFixture(col.Type), col.Name)
			buf.WriteString(fmt.Sprintf("\t\t\t%s: %s,\n", fieldName, sampleVal))
		}
	}
	buf.WriteString("\t\t})\n")
	buf.WriteString("\t\tif err != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"failed to create %s: %%v\", err)\n", singular))
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\treturn resp\n")
	buf.WriteString("\t}\n\n")
}

// writeCreateDeps generates variable declarations for non-nullable FK
// dependencies (excluding the scope column). Must be called before
// writeScopedCreateHelper.
func writeCreateDeps(buf *bytes.Buffer, cfg PerOpTestGenConfig) {
	for _, col := range cfg.Table.Columns {
		if col.References == "" || col.Nullable || isFixtureAutoColumn(col.Name) {
			continue
		}
		if cfg.ScopeColumn != "" && col.Name == cfg.ScopeColumn {
			continue
		}
		depSingular := dbstrings.ToSingular(col.References)
		depAlias := depSingular + "fixture"
		buf.WriteString(fmt.Sprintf("\t%sDep := %s.Create(t, ctx, tx)\n", depSingular, depAlias))
	}
}

func formatSource(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return src, fmt.Errorf("failed to format test code: %w\nunformatted:\n%s", err, string(src))
	}
	return formatted, nil
}
