package authgen

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/shipq/shipq/codegen"
)

// RBACTestGenConfig holds configuration for generating RBAC integration tests.
type RBACTestGenConfig struct {
	ModulePath      string // e.g., "myapp"
	OutputPkg       string // package name for generated code (e.g., "api")
	Dialect         string // "postgres", "mysql", or "sqlite"
	TestDatabaseURL string // test database URL derived from shipq.ini
	ScopeColumn     string // from [db] scope in shipq.ini; controls which variant to emit
}

// GenerateRBACTests generates api/zz_generated_rbac_test.go containing RBAC
// integration tests that exercise the CheckRBAC query through the HTTP middleware.
func GenerateRBACTests(cfg RBACTestGenConfig) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by shipq.\n")
	fmt.Fprintf(&buf, "package %s\n\n", cfg.OutputPkg)

	writeRBACTestImports(&buf, cfg)
	writeRBACTestServerSetup(&buf, cfg)
	writeRBACCreateTestUser(&buf, cfg)

	// 5 core tests (both variants)
	writeTestGlobalOwnerCanAccessAnything(&buf, cfg)
	writeTestUnrestrictedRouteAllowsAnyAuthenticatedUser(&buf, cfg)
	writeTestRestrictedRouteAllowsUserWithMatchingRole(&buf, cfg)
	writeTestRestrictedRouteDeniesUserWithoutMatchingRole(&buf, cfg)
	writeTestWildcardMethodMatchesAnyMethod(&buf, cfg)

	// 6th test only for scoped variant
	if cfg.ScopeColumn != "" {
		writeTestOrgScopedRolesDoNotCrossOrgs(&buf, cfg)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("failed to format RBAC test code: %w\nunformatted:\n%s", err, buf.String())
	}
	return formatted, nil
}

func writeRBACTestImports(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"database/sql\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"os\"\n")
	buf.WriteString("\t\"testing\"\n")
	buf.WriteString("\t\"time\"\n")
	buf.WriteString("\n")

	fmt.Fprintf(buf, "\t%s\n", codegen.DriverImportForDialect(cfg.Dialect))
	buf.WriteString("\n")

	fmt.Fprintf(buf, "\t%q\n", cfg.ModulePath+"/config")
	fmt.Fprintf(buf, "\t%q\n", cfg.ModulePath+"/shipq/lib/crypto")
	fmt.Fprintf(buf, "\t%q\n", cfg.ModulePath+"/shipq/lib/nanoid")
	fmt.Fprintf(buf, "\t%q\n", cfg.ModulePath+"/shipq/queries")
	fmt.Fprintf(buf, "\tdbrunner %q\n", cfg.ModulePath+"/shipq/queries/"+cfg.Dialect)
	buf.WriteString(")\n\n")
}

func writeRBACTestServerSetup(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`// newRBACTestServer creates a test server for RBAC tests.
func newRBACTestServer(t *testing.T) *TestServer {
	t.Helper()
	os.Setenv("COOKIE_SECRET", "test-secret-key-for-testing-only")
	dbURL := os.Getenv("TEST_DATABASE_URL")
	if dbURL == "" {
`)
	fmt.Fprintf(buf, "\t\tdbURL = %q\n", cfg.TestDatabaseURL)
	buf.WriteString(`	}
	if dbURL == "" {
		t.Skip("TEST_DATABASE_URL not set, skipping RBAC integration test")
	}
	if !config.IsLocalhostURL(dbURL) {
		t.Fatal("test database URL must point to localhost")
	}

	driver, dsn := config.ParseDatabaseURL(dbURL)
	db, err := sql.Open(driver, dsn)
	if err != nil {
		t.Fatalf("failed to open database: %v", err)
	}
	t.Cleanup(func() { db.Close() })

	return NewUnauthenticatedTestServer(t, db)
}

`)
}

func writeRBACCreateTestUser(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	// Returns accountPublicID (string) for use with CRUD FK params, and
	// orgID (int64) for scoped role creation (which uses the native scope column type).
	buf.WriteString(`// rbacCreateTestUser creates a test account with an org and session, returning
// the signed session cookie, the account's public_id (for CRUD FK references),
// and the internal org ID (for scoped role creation).
func rbacCreateTestUser(t *testing.T, ts *TestServer, email, firstName string) (cookie string, accountPublicID string, orgID int64) {
	t.Helper()
	ctx := context.Background()
	runner := dbrunner.NewQueryRunner(ts.Tx())

	passwordHash, err := crypto.HashPassword("password")
	if err != nil {
		t.Fatalf("failed to hash password: %v", err)
	}

	org, err := runner.SignupCreateOrganization(ctx, queries.SignupCreateOrganizationParams{
		PublicId:    nanoid.New(),
		Name:        firstName + "'s Organization",
		Description: "",
	})
	if err != nil {
		t.Fatalf("failed to create organization: %v", err)
	}

	account, err := runner.SignupCreateAccount(ctx, queries.SignupCreateAccountParams{
		PublicId:              nanoid.New(),
		FirstName:             firstName,
		LastName:              "Test",
		Email:                 email,
		PasswordHash:          passwordHash,
		DefaultOrganizationId: org.Id,
	})
	if err != nil {
		t.Fatalf("failed to create account: %v", err)
	}

	_, err = runner.SignupCreateOrganizationUser(ctx, queries.SignupCreateOrganizationUserParams{
		PublicId:       nanoid.New(),
		OrganizationId: org.Id,
		AccountId:      account.Id,
	})
	if err != nil {
		t.Fatalf("failed to link account to organization: %v", err)
	}

	session, err := runner.SignupCreateSession(ctx, queries.SignupCreateSessionParams{
		PublicId:  nanoid.New(),
		AccountId: account.Id,
		ExpiresAt: time.Now().UTC().Add(14 * 24 * time.Hour).Format("2006-01-02 15:04:05"),
	})
	if err != nil {
		t.Fatalf("failed to create session: %v", err)
	}

	signedCookie := crypto.SignCookie(session.PublicId, []byte(config.Settings.COOKIE_SECRET))
	return signedCookie, account.PublicId, org.Id
}

`)
}

func writeTestGlobalOwnerCanAccessAnything(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`func TestRBAC_GlobalOwnerCanAccessAnything(t *testing.T) {
	ts := newRBACTestServer(t)
	ctx := context.Background()
	runner := dbrunner.NewQueryRunner(ts.Tx())

	cookie, accountPublicID, _ := rbacCreateTestUser(t, ts, "owner@test.com", "Owner")

`)

	if cfg.ScopeColumn != "" {
		buf.WriteString(`	// Create GLOBAL_OWNER role (system-level, organization_id = NULL)
	globalOwnerRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId:        nanoid.New(),
		Name:            "GLOBAL_OWNER",
		OrganizationId:  nil,
	})
`)
	} else {
		buf.WriteString(`	// Create GLOBAL_OWNER role (global)
	globalOwnerRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId: nanoid.New(),
		Name:     "GLOBAL_OWNER",
	})
`)
	}

	buf.WriteString(`	if err != nil {
		t.Fatalf("failed to create GLOBAL_OWNER role: %v", err)
	}

	// Assign GLOBAL_OWNER to our test user
	_, err = runner.CreateAccountRole(ctx, queries.CreateAccountRoleParams{
		PublicId:  nanoid.New(),
		AccountId: accountPublicID,
		RoleId:    globalOwnerRole.PublicId,
	})
	if err != nil {
		t.Fatalf("failed to assign GLOBAL_OWNER: %v", err)
	}

	// The /me endpoint should be accessible (200, not 403)
	req, _ := http.NewRequest("GET", ts.Server.URL+"/me", nil)
	req.AddCookie(&http.Cookie{Name: "session", Value: cookie})
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusForbidden {
		t.Error("GLOBAL_OWNER should bypass all RBAC checks, but got 403")
	}
	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected status 200, got %d", resp.StatusCode)
	}
}

`)
}

func writeTestUnrestrictedRouteAllowsAnyAuthenticatedUser(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`func TestRBAC_UnrestrictedRouteAllowsAnyAuthenticatedUser(t *testing.T) {
	ts := newRBACTestServer(t)

	// Create a user with NO roles at all
	cookie, _, _ := rbacCreateTestUser(t, ts, "noroles@test.com", "NoRoles")

	// The /me endpoint has no role_actions restricting it, so it should be open to any authenticated user
	req, _ := http.NewRequest("GET", ts.Server.URL+"/me", nil)
	req.AddCookie(&http.Cookie{Name: "session", Value: cookie})
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusForbidden {
		t.Error("unrestricted route should allow any authenticated user, but got 403")
	}
	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected status 200, got %d", resp.StatusCode)
	}
}

`)
}

func writeTestRestrictedRouteAllowsUserWithMatchingRole(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`func TestRBAC_RestrictedRouteAllowsUserWithMatchingRole(t *testing.T) {
	ts := newRBACTestServer(t)
	ctx := context.Background()
	runner := dbrunner.NewQueryRunner(ts.Tx())

	cookie, accountPublicID, orgID := rbacCreateTestUser(t, ts, "admin@test.com", "Admin")

`)
	if cfg.ScopeColumn != "" {
		buf.WriteString(`	// Create a role scoped to this org
	adminRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId:        nanoid.New(),
		Name:            "admin",
		OrganizationId:  &orgID,
	})
`)
	} else {
		buf.WriteString(`	// Create a role
	adminRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId: nanoid.New(),
		Name:     "admin",
	})
	_ = orgID // unused in unscoped variant
`)
	}

	buf.WriteString(`	if err != nil {
		t.Fatalf("failed to create admin role: %v", err)
	}

	// Restrict /me GET to admin role
	_, err = runner.CreateRoleAction(ctx, queries.CreateRoleActionParams{
		PublicId:   nanoid.New(),
		RoleId:     adminRole.PublicId,
		RoutePath:  "/me",
		Method:     "GET",
	})
	if err != nil {
		t.Fatalf("failed to create role_action: %v", err)
	}

	// Assign admin role to this user
	_, err = runner.CreateAccountRole(ctx, queries.CreateAccountRoleParams{
		PublicId:  nanoid.New(),
		AccountId: accountPublicID,
		RoleId:    adminRole.PublicId,
	})
	if err != nil {
		t.Fatalf("failed to assign admin role: %v", err)
	}

	// User with matching role should have access
	req, _ := http.NewRequest("GET", ts.Server.URL+"/me", nil)
	req.AddCookie(&http.Cookie{Name: "session", Value: cookie})
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusForbidden {
		t.Error("user with matching role should have access, but got 403")
	}
	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected status 200, got %d", resp.StatusCode)
	}
}

`)
}

func writeTestRestrictedRouteDeniesUserWithoutMatchingRole(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`func TestRBAC_RestrictedRouteDeniesUserWithoutMatchingRole(t *testing.T) {
	ts := newRBACTestServer(t)
	ctx := context.Background()
	runner := dbrunner.NewQueryRunner(ts.Tx())

	cookie, _, orgID := rbacCreateTestUser(t, ts, "denied@test.com", "Denied")

`)
	if cfg.ScopeColumn != "" {
		buf.WriteString(`	// Create a role scoped to this org (but don't assign it to the user)
	restrictRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId:        nanoid.New(),
		Name:            "restricted_viewer",
		OrganizationId:  &orgID,
	})
`)
	} else {
		buf.WriteString(`	// Create a role (but don't assign it to the user)
	restrictRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId: nanoid.New(),
		Name:     "restricted_viewer",
	})
	_ = orgID // unused in unscoped variant
`)
	}

	buf.WriteString(`	if err != nil {
		t.Fatalf("failed to create role: %v", err)
	}

	// Restrict /me GET to this role
	_, err = runner.CreateRoleAction(ctx, queries.CreateRoleActionParams{
		PublicId:   nanoid.New(),
		RoleId:     restrictRole.PublicId,
		RoutePath:  "/me",
		Method:     "GET",
	})
	if err != nil {
		t.Fatalf("failed to create role_action: %v", err)
	}

	// User WITHOUT the role should be denied
	req, _ := http.NewRequest("GET", ts.Server.URL+"/me", nil)
	req.AddCookie(&http.Cookie{Name: "session", Value: cookie})
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusForbidden {
		t.Errorf("expected status 403 Forbidden, got %d", resp.StatusCode)
	}
}

`)
}

func writeTestWildcardMethodMatchesAnyMethod(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`func TestRBAC_WildcardMethodMatchesAnyMethod(t *testing.T) {
	ts := newRBACTestServer(t)
	ctx := context.Background()
	runner := dbrunner.NewQueryRunner(ts.Tx())

	cookie, accountPublicID, orgID := rbacCreateTestUser(t, ts, "wildcard@test.com", "Wildcard")

`)
	if cfg.ScopeColumn != "" {
		buf.WriteString(`	// Create a role with wildcard method
	wildcardRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId:        nanoid.New(),
		Name:            "wildcard_access",
		OrganizationId:  &orgID,
	})
`)
	} else {
		buf.WriteString(`	// Create a role with wildcard method
	wildcardRole, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId: nanoid.New(),
		Name:     "wildcard_access",
	})
	_ = orgID // unused in unscoped variant
`)
	}

	buf.WriteString(`	if err != nil {
		t.Fatalf("failed to create role: %v", err)
	}

	// Restrict /me with wildcard method *
	_, err = runner.CreateRoleAction(ctx, queries.CreateRoleActionParams{
		PublicId:   nanoid.New(),
		RoleId:     wildcardRole.PublicId,
		RoutePath:  "/me",
		Method:     "*",
	})
	if err != nil {
		t.Fatalf("failed to create role_action: %v", err)
	}

	// Assign the wildcard role to the user
	_, err = runner.CreateAccountRole(ctx, queries.CreateAccountRoleParams{
		PublicId:  nanoid.New(),
		AccountId: accountPublicID,
		RoleId:    wildcardRole.PublicId,
	})
	if err != nil {
		t.Fatalf("failed to assign wildcard role: %v", err)
	}

	// GET /me should work (wildcard matches any method)
	req, _ := http.NewRequest("GET", ts.Server.URL+"/me", nil)
	req.AddCookie(&http.Cookie{Name: "session", Value: cookie})
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusForbidden {
		t.Error("wildcard method (*) should match GET, but got 403")
	}
	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected status 200, got %d", resp.StatusCode)
	}
}

`)
}

func writeTestOrgScopedRolesDoNotCrossOrgs(buf *bytes.Buffer, cfg RBACTestGenConfig) {
	buf.WriteString(`func TestRBAC_OrgScopedRolesDoNotCrossOrgs(t *testing.T) {
	ts := newRBACTestServer(t)
	ctx := context.Background()
	runner := dbrunner.NewQueryRunner(ts.Tx())

	// Create two users in different orgs
	_, _, orgAID := rbacCreateTestUser(t, ts, "orgA@test.com", "OrgA")
	cookieB, _, orgBID := rbacCreateTestUser(t, ts, "orgB@test.com", "OrgB")

	// Create an "admin" role in Org A that restricts GET /me
	adminRoleA, err := runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId:        nanoid.New(),
		Name:            "admin",
		OrganizationId:  &orgAID,
	})
	if err != nil {
		t.Fatalf("failed to create admin role in org A: %v", err)
	}

	_, err = runner.CreateRoleAction(ctx, queries.CreateRoleActionParams{
		PublicId:   nanoid.New(),
		RoleId:     adminRoleA.PublicId,
		RoutePath:  "/me",
		Method:     "GET",
	})
	if err != nil {
		t.Fatalf("failed to create role_action for org A: %v", err)
	}

	// Create an "admin" role in Org B with NO role_actions (doesn't restrict /me)
	_, err = runner.CreateRole(ctx, queries.CreateRoleParams{
		PublicId:        nanoid.New(),
		Name:            "admin",
		OrganizationId:  &orgBID,
	})
	if err != nil {
		t.Fatalf("failed to create admin role in org B: %v", err)
	}

	// User B in Org B should still have access to /me, because Org B's roles
	// don't restrict it -- even though Org A's "admin" role does.
	req, _ := http.NewRequest("GET", ts.Server.URL+"/me", nil)
	req.AddCookie(&http.Cookie{Name: "session", Value: cookieB})
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusForbidden {
		t.Error("Org B user should not be affected by Org A's role_actions, but got 403")
	}
	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected status 200, got %d", resp.StatusCode)
	}
}

`)
}
