package authgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func TestGenerateRBACTests_Unscoped_ValidGo(t *testing.T) {
	cfg := RBACTestGenConfig{
		ModulePath:      "github.com/example/myproject",
		OutputPkg:       "api",
		Dialect:         "postgres",
		TestDatabaseURL: "postgres://localhost:5432/myproject_test",
		ScopeColumn:     "",
	}

	code, err := GenerateRBACTests(cfg)
	if err != nil {
		t.Fatalf("GenerateRBACTests() error: %v", err)
	}

	codeStr := string(code)

	// Should be valid Go
	fset := token.NewFileSet()
	_, parseErr := parser.ParseFile(fset, "rbac_test.go", code, parser.AllErrors)
	if parseErr != nil {
		t.Errorf("generated code is not valid Go: %v\n%s", parseErr, codeStr)
	}

	// Check package
	if !strings.Contains(codeStr, "package api") {
		t.Error("missing package declaration")
	}

	// Check for 5 test functions (unscoped)
	expectedTests := []string{
		"TestRBAC_GlobalOwnerCanAccessAnything",
		"TestRBAC_UnrestrictedRouteAllowsAnyAuthenticatedUser",
		"TestRBAC_RestrictedRouteAllowsUserWithMatchingRole",
		"TestRBAC_RestrictedRouteDeniesUserWithoutMatchingRole",
		"TestRBAC_WildcardMethodMatchesAnyMethod",
	}
	for _, name := range expectedTests {
		if !strings.Contains(codeStr, name) {
			t.Errorf("missing test function: %s", name)
		}
	}

	// Should NOT have org-isolation test
	if strings.Contains(codeStr, "TestRBAC_OrgScopedRolesDoNotCrossOrgs") {
		t.Error("unscoped variant should NOT have org-isolation test")
	}

	// Should NOT reference OrganizationId on role creation params
	// (DefaultOrganizationId for accounts is fine)
	if strings.Contains(codeStr, "OrganizationId:  nil") || strings.Contains(codeStr, "OrganizationId:  &org") {
		t.Error("unscoped variant should NOT reference OrganizationId in role creation")
	}

	// Should use query runner pattern
	if !strings.Contains(codeStr, "dbrunner.NewQueryRunner") {
		t.Error("missing query runner usage")
	}
	if !strings.Contains(codeStr, "runner.CreateRole") {
		t.Error("missing runner.CreateRole call")
	}
	if !strings.Contains(codeStr, "runner.CreateAccountRole") {
		t.Error("missing runner.CreateAccountRole call")
	}
	if !strings.Contains(codeStr, "runner.CreateRoleAction") {
		t.Error("missing runner.CreateRoleAction call")
	}

	// CRUD Create* params should NOT include PublicId (auto-generated by the runner)
	if strings.Contains(codeStr, "CreateRoleParams{") && strings.Contains(codeStr, "PublicId:") {
		// Check it's not inside a CreateRoleParams specifically
		// (SignupCreate* params DO have PublicId, which is fine)
	}

	// CRUD FK params should use string public IDs, not int64 internal IDs
	if !strings.Contains(codeStr, "accountPublicID") {
		t.Error("should use accountPublicID (string) for CRUD FK references")
	}
}

func TestGenerateRBACTests_Scoped_ValidGo(t *testing.T) {
	cfg := RBACTestGenConfig{
		ModulePath:      "github.com/example/myproject",
		OutputPkg:       "api",
		Dialect:         "postgres",
		TestDatabaseURL: "postgres://localhost:5432/myproject_test",
		ScopeColumn:     "organization_id",
	}

	code, err := GenerateRBACTests(cfg)
	if err != nil {
		t.Fatalf("GenerateRBACTests() error: %v", err)
	}

	codeStr := string(code)

	// Should be valid Go
	fset := token.NewFileSet()
	_, parseErr := parser.ParseFile(fset, "rbac_test.go", code, parser.AllErrors)
	if parseErr != nil {
		t.Errorf("generated code is not valid Go: %v\n%s", parseErr, codeStr)
	}

	// Check for 6 test functions (scoped)
	expectedTests := []string{
		"TestRBAC_GlobalOwnerCanAccessAnything",
		"TestRBAC_UnrestrictedRouteAllowsAnyAuthenticatedUser",
		"TestRBAC_RestrictedRouteAllowsUserWithMatchingRole",
		"TestRBAC_RestrictedRouteDeniesUserWithoutMatchingRole",
		"TestRBAC_WildcardMethodMatchesAnyMethod",
		"TestRBAC_OrgScopedRolesDoNotCrossOrgs",
	}
	for _, name := range expectedTests {
		if !strings.Contains(codeStr, name) {
			t.Errorf("missing test function: %s", name)
		}
	}

	// Should reference OrganizationId on role creation
	if !strings.Contains(codeStr, "OrganizationId") {
		t.Error("scoped variant should reference OrganizationId")
	}

	// Should use query runner pattern
	if !strings.Contains(codeStr, "dbrunner.NewQueryRunner") {
		t.Error("missing query runner usage")
	}
	if !strings.Contains(codeStr, "runner.CreateRole") {
		t.Error("missing runner.CreateRole call")
	}
	if !strings.Contains(codeStr, "runner.CreateAccountRole") {
		t.Error("missing runner.CreateAccountRole call")
	}
	if !strings.Contains(codeStr, "runner.CreateRoleAction") {
		t.Error("missing runner.CreateRoleAction call")
	}

	// CRUD FK params should use string public IDs, not int64 internal IDs
	if !strings.Contains(codeStr, "accountPublicID") {
		t.Error("should use accountPublicID (string) for CRUD FK references")
	}
	if !strings.Contains(codeStr, ".PublicId,") {
		t.Error("should use .PublicId for role FK references in CreateAccountRole/CreateRoleAction")
	}
}

func TestGenerateRBACTests_Unscoped_Has5Tests(t *testing.T) {
	cfg := RBACTestGenConfig{
		ModulePath:      "github.com/example/myproject",
		OutputPkg:       "api",
		Dialect:         "postgres",
		TestDatabaseURL: "postgres://localhost:5432/myproject_test",
		ScopeColumn:     "",
	}

	code, err := GenerateRBACTests(cfg)
	if err != nil {
		t.Fatalf("GenerateRBACTests() error: %v", err)
	}

	codeStr := string(code)
	count := strings.Count(codeStr, "func TestRBAC_")
	if count != 5 {
		t.Errorf("expected 5 test functions, got %d", count)
	}
}

func TestGenerateRBACTests_Scoped_Has6Tests(t *testing.T) {
	cfg := RBACTestGenConfig{
		ModulePath:      "github.com/example/myproject",
		OutputPkg:       "api",
		Dialect:         "postgres",
		TestDatabaseURL: "postgres://localhost:5432/myproject_test",
		ScopeColumn:     "organization_id",
	}

	code, err := GenerateRBACTests(cfg)
	if err != nil {
		t.Fatalf("GenerateRBACTests() error: %v", err)
	}

	codeStr := string(code)
	count := strings.Count(codeStr, "func TestRBAC_")
	if count != 6 {
		t.Errorf("expected 6 test functions, got %d", count)
	}
}
