package llmgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func TestGeneratePersisterAdapter_CompilesAsValidGo(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "zz_generated_persister.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated code does not parse as valid Go: %v\n\nSource:\n%s", err, string(src))
	}
}

func TestGeneratePersisterAdapter_HasGeneratedHeader(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "Code generated by shipq. DO NOT EDIT.") {
		t.Error("expected generated file header")
	}
}

func TestGeneratePersisterAdapter_PackageName(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "package llmpersist") {
		t.Error("expected 'package llmpersist'")
	}
}

func TestGeneratePersisterAdapter_ImportsLLMPackage(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, `"myapp/shipq/lib/llm"`) {
		t.Error("expected import of myapp/shipq/lib/llm")
	}
}

func TestGeneratePersisterAdapter_ImportsQueriesPackage(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, `"myapp/shipq/queries"`) {
		t.Error("expected import of myapp/shipq/queries")
	}
}

func TestGeneratePersisterAdapter_ImportsContextAndTime(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, `"context"`) {
		t.Error("expected import of context")
	}
	if !strings.Contains(code, `"time"`) {
		t.Error("expected import of time")
	}
}

func TestGeneratePersisterAdapter_HasPersisterStruct(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "type Persister struct") {
		t.Error("expected Persister struct definition")
	}

	if !strings.Contains(code, "runner queries.Runner") {
		t.Error("expected runner field of type queries.Runner")
	}
}

func TestGeneratePersisterAdapter_HasNewConstructor(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "func New(runner queries.Runner) *Persister") {
		t.Error("expected New constructor function")
	}
}

func TestGeneratePersisterAdapter_HasInterfaceCheck(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "var _ llm.Persister = (*Persister)(nil)") {
		t.Error("expected compile-time interface check")
	}
}

func TestGeneratePersisterAdapter_HasInsertConversation(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "func (p *Persister) InsertConversation(ctx context.Context, params llm.InsertConversationParams) (llm.ConversationRow, error)") {
		t.Error("expected InsertConversation method")
	}

	// Should map all relevant fields
	expectedFields := []string{
		"params.PublicID",
		"params.JobID",
		"params.ChannelName",
		"params.AccountID",
		"params.Provider",
		"params.Model",
		"params.Status",
	}
	for _, field := range expectedFields {
		if !strings.Contains(code, field) {
			t.Errorf("InsertConversation: expected reference to %s", field)
		}
	}

	// Should call runner.InsertLLMConversation
	if !strings.Contains(code, "p.runner.InsertLLMConversation(") {
		t.Error("expected call to p.runner.InsertLLMConversation")
	}

	// Should return ConversationRow with ID and PublicID
	if !strings.Contains(code, "result.Id") {
		t.Error("expected result.Id in return")
	}
	if !strings.Contains(code, "result.PublicId") {
		t.Error("expected result.PublicId in return")
	}
}

func TestGeneratePersisterAdapter_InsertConversation_DefaultStartedAt(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	// Should default StartedAt to time.Now() if zero
	if !strings.Contains(code, "startedAt.IsZero()") {
		t.Error("expected zero check for StartedAt")
	}
	if !strings.Contains(code, "time.Now()") {
		t.Error("expected time.Now() fallback for StartedAt")
	}
}

func TestGeneratePersisterAdapter_HasUpdateConversation(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "func (p *Persister) UpdateConversation(ctx context.Context, params llm.UpdateConversationParams) error") {
		t.Error("expected UpdateConversation method")
	}

	// Should map relevant fields
	expectedFields := []string{
		"params.ID",
		"params.Status",
		"params.InputTokens",
		"params.OutputTokens",
		"params.ToolCallCount",
		"params.ErrorMessage",
		"params.CompletedAt",
	}
	for _, field := range expectedFields {
		if !strings.Contains(code, field) {
			t.Errorf("UpdateConversation: expected reference to %s", field)
		}
	}

	// Should call runner.UpdateLLMConversation
	if !strings.Contains(code, "p.runner.UpdateLLMConversation(") {
		t.Error("expected call to p.runner.UpdateLLMConversation")
	}
}

func TestGeneratePersisterAdapter_UpdateConversation_NullableFields(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	// CompletedAt should be converted to *string (nullable)
	if !strings.Contains(code, "var completedAt *string") {
		t.Error("expected completedAt to be *string (nullable)")
	}

	// ErrorMessage should be converted to *string (nullable)
	if !strings.Contains(code, "var errorMessage *string") {
		t.Error("expected errorMessage to be *string (nullable)")
	}
}

func TestGeneratePersisterAdapter_HasInsertMessage(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "func (p *Persister) InsertMessage(ctx context.Context, params llm.InsertMessageParams) error") {
		t.Error("expected InsertMessage method")
	}

	// Should map relevant fields
	expectedFields := []string{
		"params.PublicID",
		"params.ConversationID",
		"params.Role",
		"params.Content",
		"params.ToolName",
		"params.ToolCallID",
	}
	for _, field := range expectedFields {
		if !strings.Contains(code, field) {
			t.Errorf("InsertMessage: expected reference to %s", field)
		}
	}

	// Should call runner.InsertLLMMessage
	if !strings.Contains(code, "p.runner.InsertLLMMessage(") {
		t.Error("expected call to p.runner.InsertLLMMessage")
	}
}

func TestGeneratePersisterAdapter_InsertMessage_NullableFields(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	// ToolName should be nullable
	if !strings.Contains(code, "var toolName *string") {
		t.Error("expected toolName to be *string (nullable)")
	}

	// ToolCallID should be nullable
	if !strings.Contains(code, "var toolCallID *string") {
		t.Error("expected toolCallID to be *string (nullable)")
	}

	// Content should be nullable
	if !strings.Contains(code, "var content *string") {
		t.Error("expected content to be *string (nullable)")
	}
}

func TestGeneratePersisterAdapter_MonorepoModulePath(t *testing.T) {
	src, err := GeneratePersisterAdapter("github.com/company/monorepo/services/myservice", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, `"github.com/company/monorepo/services/myservice/shipq/lib/llm"`) {
		t.Error("expected full monorepo import path for llm package")
	}

	if !strings.Contains(code, `"github.com/company/monorepo/services/myservice/shipq/queries"`) {
		t.Error("expected full monorepo import path for queries package")
	}

	// Should still compile as valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "zz_generated_persister.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated code (monorepo) does not parse as valid Go: %v\n\nSource:\n%s", err, string(src))
	}
}

func TestGeneratePersisterAdapter_AllFourMethodsBasic(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	methods := []string{
		"InsertConversation",
		"UpdateConversation",
		"InsertMessage",
		"ListCompletedTools",
	}

	for _, method := range methods {
		if !strings.Contains(code, "func (p *Persister) "+method+"(") {
			t.Errorf("expected method %s on Persister", method)
		}
	}
}

func TestGeneratePersisterAdapter_Deterministic(t *testing.T) {
	src1, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("first GeneratePersisterAdapter failed: %v", err)
	}

	src2, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("second GeneratePersisterAdapter failed: %v", err)
	}

	if string(src1) != string(src2) {
		t.Error("expected deterministic output for same module path")
	}
}

func TestGeneratePersisterAdapter_WithAuth_HasAuthorAccountIdConversion(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", true)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	// Should declare authorAccountId as *int64
	if !strings.Contains(code, "var authorAccountId *int64") {
		t.Error("expected var authorAccountId *int64 when hasAuth is true")
	}

	// Should check AccountID != 0 before taking pointer
	if !strings.Contains(code, "if params.AccountID != 0") {
		t.Error("expected AccountID != 0 check for nullable author_account_id")
	}

	// Should assign pointer when nonzero
	if !strings.Contains(code, "authorAccountId = &params.AccountID") {
		t.Error("expected authorAccountId = &params.AccountID when AccountID is nonzero")
	}

	// Should include AuthorAccountId in insert params
	if !strings.Contains(code, "AuthorAccountId: authorAccountId,") {
		t.Error("expected AuthorAccountId field in InsertLLMConversationParams")
	}

	// Should still compile as valid Go
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "zz_generated_persister.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated code (with auth) does not parse as valid Go: %v\n\nSource:\n%s", err, string(src))
	}
}

func TestGeneratePersisterAdapter_WithoutAuth_NoAuthorAccountId(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if strings.Contains(code, "authorAccountId") {
		t.Error("expected no authorAccountId logic when hasAuth is false")
	}

	if strings.Contains(code, "AuthorAccountId") {
		t.Error("expected no AuthorAccountId field when hasAuth is false")
	}
}

func TestGeneratePersisterAdapter_WithAuth_Deterministic(t *testing.T) {
	src1, err := GeneratePersisterAdapter("myapp", true)
	if err != nil {
		t.Fatalf("first GeneratePersisterAdapter failed: %v", err)
	}

	src2, err := GeneratePersisterAdapter("myapp", true)
	if err != nil {
		t.Fatalf("second GeneratePersisterAdapter failed: %v", err)
	}

	if string(src1) != string(src2) {
		t.Error("expected deterministic output for same parameters")
	}
}

// ── ListCompletedTools adapter tests ──────────────────────────────────────────

func TestGeneratePersisterAdapter_HasListCompletedTools(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "func (p *Persister) ListCompletedTools(ctx context.Context, jobID string) ([]string, error)") {
		t.Error("expected ListCompletedTools method")
	}
}

func TestGeneratePersisterAdapter_ListCompletedTools_CallsRunner(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "p.runner.ListCompletedToolsByJob(") {
		t.Error("expected call to p.runner.ListCompletedToolsByJob")
	}
}

func TestGeneratePersisterAdapter_ListCompletedTools_PassesJobID(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "JobId: jobID") {
		t.Error("expected JobId: jobID in ListCompletedToolsByJob params")
	}
}

func TestGeneratePersisterAdapter_ListCompletedTools_HandlesNullableToolName(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "row.ToolName != nil") {
		t.Error("expected nil check for ToolName in ListCompletedTools")
	}
}

func TestGeneratePersisterAdapter_ListCompletedTools_ReturnsStringSlice(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "return names, nil") {
		t.Error("expected 'return names, nil' in ListCompletedTools")
	}
}

func TestGeneratePersisterAdapter_AllFourMethods(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	methods := []string{
		"InsertConversation",
		"UpdateConversation",
		"InsertMessage",
		"ListCompletedTools",
	}

	for _, method := range methods {
		if !strings.Contains(code, "func (p *Persister) "+method+"(") {
			t.Errorf("expected method %s on Persister", method)
		}
	}
}

func TestGeneratePersisterAdapter_ListCompletedTools_HasComment(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "ListCompletedTools returns the distinct tool names") {
		t.Error("expected descriptive comment for ListCompletedTools")
	}
}

// ── MySQL datetime format regression tests ────────────────────────────────────
// MySQL strict mode rejects RFC 3339 timestamps (the "T" separator and "Z"
// suffix). The generated code must use "2006-01-02 15:04:05".

func TestGeneratePersisterAdapter_DatetimeFormat_NoRFC3339InFormatCalls(t *testing.T) {
	for _, hasAuth := range []bool{false, true} {
		src, err := GeneratePersisterAdapter("myapp", hasAuth)
		if err != nil {
			t.Fatalf("GeneratePersisterAdapter(hasAuth=%v) failed: %v", hasAuth, err)
		}

		code := string(src)

		// .Format("2006-01-02T... is the bug pattern — an RFC 3339 literal
		// passed to time.Format. Comments mentioning the format are fine.
		if strings.Contains(code, `.Format("2006-01-02T`) {
			t.Errorf("hasAuth=%v: generated code passes RFC 3339 format to .Format(); MySQL strict mode will reject it", hasAuth)
		}
		if strings.Contains(code, `.Format("`) && strings.Contains(code, `Z07:00")`) {
			t.Errorf("hasAuth=%v: generated code passes 'Z07:00' timezone suffix to .Format(); MySQL DATETIME columns do not accept it", hasAuth)
		}
	}
}

func TestGeneratePersisterAdapter_DatetimeFormat_UsesMySQLFormat(t *testing.T) {
	for _, hasAuth := range []bool{false, true} {
		src, err := GeneratePersisterAdapter("myapp", hasAuth)
		if err != nil {
			t.Fatalf("GeneratePersisterAdapter(hasAuth=%v) failed: %v", hasAuth, err)
		}

		code := string(src)

		if !strings.Contains(code, `"2006-01-02 15:04:05"`) {
			t.Errorf("hasAuth=%v: generated code does not contain MySQL-compatible datetime format \"2006-01-02 15:04:05\"", hasAuth)
		}
	}
}

func TestGeneratePersisterAdapter_DatetimeFormat_BothMethodsUseSqlDatetimeFormat(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, "startedAt.Format(sqlDatetimeFormat)") {
		t.Error("InsertConversation: expected startedAt.Format(sqlDatetimeFormat)")
	}
	if !strings.Contains(code, "params.CompletedAt.Format(sqlDatetimeFormat)") {
		t.Error("UpdateConversation: expected params.CompletedAt.Format(sqlDatetimeFormat)")
	}
}

func TestGeneratePersisterAdapter_DatetimeFormat_ConstantDefined(t *testing.T) {
	src, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, `const sqlDatetimeFormat = "2006-01-02 15:04:05"`) {
		t.Error("expected sqlDatetimeFormat constant with MySQL-compatible format in generated code")
	}
}

func TestGeneratePersisterAdapter_DifferentAuthProducesDifferentOutput(t *testing.T) {
	src1, err := GeneratePersisterAdapter("myapp", false)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter (no auth) failed: %v", err)
	}

	src2, err := GeneratePersisterAdapter("myapp", true)
	if err != nil {
		t.Fatalf("GeneratePersisterAdapter (with auth) failed: %v", err)
	}

	if string(src1) == string(src2) {
		t.Error("expected different output for different auth settings")
	}
}
