package llmgen

import (
	"encoding/json"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/shipq/shipq/codegen/llmcompile"
)

func TestGenerateToolRegistry_SingleTool(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/weather",
		PackageName: "weather",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "get_weather",
				Description: "Get the current weather for a city",
				FuncName:    "GetWeather",
				PackagePath: "myapp/tools/weather",
				PackageName: "weather",
				InputSchema: json.RawMessage(`{"type":"object","properties":{"city":{"type":"string"}},"required":["city"],"additionalProperties":false}`),
				InputType:   "WeatherInput",
				OutputType:  "WeatherOutput",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	code := string(src)

	// Should be in the correct package.
	if !strings.Contains(code, "package weather") {
		t.Error("expected 'package weather'")
	}

	// Should have the generated header.
	if !strings.Contains(code, "Code generated by shipq. DO NOT EDIT.") {
		t.Error("expected generated file header")
	}

	// Should import the llm package.
	if !strings.Contains(code, `"myapp/shipq/lib/llm"`) {
		t.Error("expected import of myapp/shipq/lib/llm")
	}

	// Should have a schema variable.
	if !strings.Contains(code, "getWeatherSchema") {
		t.Error("expected getWeatherSchema variable")
	}

	// Should have a dispatcher function.
	if !strings.Contains(code, "dispatchGetWeather") {
		t.Error("expected dispatchGetWeather function")
	}

	// Should have a Registry function.
	if !strings.Contains(code, "func Registry()") {
		t.Error("expected Registry() function")
	}

	// Dispatcher should unmarshal into the correct type.
	if !strings.Contains(code, "var input WeatherInput") {
		t.Error("expected 'var input WeatherInput' in dispatcher")
	}

	// Dispatcher should call the user's function.
	if !strings.Contains(code, "GetWeather(ctx, &input)") {
		t.Error("expected call to GetWeather(ctx, &input)")
	}

	// Registry should reference the tool name.
	if !strings.Contains(code, `"get_weather"`) {
		t.Error("expected tool name 'get_weather' in Registry")
	}

	// Registry should reference the description.
	if !strings.Contains(code, `"Get the current weather for a city"`) {
		t.Error("expected tool description in Registry")
	}

	// Registry should reference the schema var and dispatcher.
	if !strings.Contains(code, "InputSchema: getWeatherSchema") {
		t.Error("expected InputSchema: getWeatherSchema in Registry")
	}
	if !strings.Contains(code, "Func:        dispatchGetWeather") {
		t.Error("expected Func: dispatchGetWeather in Registry")
	}
}

func TestGenerateToolRegistry_MultipleTools(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/multi",
		PackageName: "multi",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "get_weather",
				Description: "Get weather",
				FuncName:    "GetWeather",
				PackagePath: "myapp/tools/multi",
				PackageName: "multi",
				InputSchema: json.RawMessage(`{"type":"object","properties":{}}`),
				InputType:   "WeatherInput",
				OutputType:  "WeatherOutput",
			},
			{
				Name:        "search_web",
				Description: "Search the web",
				FuncName:    "SearchWeb",
				PackagePath: "myapp/tools/multi",
				PackageName: "multi",
				InputSchema: json.RawMessage(`{"type":"object","properties":{}}`),
				InputType:   "SearchInput",
				OutputType:  "SearchOutput",
			},
			{
				Name:        "send_email",
				Description: "Send an email",
				FuncName:    "SendEmail",
				PackagePath: "myapp/tools/multi",
				PackageName: "multi",
				InputSchema: json.RawMessage(`{"type":"object","properties":{}}`),
				InputType:   "EmailInput",
				OutputType:  "EmailOutput",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	code := string(src)

	// All three dispatchers should be present.
	if !strings.Contains(code, "dispatchGetWeather") {
		t.Error("expected dispatchGetWeather")
	}
	if !strings.Contains(code, "dispatchSearchWeb") {
		t.Error("expected dispatchSearchWeb")
	}
	if !strings.Contains(code, "dispatchSendEmail") {
		t.Error("expected dispatchSendEmail")
	}

	// All three schema vars.
	if !strings.Contains(code, "getWeatherSchema") {
		t.Error("expected getWeatherSchema")
	}
	if !strings.Contains(code, "searchWebSchema") {
		t.Error("expected searchWebSchema")
	}
	if !strings.Contains(code, "sendEmailSchema") {
		t.Error("expected sendEmailSchema")
	}

	// All three tool names in Registry.
	if !strings.Contains(code, `"get_weather"`) {
		t.Error("expected get_weather in Registry")
	}
	if !strings.Contains(code, `"search_web"`) {
		t.Error("expected search_web in Registry")
	}
	if !strings.Contains(code, `"send_email"`) {
		t.Error("expected send_email in Registry")
	}

	// Each tool should unmarshal to its own type.
	if !strings.Contains(code, "var input WeatherInput") {
		t.Error("expected WeatherInput in GetWeather dispatcher")
	}
	if !strings.Contains(code, "var input SearchInput") {
		t.Error("expected SearchInput in SearchWeb dispatcher")
	}
	if !strings.Contains(code, "var input EmailInput") {
		t.Error("expected EmailInput in SendEmail dispatcher")
	}
}

func TestGenerateToolRegistry_Empty(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/empty",
		PackageName: "empty",
		Tools:       []llmcompile.SerializedToolInfo{},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	code := string(src)

	// Should still have a valid package declaration.
	if !strings.Contains(code, "package empty") {
		t.Error("expected 'package empty'")
	}

	// Should have a Registry function returning an empty registry.
	if !strings.Contains(code, "func Registry()") {
		t.Error("expected Registry() function")
	}

	// Should have no dispatchers.
	if strings.Contains(code, "dispatch") && !strings.Contains(code, "// ") {
		// Only check for dispatch as a function declaration, not in comments.
		if strings.Contains(code, "func dispatch") {
			t.Error("expected no dispatcher functions for empty tools")
		}
	}
}

func TestGenerateToolRegistry_CompilesAsValidGo(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/weather",
		PackageName: "weather",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "get_weather",
				Description: "Get the current weather for a city",
				FuncName:    "GetWeather",
				PackagePath: "myapp/tools/weather",
				PackageName: "weather",
				InputSchema: json.RawMessage(`{"type":"object","properties":{"city":{"type":"string","description":"The city name"}},"required":["city"],"additionalProperties":false}`),
				InputType:   "WeatherInput",
				OutputType:  "WeatherOutput",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	// Parse as Go source — this validates syntax.
	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "zz_generated_registry.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated code does not parse as valid Go: %v\n\nSource:\n%s", err, string(src))
	}
}

func TestGenerateToolRegistry_MultipleToolsCompilesAsValidGo(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/multi",
		PackageName: "multi",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "tool_a",
				Description: "First tool",
				FuncName:    "ToolA",
				PackagePath: "myapp/tools/multi",
				PackageName: "multi",
				InputSchema: json.RawMessage(`{"type":"object","properties":{}}`),
				InputType:   "InputA",
				OutputType:  "OutputA",
			},
			{
				Name:        "tool_b",
				Description: "Second tool",
				FuncName:    "ToolB",
				PackagePath: "myapp/tools/multi",
				PackageName: "multi",
				InputSchema: json.RawMessage(`{"type":"object","properties":{}}`),
				InputType:   "InputB",
				OutputType:  "OutputB",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "zz_generated_registry.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated code does not parse as valid Go: %v\n\nSource:\n%s", err, string(src))
	}
}

func TestGenerateToolRegistry_EmptyCompilesAsValidGo(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/empty",
		PackageName: "empty",
		Tools:       []llmcompile.SerializedToolInfo{},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	fset := token.NewFileSet()
	_, err = parser.ParseFile(fset, "zz_generated_registry.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated code (empty) does not parse as valid Go: %v\n\nSource:\n%s", err, string(src))
	}
}

func TestGenerateToolRegistry_MonorepoModulePath(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "github.com/company/monorepo/services/myservice/tools/weather",
		PackageName: "weather",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "get_weather",
				Description: "Get weather",
				FuncName:    "GetWeather",
				PackagePath: "github.com/company/monorepo/services/myservice/tools/weather",
				PackageName: "weather",
				InputSchema: json.RawMessage(`{"type":"object"}`),
				InputType:   "WeatherInput",
				OutputType:  "WeatherOutput",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "github.com/company/monorepo/services/myservice")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	code := string(src)

	if !strings.Contains(code, `"github.com/company/monorepo/services/myservice/shipq/lib/llm"`) {
		t.Error("expected full monorepo import path for llm package")
	}
}

func TestGenerateToolRegistry_SchemaEmbeddedAsVar(t *testing.T) {
	schema := `{"type":"object","properties":{"city":{"type":"string"},"country":{"type":"string"}},"required":["city","country"],"additionalProperties":false}`
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/weather",
		PackageName: "weather",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "get_weather",
				Description: "Get weather",
				FuncName:    "GetWeather",
				PackagePath: "myapp/tools/weather",
				PackageName: "weather",
				InputSchema: json.RawMessage(schema),
				InputType:   "WeatherInput",
				OutputType:  "WeatherOutput",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	code := string(src)

	// The schema should be embedded as a json.RawMessage variable.
	if !strings.Contains(code, "json.RawMessage(") || !strings.Contains(code, "getWeatherSchema") {
		t.Error("expected schema to be embedded as a json.RawMessage variable")
	}

	// The schema content should appear in the source.
	if !strings.Contains(code, `"city"`) {
		t.Error("expected schema to contain city property")
	}
	if !strings.Contains(code, `"country"`) {
		t.Error("expected schema to contain country property")
	}
}

func TestGenerateToolRegistry_DispatcherUnmarshalsMarshal(t *testing.T) {
	pkg := llmcompile.SerializedToolPackage{
		PackagePath: "myapp/tools/calc",
		PackageName: "calc",
		Tools: []llmcompile.SerializedToolInfo{
			{
				Name:        "add",
				Description: "Add two numbers",
				FuncName:    "Add",
				PackagePath: "myapp/tools/calc",
				PackageName: "calc",
				InputSchema: json.RawMessage(`{"type":"object"}`),
				InputType:   "AddInput",
				OutputType:  "AddOutput",
			},
		},
	}

	src, err := GenerateToolRegistry(pkg, "myapp")
	if err != nil {
		t.Fatalf("GenerateToolRegistry failed: %v", err)
	}

	code := string(src)

	// Dispatcher should unmarshal input.
	if !strings.Contains(code, "json.Unmarshal(argsJSON, &input)") {
		t.Error("expected json.Unmarshal call in dispatcher")
	}

	// Dispatcher should marshal output.
	if !strings.Contains(code, "json.Marshal(output)") {
		t.Error("expected json.Marshal call in dispatcher")
	}

	// Dispatcher should check for errors from the user function.
	if !strings.Contains(code, "if err != nil") {
		t.Error("expected error check in dispatcher")
	}
}

func TestToLowerCamel(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"GetWeather", "getWeather"},
		{"SearchWeb", "searchWeb"},
		{"X", "x"},
		{"ABC", "aBC"},
		{"", ""},
		{"otherpkg.SomeFunc", "someFunc"},
		{"pkg.X", "x"},
	}

	for _, tt := range tests {
		got := toLowerCamel(tt.input)
		if got != tt.want {
			t.Errorf("toLowerCamel(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
