// Code generated by shipq.
package db

import (
	"database/sql"
	"fmt"
	"net/url"
	"os"
	"sync"

	_ "github.com/go-sql-driver/mysql"
)

// Dialect is the database dialect configured for this project.
const Dialect = "mysql"

// localhostURL is the fallback URL from shipq.ini at code generation time.
// Used for local development when DATABASE_URL is not set.
const localhostURL = "mysql://root@localhost:3306/shipq"

var (
	db     *sql.DB
	dbOnce sync.Once
	dbErr  error
)

// DB returns the database connection pool.
// On first call, it initializes the connection using DATABASE_URL env var,
// falling back to the compile-time localhost URL from shipq.ini.
func DB() (*sql.DB, error) {
	dbOnce.Do(func() {
		dbURL := os.Getenv("DATABASE_URL")
		if dbURL == "" {
			fmt.Fprintln(os.Stderr, "shipq: DATABASE_URL not set, using localhost fallback")
			dbURL = localhostURL
		}

		if dbURL == "" {
			dbErr = fmt.Errorf("shipq: no database URL available (set DATABASE_URL or configure db.database_url in shipq.ini)")
			return
		}

		// Convert URL to driver-specific DSN if needed
		dsn, err := urlToDSN(dbURL)
		if err != nil {
			dbErr = fmt.Errorf("shipq: failed to parse database URL: %w", err)
			return
		}

		db, dbErr = sql.Open("mysql", dsn)
		if dbErr != nil {
			dbErr = fmt.Errorf("shipq: failed to open database: %w", dbErr)
			return
		}

		// Verify connection
		if err := db.Ping(); err != nil {
			dbErr = fmt.Errorf("shipq: failed to ping database: %w", err)
			return
		}
	})

	return db, dbErr
}

// MustDB returns the database connection pool or panics on error.
func MustDB() *sql.DB {
	db, err := DB()
	if err != nil {
		panic(err)
	}
	return db
}

// urlToDSN converts a mysql:// URL to a go-sql-driver/mysql DSN.
// Format: user:password@tcp(host:port)/dbname?params
//
// Query parameters from the input URL are preserved. If not explicitly set,
// parseTime=true and loc=Local are added as defaults — parseTime so the driver
// scans DATETIME columns into time.Time, and loc so timestamps use the
// server's local timezone rather than UTC.
func urlToDSN(dbURL string) (string, error) {
	u, err := url.Parse(dbURL)
	if err != nil {
		return "", fmt.Errorf("invalid MySQL URL: %w", err)
	}

	if u.Scheme != "mysql" {
		return "", fmt.Errorf("invalid MySQL URL: unexpected scheme %q", u.Scheme)
	}

	user := u.User.String()
	host := u.Host

	dbName := ""
	if len(u.Path) > 1 {
		dbName = u.Path[1:]
	}

	params := u.Query()
	if params.Get("parseTime") == "" {
		params.Set("parseTime", "true")
	}
	if params.Get("loc") == "" {
		params.Set("loc", "Local")
	}

	return fmt.Sprintf("%s@tcp(%s)/%s?%s", user, host, dbName, params.Encode()), nil
}
