package httptsgen

import (
	"strings"
	"testing"

	"github.com/shipq/shipq/codegen"
)

// ─── GenerateReactHooks tests ───

func TestGenerateReactHooks_EmptyHandlers(t *testing.T) {
	result, err := GenerateReactHooks(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(result), "No handlers defined") {
		t.Errorf("expected 'No handlers defined' message, got: %s", string(result))
	}
}

func TestGenerateReactHooks_Header(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)
	if !strings.HasPrefix(output, "// Code generated by shipq. DO NOT EDIT.\n") {
		t.Error("output should start with generated file header")
	}
}

func TestGenerateReactHooks_TanStackImports(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		`from "@tanstack/react-query"`,
		"useQuery,",
		"useMutation,",
		"useQueryClient,",
		"type UseQueryOptions,",
		"type UseMutationOptions,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("TanStack imports should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_BaseClientImports(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		`from "../shipq-api"`,
		"type CreatePostRequest,",
		"type CreatePostResponse,",
		"type GetPostResponse,",
		"type ListPostsResponse,",
		"type UpdatePostRequest,",
		"type UpdatePostResponse,",
		"createPost,",
		"getPost,",
		"listPosts,",
		"updatePost,",
		"softDeletePost,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("base client imports should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_QueryKeys(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export const postsKeys = {",
		`all: ["posts"] as const,`,
		`getPost: (id: string) => [...postsKeys.all, "getPost", id] as const,`,
		`listPosts: () => [...postsKeys.all, "listPosts"] as const,`,
		`createPost: () => [...postsKeys.all, "createPost"] as const,`,
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("query keys should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_UseGetPostHook(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useGetPost(",
		"id: string,",
		"options?: Partial<UseQueryOptions<GetPostResponse>>",
		"queryKey: postsKeys.getPost(id),",
		"queryFn: () => getPost(id),",
		"...options,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useGetPost hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_UseListPostsHook(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useListPosts(",
		"params?: { cursor?: string; limit?: number }",
		"options?: Partial<UseQueryOptions<ListPostsResponse>>",
		"[...postsKeys.listPosts(), params] as const,",
		"queryFn: () => listPosts(params),",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useListPosts hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_UseCreatePostHook(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useCreatePost(",
		"options?: UseMutationOptions<CreatePostResponse, Error, CreatePostRequest>",
		"const queryClient = useQueryClient();",
		"mutationFn: (req: CreatePostRequest) => createPost(req),",
		"onSuccess: () => {",
		"queryClient.invalidateQueries({ queryKey: postsKeys.all });",
		"...options,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useCreatePost hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_UseUpdatePostHook(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useUpdatePost(",
		"options?: UseMutationOptions<UpdatePostResponse, Error, { id: string; data: UpdatePostRequest }>",
		"const queryClient = useQueryClient();",
		"mutationFn: ({ id, data }: { id: string; data: UpdatePostRequest }) => updatePost(id, data),",
		"onSuccess: () => {",
		"queryClient.invalidateQueries({ queryKey: postsKeys.all });",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useUpdatePost hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_UseSoftDeletePostHook(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useSoftDeletePost(",
		"options?: UseMutationOptions<void, Error, string>",
		"const queryClient = useQueryClient();",
		"mutationFn: (id: string) => softDeletePost(id),",
		"onSuccess: () => {",
		"queryClient.invalidateQueries({ queryKey: postsKeys.all });",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useSoftDeletePost hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_CRUDAutoInvalidation(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Count occurrences of queryClient.invalidateQueries — should appear for
	// Create, Update, and SoftDelete (3 CRUD mutations)
	count := strings.Count(output, "queryClient.invalidateQueries({ queryKey: postsKeys.all });")
	if count != 3 {
		t.Errorf("expected 3 auto-invalidation calls (Create, Update, Delete), got %d", count)
	}
}

func TestGenerateReactHooks_CustomMutation_NoAutoInvalidation(t *testing.T) {
	handlers := append(makePostsHandlers(), makeCustomHandler())
	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "export function usePublishPost(") {
		t.Error("should generate usePublishPost hook")
	}

	// Find the usePublishPost hook and check it does NOT have auto-invalidation
	lines := strings.Split(output, "\n")
	inPublishHook := false
	braceDepth := 0
	hasInvalidation := false
	for _, line := range lines {
		if strings.Contains(line, "export function usePublishPost(") {
			inPublishHook = true
			braceDepth = 0
			continue
		}
		if inPublishHook {
			braceDepth += strings.Count(line, "{") - strings.Count(line, "}")
			if strings.Contains(line, "queryClient.invalidateQueries") {
				hasInvalidation = true
			}
			if braceDepth <= 0 && strings.TrimSpace(line) == "}" {
				break
			}
		}
	}
	if hasInvalidation {
		t.Error("custom mutation usePublishPost should NOT have auto-invalidation")
	}

	// Also check that it does NOT use useQueryClient
	inPublishHook = false
	hasQueryClient := false
	for _, line := range lines {
		if strings.Contains(line, "export function usePublishPost(") {
			inPublishHook = true
			braceDepth = 0
			continue
		}
		if inPublishHook {
			braceDepth += strings.Count(line, "{") - strings.Count(line, "}")
			if strings.Contains(line, "useQueryClient()") {
				hasQueryClient = true
			}
			if braceDepth <= 0 && strings.TrimSpace(line) == "}" {
				break
			}
		}
	}
	if hasQueryClient {
		t.Error("custom mutation usePublishPost should NOT use useQueryClient")
	}
}

func TestGenerateReactHooks_CustomGetHook(t *testing.T) {
	handlers := append(makePostsHandlers(), makeCustomGetHandler())
	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useListPostComments(",
		"id: string,",
		"queryKey: postsKeys.listPostComments(id),",
		"queryFn: () => listPostComments(id),",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useListPostComments hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_CustomGetQueryKey(t *testing.T) {
	handlers := append(makePostsHandlers(), makeCustomGetHandler())
	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, `listPostComments: (id: string) => [...postsKeys.all, "listPostComments", id] as const,`) {
		t.Error("should generate key factory for custom GET with path params")
	}
}

func TestGenerateReactHooks_AdminListHook(t *testing.T) {
	result, err := GenerateReactHooks(makeAdminHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useAdminListPosts(",
		"params?: { cursor?: string; limit?: number }",
		"[...postsKeys.adminListPosts(), params] as const,",
		"queryFn: () => adminListPosts(params),",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useAdminListPosts hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_UndeleteHook(t *testing.T) {
	result, err := GenerateReactHooks(makeAdminHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"export function useUndeletePost(",
		"mutationFn: (id: string) => undeletePost(id),",
		"queryClient.invalidateQueries({ queryKey: postsKeys.all });",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("useUndeletePost hook should contain %q", s)
		}
	}
}

func TestGenerateReactHooks_MultiplePackages(t *testing.T) {
	handlers := append(makePostsHandlers(), codegen.SerializedHandlerInfo{
		Method:      "GET",
		Path:        "/comments",
		FuncName:    "ListComments",
		PackagePath: "myapp/api/comments",
		Response: &codegen.SerializedStructInfo{
			Name: "ListCommentsResponse",
			Fields: []codegen.SerializedFieldInfo{
				{Name: "Items", Type: "[]Comment", JSONName: "items", Required: true},
			},
		},
	})

	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "export const commentsKeys = {") {
		t.Error("should generate commentsKeys object")
	}
	if !strings.Contains(output, "export const postsKeys = {") {
		t.Error("should generate postsKeys object")
	}
	if !strings.Contains(output, `all: ["comments"] as const,`) {
		t.Error("commentsKeys should have correct all key")
	}
	if !strings.Contains(output, `all: ["posts"] as const,`) {
		t.Error("postsKeys should have correct all key")
	}
	if !strings.Contains(output, "export function useListComments(") {
		t.Error("should generate useListComments hook")
	}
}

func TestGenerateReactHooks_QueryHookUsesUseQuery(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// GET hooks should use useQuery, not useMutation
	if !strings.Contains(output, "return useQuery({") {
		t.Error("GET hooks should use useQuery")
	}
}

func TestGenerateReactHooks_MutationHookUsesUseMutation(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "return useMutation({") {
		t.Error("non-GET hooks should use useMutation")
	}
}

func TestGenerateReactHooks_OptionsSpread(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Every hook should spread options at the end
	hooksCount := strings.Count(output, "export function use")
	optionsCount := strings.Count(output, "...options,")
	if optionsCount < hooksCount {
		t.Errorf("expected at least %d ...options spreads, got %d", hooksCount, optionsCount)
	}
}

func TestGenerateReactHooks_HookNaming(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	expectedHooks := []string{
		"export function useCreatePost(",
		"export function useGetPost(",
		"export function useListPosts(",
		"export function useUpdatePost(",
		"export function useSoftDeletePost(",
	}
	for _, h := range expectedHooks {
		if !strings.Contains(output, h) {
			t.Errorf("should contain hook %q", h)
		}
	}
}

func TestGenerateReactHooks_VoidReturnForDelete(t *testing.T) {
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// SoftDeletePost has no response, so the mutation type should be void
	if !strings.Contains(output, "UseMutationOptions<void, Error, string>") {
		t.Error("softDeletePost mutation should have void return type")
	}
}

func TestGenerateReactHooks_MutationWithPathParamsAndBody(t *testing.T) {
	// updatePost has both path params (id) and body (title, body)
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// The variable type should combine path params and body
	if !strings.Contains(output, "{ id: string; data: UpdatePostRequest }") {
		t.Error("updatePost mutation should have combined path params + body variable type")
	}
}

func TestGenerateReactHooks_MutationWithOnlyPathParams(t *testing.T) {
	// softDeletePost has only path params (id), no body
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Single path param should be typed as string, not wrapped in object
	if !strings.Contains(output, "UseMutationOptions<void, Error, string>") {
		t.Error("softDeletePost with single path param should use string type")
	}
}

func TestGenerateReactHooks_MutationWithOnlyBody(t *testing.T) {
	// createPost has body but no path params
	result, err := GenerateReactHooks(makePostsHandlers())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "UseMutationOptions<CreatePostResponse, Error, CreatePostRequest>") {
		t.Error("createPost mutation should use request type directly for variables")
	}
}

func TestGenerateReactHooks_CustomMutationWithPathParams(t *testing.T) {
	// PublishPost has path param (id) and the request only has path param fields
	handlers := []codegen.SerializedHandlerInfo{makeCustomHandler()}
	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "export function usePublishPost(") {
		t.Error("should generate usePublishPost hook")
	}
	// Since it only has path params (id field is a path param), it should be a simple string
	if !strings.Contains(output, "mutationFn: (id: string) => publishPost(id),") {
		t.Error("publishPost mutation should destructure path param")
	}
}

func TestGenerateReactHooks_MultiplePathParams(t *testing.T) {
	handlers := []codegen.SerializedHandlerInfo{
		{
			Method:      "DELETE",
			Path:        "/orgs/:org_id/posts/:id",
			FuncName:    "DeleteOrgPost",
			PackagePath: "myapp/api/posts",
			PathParams: []codegen.SerializedPathParam{
				{Name: "org_id", Position: 0},
				{Name: "id", Position: 1},
			},
		},
	}

	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Multiple path params should be wrapped in an object
	if !strings.Contains(output, "{ org_id: string; id: string }") {
		t.Error("multiple path params should be wrapped in an object type")
	}
}

func TestGenerateReactHooks_GetWithNoResponse(t *testing.T) {
	handlers := []codegen.SerializedHandlerInfo{
		{
			Method:      "GET",
			Path:        "/health",
			FuncName:    "HealthCheck",
			PackagePath: "myapp/api/health",
		},
	}

	result, err := GenerateReactHooks(handlers)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "export function useHealthCheck(") {
		t.Error("should generate useHealthCheck hook")
	}
	if !strings.Contains(output, "UseQueryOptions<void>") {
		t.Error("hook with no response should use void query type")
	}
}
