// Code generated by shipq. DO NOT EDIT.

import {
  useQuery,
  useMutation,
  useQueryClient,
  type UseQueryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import {
  type CreateCommentRequest,
  type CreateCommentResponse,
  type ListCommentsResponse,
  type AdminListPostsResponse,
  type CreatePostRequest,
  type CreatePostResponse,
  type GetPostResponse,
  type ListPostsResponse,
  type PublishPostResponse,
  type UpdatePostRequest,
  type UpdatePostResponse,
  createComment,
  listComments,
  softDeleteComment,
  adminListPosts,
  createPost,
  getPost,
  listPosts,
  publishPost,
  softDeletePost,
  updatePost,
} from "../shipq-api";

// ─── Query Keys: comments ───

export const commentsKeys = {
  all: ["comments"] as const,
  createComment: () => [...commentsKeys.all, "createComment"] as const,
  listComments: () => [...commentsKeys.all, "listComments"] as const,
  softDeleteComment: (id: string) => [...commentsKeys.all, "softDeleteComment", id] as const,
};

export function useCreateComment(
  options?: UseMutationOptions<CreateCommentResponse, Error, CreateCommentRequest>,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (req: CreateCommentRequest) => createComment(req),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: commentsKeys.all });
    },
    ...options,
  });
}

export function useListComments(
  params?: { cursor?: string; limit?: number },
  options?: Partial<UseQueryOptions<ListCommentsResponse>>,
) {
  return useQuery({
    queryKey: [...commentsKeys.listComments(), params] as const,
    queryFn: () => listComments(params),
    ...options,
  });
}

export function useSoftDeleteComment(
  options?: UseMutationOptions<void, Error, string>,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => softDeleteComment(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: commentsKeys.all });
    },
    ...options,
  });
}

// ─── Query Keys: posts ───

export const postsKeys = {
  all: ["posts"] as const,
  adminListPosts: () => [...postsKeys.all, "adminListPosts"] as const,
  createPost: () => [...postsKeys.all, "createPost"] as const,
  getPost: (id: string) => [...postsKeys.all, "getPost", id] as const,
  listPosts: () => [...postsKeys.all, "listPosts"] as const,
  publishPost: (id: string) => [...postsKeys.all, "publishPost", id] as const,
  softDeletePost: (id: string) => [...postsKeys.all, "softDeletePost", id] as const,
  updatePost: (id: string) => [...postsKeys.all, "updatePost", id] as const,
};

export function useAdminListPosts(
  params?: { cursor?: string; limit?: number },
  options?: Partial<UseQueryOptions<AdminListPostsResponse>>,
) {
  return useQuery({
    queryKey: [...postsKeys.adminListPosts(), params] as const,
    queryFn: () => adminListPosts(params),
    ...options,
  });
}

export function useCreatePost(
  options?: UseMutationOptions<CreatePostResponse, Error, CreatePostRequest>,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (req: CreatePostRequest) => createPost(req),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: postsKeys.all });
    },
    ...options,
  });
}

export function useGetPost(
  id: string,
  options?: Partial<UseQueryOptions<GetPostResponse>>,
) {
  return useQuery({
    queryKey: postsKeys.getPost(id),
    queryFn: () => getPost(id),
    ...options,
  });
}

export function useListPosts(
  params?: { cursor?: string; limit?: number },
  options?: Partial<UseQueryOptions<ListPostsResponse>>,
) {
  return useQuery({
    queryKey: [...postsKeys.listPosts(), params] as const,
    queryFn: () => listPosts(params),
    ...options,
  });
}

export function usePublishPost(
  options?: UseMutationOptions<PublishPostResponse, Error, string>,
) {
  return useMutation({
    mutationFn: (id: string) => publishPost(id),
    ...options,
  });
}

export function useSoftDeletePost(
  options?: UseMutationOptions<void, Error, string>,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => softDeletePost(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: postsKeys.all });
    },
    ...options,
  });
}

export function useUpdatePost(
  options?: UseMutationOptions<UpdatePostResponse, Error, { id: string; data: UpdatePostRequest }>,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdatePostRequest }) => updatePost(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: postsKeys.all });
    },
    ...options,
  });
}
