// Code generated by shipq. DO NOT EDIT.

// ─── Configuration ───

export interface ApiConfig {
  baseURL: string;
  /** Called on every request. Return headers to merge (e.g., Authorization). */
  getHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  /** Called when a request returns 401. */
  onUnauthorized?: () => void;
}

let _config: ApiConfig | null = null;

export function configureApi(cfg: ApiConfig): void {
  _config = cfg;
}

function getConfig(): ApiConfig {
  if (!_config) throw new Error("shipq API not configured — call configureApi() first");
  return _config;
}

// ─── Query string helper ───

function buildQuery(params?: Record<string, unknown>): string {
  if (!params) return "";
  const parts: string[] = [];
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null) {
      parts.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`);
    }
  }
  return parts.length > 0 ? `?${parts.join("&")}` : "";
}

// ─── Shared fetch wrapper ───

async function request<T>(
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const cfg = getConfig();
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (cfg.getHeaders) {
    Object.assign(headers, await cfg.getHeaders());
  }
  const res = await fetch(`${cfg.baseURL}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
    credentials: "include",
  });
  if (res.status === 401 && cfg.onUnauthorized) {
    cfg.onUnauthorized();
  }
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new ApiError(res.status, text);
  }
  if (res.status === 204) return undefined as T;
  return res.json();
}

export class ApiError extends Error {
  constructor(public status: number, public body: string) {
    super(`API error ${status}: ${body}`);
    this.name = "ApiError";
  }
}

// ─── comments ───

export interface CreateCommentRequest {
  post_id: string;
  body: string;
}

export interface CreateCommentResponse {
  id: string;
  post_id: string;
  body: string;
  created_at: string;
}

export interface ListCommentsParams {
  cursor?: string;
  limit?: number;
}

export interface ListCommentsResponse {
  items: any[];
  next_cursor?: string;
}

/** POST /comments */
export async function createComment(req: CreateCommentRequest): Promise<CreateCommentResponse> {
  return request<CreateCommentResponse>("POST", `/comments`, req);
}

/** GET /comments */
export async function listComments(params?: ListCommentsParams): Promise<ListCommentsResponse> {
  const query = buildQuery(params as Record<string, unknown>);
  return request<ListCommentsResponse>("GET", `/comments${query}`);
}

/** DELETE /comments/:id */
export async function softDeleteComment(id: string): Promise<void> {
  return request<void>("DELETE", `/comments/${encodeURIComponent(id)}`);
}

// ─── posts ───

export interface AdminListPostsParams {
  cursor?: string;
  limit?: number;
}

export interface AdminListPostsResponse {
  items: any[];
  next_cursor?: string;
}

export interface CreatePostRequest {
  title: string;
  body: string;
  tags?: string[];
}

export interface CreatePostResponse {
  id: string;
  title: string;
  body: string;
  tags?: string[];
  created_at: string;
}

export interface GetPostResponse {
  id: string;
  title: string;
  body: string;
  tags?: string[];
  created_at: string;
}

export interface ListPostsParams {
  cursor?: string;
  limit?: number;
}

export interface ListPostsResponse {
  items: any[];
  next_cursor?: string;
}

export interface PublishPostResponse {
  id: string;
  published_at: string;
}

export interface UpdatePostRequest {
  title?: string;
  body?: string;
}

export interface UpdatePostResponse {
  id: string;
  title: string;
  body: string;
}

/** GET /admin/posts */
export async function adminListPosts(params?: AdminListPostsParams): Promise<AdminListPostsResponse> {
  const query = buildQuery(params as Record<string, unknown>);
  return request<AdminListPostsResponse>("GET", `/admin/posts${query}`);
}

/** POST /posts */
export async function createPost(req: CreatePostRequest): Promise<CreatePostResponse> {
  return request<CreatePostResponse>("POST", `/posts`, req);
}

/** GET /posts/:id */
export async function getPost(id: string): Promise<GetPostResponse> {
  return request<GetPostResponse>("GET", `/posts/${encodeURIComponent(id)}`);
}

/** GET /posts */
export async function listPosts(params?: ListPostsParams): Promise<ListPostsResponse> {
  const query = buildQuery(params as Record<string, unknown>);
  return request<ListPostsResponse>("GET", `/posts${query}`);
}

/** POST /posts/:id/publish */
export async function publishPost(id: string): Promise<PublishPostResponse> {
  return request<PublishPostResponse>("POST", `/posts/${encodeURIComponent(id)}/publish`);
}

/** DELETE /posts/:id */
export async function softDeletePost(id: string): Promise<void> {
  return request<void>("DELETE", `/posts/${encodeURIComponent(id)}`);
}

/** PATCH /posts/:id */
export async function updatePost(id: string, req: UpdatePostRequest): Promise<UpdatePostResponse> {
  return request<UpdatePostResponse>("PATCH", `/posts/${encodeURIComponent(id)}`, req);
}
