package files

import (
	"bytes"
	"fmt"
)

// GenerateFileQueryDefs generates querydefs/managed_files/queries.go
func GenerateFileQueryDefs(modulePath string) []byte {
	var buf bytes.Buffer

	schemaPkg := modulePath + "/shipq/db/schema"
	queryPkg := modulePath + "/shipq/lib/db/portsql/query"

	buf.WriteString(generatedFileHeader)
	buf.WriteString("package managed_files\n\n")
	buf.WriteString("import (\n")
	buf.WriteString(fmt.Sprintf("\t%q\n", schemaPkg))
	buf.WriteString(fmt.Sprintf("\t%q\n", queryPkg))
	buf.WriteString(")\n\n")

	buf.WriteString("func init() {\n")

	// FilesCreateManagedFile: INSERT into managed_files
	buf.WriteString("\tquery.MustDefineOne(\"FilesCreateManagedFile\",\n")
	buf.WriteString("\t\tquery.InsertInto(schema.ManagedFiles).\n")
	buf.WriteString("\t\t\tColumns(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.PublicId(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.FileKey(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.OriginalName(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.ContentType(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.SizeBytes(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Status(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Visibility(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.S3UploadId(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.AuthorAccountId(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tValues(\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"publicId\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"fileKey\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"originalName\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"contentType\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[int64](\"sizeBytes\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"status\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"visibility\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"s3UploadId\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[int64](\"authorAccountId\"),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tReturning(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Id(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.PublicId(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesFindByPublicID: SELECT by public_id (not soft-deleted)
	buf.WriteString("\tquery.MustDefineOne(\"FilesFindByPublicID\",\n")
	buf.WriteString("\t\tquery.From(schema.ManagedFiles).\n")
	buf.WriteString("\t\t\tJoin(schema.Accounts).On(schema.ManagedFiles.AuthorAccountId().Eq(schema.Accounts.Id())).\n")
	buf.WriteString("\t\t\tSelect(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Id(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.PublicId(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.FileKey(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.OriginalName(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.ContentType(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.SizeBytes(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Status(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Visibility(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.S3UploadId(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.AuthorAccountId(),\n")
	buf.WriteString("\t\t\t\tschema.Accounts.DefaultOrganizationId(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.PublicId().Eq(query.Param[string](\"publicId\")),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesUpdateStatus: UPDATE status by public_id
	buf.WriteString("\tquery.MustDefineExec(\"FilesUpdateStatus\",\n")
	buf.WriteString("\t\tquery.Update(schema.ManagedFiles).\n")
	buf.WriteString("\t\t\tSet(schema.ManagedFiles.Status(), query.Param[string](\"status\")).\n")
	buf.WriteString("\t\t\tWhere(schema.ManagedFiles.PublicId().Eq(query.Param[string](\"publicId\"))).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesUpdateVisibility: UPDATE visibility by public_id
	buf.WriteString("\tquery.MustDefineExec(\"FilesUpdateVisibility\",\n")
	buf.WriteString("\t\tquery.Update(schema.ManagedFiles).\n")
	buf.WriteString("\t\t\tSet(schema.ManagedFiles.Visibility(), query.Param[string](\"visibility\")).\n")
	buf.WriteString("\t\t\tWhere(schema.ManagedFiles.PublicId().Eq(query.Param[string](\"publicId\"))).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesSoftDelete: SET deleted_at
	buf.WriteString("\tquery.MustDefineExec(\"FilesSoftDelete\",\n")
	buf.WriteString("\t\tquery.Update(schema.ManagedFiles).\n")
	buf.WriteString("\t\t\tSet(schema.ManagedFiles.DeletedAt(), query.Now()).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.PublicId().Eq(query.Param[string](\"publicId\")),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesCheckAccess: Check if account has access to a file
	buf.WriteString("\tquery.MustDefineOne(\"FilesCheckAccess\",\n")
	buf.WriteString("\t\tquery.From(schema.FileAccess).\n")
	buf.WriteString("\t\t\tSelectExprAs(query.Literal(1), \"has_access\").\n")
	buf.WriteString("\t\t\tSelect(schema.FileAccess.Role()).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.ManagedFileId().Eq(query.Param[int64](\"managedFileId\")),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.AccountId().Eq(query.Param[int64](\"accountId\")),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesGrantAccess: INSERT into file_access
	buf.WriteString("\tquery.MustDefineExec(\"FilesGrantAccess\",\n")
	buf.WriteString("\t\tquery.InsertInto(schema.FileAccess).\n")
	buf.WriteString("\t\t\tColumns(\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.PublicId(),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.ManagedFileId(),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.AccountId(),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.Role(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tValues(\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"publicId\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[int64](\"managedFileId\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[int64](\"accountId\"),\n")
	buf.WriteString("\t\t\t\tquery.Param[string](\"role\"),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesRevokeAccess: soft-delete from file_access
	buf.WriteString("\tquery.MustDefineExec(\"FilesRevokeAccess\",\n")
	buf.WriteString("\t\tquery.Update(schema.FileAccess).\n")
	buf.WriteString("\t\t\tSet(schema.FileAccess.DeletedAt(), query.Now()).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.ManagedFileId().Eq(query.Param[int64](\"managedFileId\")),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.AccountId().Eq(query.Param[int64](\"accountId\")),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesListAccess: list all access entries for a file, joining accounts for public_id
	buf.WriteString("\tquery.MustDefineMany(\"FilesListAccess\",\n")
	buf.WriteString("\t\tquery.From(schema.FileAccess).\n")
	buf.WriteString("\t\t\tJoin(schema.Accounts).On(schema.FileAccess.AccountId().Eq(schema.Accounts.Id())).\n")
	buf.WriteString("\t\t\tSelect(\n")
	buf.WriteString("\t\t\t\tschema.Accounts.PublicId(),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.Role(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.ManagedFileId().Eq(query.Param[int64](\"managedFileId\")),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesListVisible: list files the user can see
	// This is a complex query: own files + shared files + org-visible files + public files
	// We use a UNION-like approach via OR conditions
	buf.WriteString("\tquery.MustDefineMany(\"FilesListVisible\",\n")
	buf.WriteString("\t\tquery.From(schema.ManagedFiles).\n")
	buf.WriteString("\t\t\tLeftJoin(schema.FileAccess).On(query.And(\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.ManagedFileId().Eq(schema.ManagedFiles.Id()),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.AccountId().Eq(query.Param[int64](\"accountId\")),\n")
	buf.WriteString("\t\t\t\tschema.FileAccess.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tLeftJoin(schema.Accounts).On(schema.ManagedFiles.AuthorAccountId().Eq(schema.Accounts.Id())).\n")
	buf.WriteString("\t\t\tSelect(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.PublicId(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.OriginalName(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.ContentType(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.SizeBytes(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Status(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Visibility(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.CreatedAt(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t\tschema.ManagedFiles.Status().Eq(query.Literal(\"uploaded\")),\n")
	buf.WriteString("\t\t\t\tquery.Or(\n")
	buf.WriteString("\t\t\t\t\t// Own files\n")
	buf.WriteString("\t\t\t\t\tschema.ManagedFiles.AuthorAccountId().Eq(query.Param[int64](\"accountId\")),\n")
	buf.WriteString("\t\t\t\t\t// Shared with me\n")
	buf.WriteString("\t\t\t\t\tschema.FileAccess.Id().IsNotNull(),\n")
	buf.WriteString("\t\t\t\t\t// Organization visibility (same org)\n")
	buf.WriteString("\t\t\t\t\tquery.And(\n")
	buf.WriteString("\t\t\t\t\t\tschema.ManagedFiles.Visibility().Eq(query.Literal(\"organization\")),\n")
	buf.WriteString("\t\t\t\t\t\tschema.Accounts.DefaultOrganizationId().Eq(query.Param[int64](\"organizationId\")),\n")
	buf.WriteString("\t\t\t\t\t),\n")
	buf.WriteString("\t\t\t\t\t// Public files\n")
	buf.WriteString("\t\t\t\t\tschema.ManagedFiles.Visibility().Eq(query.Literal(\"public\")),\n")
	buf.WriteString("\t\t\t\t\t// Anonymous files\n")
	buf.WriteString("\t\t\t\t\tschema.ManagedFiles.Visibility().Eq(query.Literal(\"anonymous\")),\n")
	buf.WriteString("\t\t\t\t),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tOrderBy(schema.ManagedFiles.CreatedAt().Desc()).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	// FilesFindAccountByPublicID: find account by public_id
	buf.WriteString("\tquery.MustDefineOne(\"FilesFindAccountByPublicID\",\n")
	buf.WriteString("\t\tquery.From(schema.Accounts).\n")
	buf.WriteString("\t\t\tSelect(\n")
	buf.WriteString("\t\t\t\tschema.Accounts.Id(),\n")
	buf.WriteString("\t\t\t\tschema.Accounts.PublicId(),\n")
	buf.WriteString("\t\t\t).\n")
	buf.WriteString("\t\t\tWhere(query.And(\n")
	buf.WriteString("\t\t\t\tschema.Accounts.PublicId().Eq(query.Param[string](\"publicId\")),\n")
	buf.WriteString("\t\t\t\tschema.Accounts.DeletedAt().IsNull(),\n")
	buf.WriteString("\t\t\t)).\n")
	buf.WriteString("\t\t\tBuild())\n\n")

	buf.WriteString("}\n")

	return formatSource(buf.Bytes())
}
