package channelgen

import (
	"fmt"
	"strings"
	"testing"

	"github.com/shipq/shipq/codegen"
)

func TestGenerateSvelteChannelHooks_EmptyChannels(t *testing.T) {
	result, err := GenerateSvelteChannelHooks(nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(result), "No frontend channels defined") {
		t.Errorf("expected 'No frontend channels defined' message, got: %s", string(result))
	}
}

func TestGenerateSvelteChannelHooks_SkipsBackendChannels(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeBackendBillingChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(string(result), "No frontend channels defined") {
		t.Errorf("expected 'No frontend channels defined' for backend-only channels, got: %s", string(result))
	}
}

func TestGenerateSvelteChannelHooks_Header(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)
	if !strings.HasPrefix(output, "// Code generated by shipq. DO NOT EDIT.\n") {
		t.Error("output should start with generated file header")
	}
}

func TestGenerateSvelteChannelHooks_SvelteImports(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		`from "svelte/store"`,
		"writable,",
		"type Readable",
		`from "svelte"`,
		"onDestroy",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("Svelte imports should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_BaseChannelImports(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		`from "../shipq-channels"`,
		"type EmailNotificationChannel,",
		"type SendEmailRequest,",
		"type SendEmailResult,",
		"dispatchEmailNotification,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("base channel imports should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_UnidirectionalStoreStructure(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Options interface
	mustContainOptions := []string{
		"export interface EmailNotificationChannelOptions {",
		"onSendEmailResult?: (msg: SendEmailResult) => void;",
		"onError?: (error: Error) => void;",
	}
	for _, s := range mustContainOptions {
		if !strings.Contains(output, s) {
			t.Errorf("options interface should contain %q", s)
		}
	}

	// Store interface
	mustContainStore := []string{
		"export interface EmailNotificationChannelStore {",
		"channel: Readable<EmailNotificationChannel | null>;",
		"isConnecting: Readable<boolean>;",
		"error: Readable<Error | null>;",
		"dispatch: (req: SendEmailRequest) => Promise<void>;",
		"disconnect: () => void;",
	}
	for _, s := range mustContainStore {
		if !strings.Contains(output, s) {
			t.Errorf("store interface should contain %q", s)
		}
	}

	// Factory function
	mustContainFactory := []string{
		"export function createEmailNotificationChannel(",
		"options?: EmailNotificationChannelOptions,",
		"): EmailNotificationChannelStore {",
		"const channel = writable<EmailNotificationChannel | null>(null);",
		"const isConnecting = writable(false);",
		"const error = writable<Error | null>(null);",
		"let currentChannel: EmailNotificationChannel | null = null;",
		"let currentOptions = options;",
	}
	for _, s := range mustContainFactory {
		if !strings.Contains(output, s) {
			t.Errorf("factory function should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_OnDestroyCleanup(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "onDestroy(() => {") {
		t.Error("should have onDestroy for cleanup")
	}
	if !strings.Contains(output, "currentChannel?.unsubscribe();") {
		t.Error("should call unsubscribe on cleanup")
	}
}

func TestGenerateSvelteChannelHooks_DispatchFunction(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"async function dispatch(req: SendEmailRequest): Promise<void> {",
		"const ch = await dispatchEmailNotification(req);",
		"currentChannel = ch;",
		"channel.set(ch);",
		"isConnecting.set(false);",
		"ch.onSendEmailResult((msg) => currentOptions?.onSendEmailResult?.(msg));",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("dispatch function should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_ErrorHandling(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"} catch (err) {",
		"const e = err instanceof Error ? err : new Error(String(err));",
		"error.set(e);",
		"isConnecting.set(false);",
		"currentOptions?.onError?.(e);",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("error handling should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_DisconnectFunction(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"function disconnect(): void {",
		"currentChannel?.unsubscribe();",
		"currentChannel = null;",
		"channel.set(null);",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("disconnect function should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_ReadableStoreReturn(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Stores should be exposed as read-only Readable wrappers
	mustContain := []string{
		"channel: { subscribe: channel.subscribe },",
		"isConnecting: { subscribe: isConnecting.subscribe },",
		"error: { subscribe: error.subscribe },",
		"dispatch,",
		"disconnect,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("return object should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_BidirectionalChannel(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeBidirectionalChatbotChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Should import all message types
	mustContainImports := []string{
		"type ChatbotChannel,",
		"type StartChat,",
		"type ToolCallApproval,",
		"type BotMessage,",
		"type ToolCallRequest,",
		"type StreamingToken,",
		"type ChatFinished,",
		"dispatchChatbot,",
	}
	for _, s := range mustContainImports {
		if !strings.Contains(output, s) {
			t.Errorf("bidirectional imports should contain %q", s)
		}
	}

	// Should have FromServer handlers in options
	mustContainOptions := []string{
		"onBotMessage?: (msg: BotMessage) => void;",
		"onToolCallRequest?: (msg: ToolCallRequest) => void;",
		"onStreamingToken?: (msg: StreamingToken) => void;",
		"onChatFinished?: (msg: ChatFinished) => void;",
	}
	for _, s := range mustContainOptions {
		if !strings.Contains(output, s) {
			t.Errorf("bidirectional options should contain %q", s)
		}
	}

	// Should have send* methods for mid-stream FromClient messages
	mustContainSend := []string{
		"sendToolCallApproval: (msg: ToolCallApproval) => void;",
		"function sendToolCallApproval(msg: ToolCallApproval): void {",
		"currentChannel?.sendToolCallApproval(msg);",
	}
	for _, s := range mustContainSend {
		if !strings.Contains(output, s) {
			t.Errorf("bidirectional send methods should contain %q", s)
		}
	}

	// Return should include sendToolCallApproval
	if !strings.Contains(output, "sendToolCallApproval,") {
		t.Error("return object should include sendToolCallApproval")
	}

	// Should wire up all FromServer handlers in dispatch
	mustContainWire := []string{
		"ch.onBotMessage((msg) => currentOptions?.onBotMessage?.(msg));",
		"ch.onToolCallRequest((msg) => currentOptions?.onToolCallRequest?.(msg));",
		"ch.onStreamingToken((msg) => currentOptions?.onStreamingToken?.(msg));",
		"ch.onChatFinished((msg) => currentOptions?.onChatFinished?.(msg));",
	}
	for _, s := range mustContainWire {
		if !strings.Contains(output, s) {
			t.Errorf("bidirectional wiring should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_UnidirectionalNoSendMethods(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Unidirectional channel should not have any send* methods
	if strings.Contains(output, "function send") {
		t.Error("unidirectional channel should not have send methods")
	}
}

func TestGenerateSvelteChannelHooks_MultipleChannels(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
		makeBidirectionalChatbotChannel(),
		makeBackendBillingChannel(), // should be skipped
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Should have store factories for both frontend channels
	if !strings.Contains(output, "export function createEmailNotificationChannel(") {
		t.Error("should generate createEmailNotificationChannel factory")
	}
	if !strings.Contains(output, "export function createChatbotChannel(") {
		t.Error("should generate createChatbotChannel factory")
	}

	// Should NOT have anything about the backend channel
	if strings.Contains(output, "BillingSync") || strings.Contains(output, "billing_sync") {
		t.Error("should not generate code for backend channels")
	}
}

func TestGenerateSvelteChannelHooks_FactoryNaming(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Factory should use "create{PascalName}Channel" naming
	if !strings.Contains(output, "createEmailNotificationChannel") {
		t.Error("factory should be named createEmailNotificationChannel")
	}
	if !strings.Contains(output, "EmailNotificationChannelOptions") {
		t.Error("options interface should be named EmailNotificationChannelOptions")
	}
	if !strings.Contains(output, "EmailNotificationChannelStore") {
		t.Error("store interface should be named EmailNotificationChannelStore")
	}
}

func TestGenerateSvelteChannelHooks_PublicChannel(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makePublicAssistantChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Public channels should still get a store factory
	if !strings.Contains(output, "export function createAssistantChannel(") {
		t.Error("should generate createAssistantChannel factory for public channel")
	}
	if !strings.Contains(output, "type AssistantChannel,") {
		t.Error("should import AssistantChannel type")
	}
	if !strings.Contains(output, "dispatchAssistant,") {
		t.Error("should import dispatchAssistant function")
	}
}

func TestGenerateSvelteChannelHooks_NoUseCallbackOrUseRef(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeBidirectionalChatbotChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Svelte hooks should NOT use React patterns
	if strings.Contains(output, "useCallback") {
		t.Error("Svelte hooks should not use useCallback")
	}
	if strings.Contains(output, "useRef") {
		t.Error("Svelte hooks should not use useRef")
	}
	if strings.Contains(output, "useState") {
		t.Error("Svelte hooks should not use useState")
	}
	if strings.Contains(output, "useEffect") {
		t.Error("Svelte hooks should not use useEffect")
	}
}

func TestGenerateSvelteChannelHooks_DispatchResetsState(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// dispatch should disconnect existing channel, set connecting, clear error
	mustContainInOrder := []string{
		"currentChannel?.unsubscribe();",
		"isConnecting.set(true);",
		"error.set(null);",
	}
	lastIdx := 0
	for _, s := range mustContainInOrder {
		idx := strings.Index(output[lastIdx:], s)
		if idx < 0 {
			t.Errorf("dispatch should contain %q after previous items", s)
			break
		}
		lastIdx += idx + len(s)
	}
}

func TestGenerateSvelteChannelHooks_DispatchIsAsync(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// dispatch should be async and return Promise<void>
	if !strings.Contains(output, "async function dispatch(") {
		t.Error("dispatch should be async")
	}
	if !strings.Contains(output, "): Promise<void> {") {
		t.Error("dispatch should return Promise<void>")
	}
}

func TestGenerateSvelteChannelHooks_StoreInterfaceDispatchReturnsPromise(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// The store interface should declare dispatch as returning Promise<void>
	if !strings.Contains(output, "dispatch: (req: SendEmailRequest) => Promise<void>;") {
		t.Error("store interface dispatch should return Promise<void>")
	}
}

func TestGenerateSvelteChannelHooks_BidirectionalReturnObject(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeBidirectionalChatbotChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"channel: { subscribe: channel.subscribe },",
		"isConnecting: { subscribe: isConnecting.subscribe },",
		"error: { subscribe: error.subscribe },",
		"dispatch,",
		"sendToolCallApproval,",
		"disconnect,",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("bidirectional return object should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_SendMethodReturnType(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeBidirectionalChatbotChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	// Send methods should explicitly return void
	if !strings.Contains(output, "function sendToolCallApproval(msg: ToolCallApproval): void {") {
		t.Error("send methods should have explicit void return type")
	}
}

func TestGenerateSvelteChannelHooks_DisconnectReturnType(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if !strings.Contains(output, "function disconnect(): void {") {
		t.Error("disconnect should have explicit void return type")
	}
}

// ── LLM hook injection tests ────────────────────────────────────────────────

func TestGenerateSvelteChannelHooks_LLMChannel_ImportsLLMTypes(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makePublicAssistantChannel(),
	}
	llmCfg := &LLMConfig{
		LLMChannelPkgs: map[string]bool{
			"myapp/channels/assistant": true,
		},
	}

	result, err := GenerateSvelteChannelHooks(channels, llmCfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	for _, llmType := range llmStreamTypeNames() {
		importLine := fmt.Sprintf("type %s,", llmType)
		if !strings.Contains(output, importLine) {
			t.Errorf("LLM channel svelte hooks should import %q from base client", llmType)
		}
	}
}

func TestGenerateSvelteChannelHooks_LLMChannel_HasLLMHandlersInOptions(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makePublicAssistantChannel(),
	}
	llmCfg := &LLMConfig{
		LLMChannelPkgs: map[string]bool{
			"myapp/channels/assistant": true,
		},
	}

	result, err := GenerateSvelteChannelHooks(channels, llmCfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"onLLMTextDelta?: (msg: LLMTextDelta) => void;",
		"onLLMToolCallStart?: (msg: LLMToolCallStart) => void;",
		"onLLMToolCallResult?: (msg: LLMToolCallResult) => void;",
		"onLLMDone?: (msg: LLMDone) => void;",
		"onLLMToolsAvailable?: (msg: LLMToolsAvailable) => void;",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("LLM channel svelte options should contain %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_LLMChannel_WiresUpLLMHandlers(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makePublicAssistantChannel(),
	}
	llmCfg := &LLMConfig{
		LLMChannelPkgs: map[string]bool{
			"myapp/channels/assistant": true,
		},
	}

	result, err := GenerateSvelteChannelHooks(channels, llmCfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	mustContain := []string{
		"ch.onLLMTextDelta((msg) => currentOptions?.onLLMTextDelta?.(msg));",
		"ch.onLLMToolCallStart((msg) => currentOptions?.onLLMToolCallStart?.(msg));",
		"ch.onLLMToolCallResult((msg) => currentOptions?.onLLMToolCallResult?.(msg));",
		"ch.onLLMDone((msg) => currentOptions?.onLLMDone?.(msg));",
		"ch.onLLMToolsAvailable((msg) => currentOptions?.onLLMToolsAvailable?.(msg));",
	}
	for _, s := range mustContain {
		if !strings.Contains(output, s) {
			t.Errorf("LLM channel svelte hook should wire up handler: %q", s)
		}
	}
}

func TestGenerateSvelteChannelHooks_NonLLMChannel_NoLLMHandlers(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makeUnidirectionalEmailChannel(),
	}
	llmCfg := &LLMConfig{
		LLMChannelPkgs: map[string]bool{
			"myapp/channels/some_other": true,
		},
	}

	result, err := GenerateSvelteChannelHooks(channels, llmCfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if strings.Contains(output, "onLLMTextDelta") {
		t.Error("non-LLM channel should not have LLM handlers")
	}
}

func TestGenerateSvelteChannelHooks_NilLLMConfig_NoLLMHandlers(t *testing.T) {
	channels := []codegen.SerializedChannelInfo{
		makePublicAssistantChannel(),
	}

	result, err := GenerateSvelteChannelHooks(channels, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	output := string(result)

	if strings.Contains(output, "onLLMTextDelta") {
		t.Error("nil LLM config should not produce LLM handlers")
	}
}
