package channelgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/shipq/shipq/codegen"
)

// GenerateTypedChannel generates the Go source code for a typed channel wrapper.
// The generated file is intended to be written as zz_generated_channel.go in the
// channel's package directory.
//
// It produces:
//   - A sealed ServerMessage interface with a marker method and TypeName()
//   - ServerMessage implementations for each FromServer type
//   - A sealed ClientMessage interface (only if mid-stream FromClient types exist)
//   - ClientMessage implementations for each non-dispatch FromClient type
//   - A TypedChannel struct wrapping *channel.Channel
//   - TypedChannelFromContext(ctx) helper
//   - Send(ctx, ServerMessage) and convenience Send<Type> methods
//   - Type-specific Receive<Type> methods for non-dispatch FromClient types
//   - ClientMessageHandler struct (only if mid-stream types exist)
//   - ReceiveAny(ctx, ClientMessageHandler) (only if mid-stream types exist)
func GenerateTypedChannel(ch codegen.SerializedChannelInfo, modulePath string) ([]byte, error) {
	var buf bytes.Buffer

	// Classify messages
	var fromServerMsgs []codegen.SerializedMessageInfo
	var fromClientDispatch *codegen.SerializedMessageInfo
	var fromClientMidStream []codegen.SerializedMessageInfo

	for i := range ch.Messages {
		msg := &ch.Messages[i]
		switch msg.Direction {
		case "server_to_client":
			fromServerMsgs = append(fromServerMsgs, *msg)
		case "client_to_server":
			if msg.IsDispatch {
				fromClientDispatch = msg
			} else {
				fromClientMidStream = append(fromClientMidStream, *msg)
			}
		}
	}

	hasMidStreamClient := len(fromClientMidStream) > 0
	_ = fromClientDispatch // dispatch type is used by the worker, not the generated channel wrapper

	channelImport := modulePath + "/shipq/lib/channel"

	// --- Package declaration + imports ---
	fmt.Fprintf(&buf, "// Code generated by shipq. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", ch.PackageName)

	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"context\"\n")
	fmt.Fprintf(&buf, "\t\"encoding/json\"\n")
	fmt.Fprintf(&buf, "\t\"fmt\"\n")
	fmt.Fprintf(&buf, "\n")
	fmt.Fprintf(&buf, "\t%q\n", channelImport)
	fmt.Fprintf(&buf, ")\n\n")

	// --- Sealed ServerMessage interface ---
	fmt.Fprintf(&buf, "// ServerMessage is a sealed interface representing messages the server can send.\n")
	fmt.Fprintf(&buf, "// Only types defined in this package may implement it.\n")
	fmt.Fprintf(&buf, "type ServerMessage interface {\n")
	fmt.Fprintf(&buf, "\tserverMessage()\n")
	fmt.Fprintf(&buf, "\tTypeName() string\n")
	fmt.Fprintf(&buf, "}\n\n")

	// Implement ServerMessage for each FromServer type
	for _, msg := range fromServerMsgs {
		fmt.Fprintf(&buf, "func (*%s) serverMessage() {}\n", msg.TypeName)
		fmt.Fprintf(&buf, "func (*%s) TypeName() string { return %q }\n\n", msg.TypeName, msg.TypeName)
	}

	// --- Sealed ClientMessage interface (only if mid-stream types exist) ---
	if hasMidStreamClient {
		fmt.Fprintf(&buf, "// ClientMessage is a sealed interface representing mid-stream messages the client can send.\n")
		fmt.Fprintf(&buf, "// Only types defined in this package may implement it.\n")
		fmt.Fprintf(&buf, "type ClientMessage interface {\n")
		fmt.Fprintf(&buf, "\tclientMessage()\n")
		fmt.Fprintf(&buf, "\tTypeName() string\n")
		fmt.Fprintf(&buf, "}\n\n")

		for _, msg := range fromClientMidStream {
			fmt.Fprintf(&buf, "func (*%s) clientMessage() {}\n", msg.TypeName)
			fmt.Fprintf(&buf, "func (*%s) TypeName() string { return %q }\n\n", msg.TypeName, msg.TypeName)
		}
	}

	// --- TypedChannel struct ---
	fmt.Fprintf(&buf, "// TypedChannel provides type-safe send and receive operations for the %s channel.\n", ch.Name)
	fmt.Fprintf(&buf, "type TypedChannel struct {\n")
	fmt.Fprintf(&buf, "\traw *channel.Channel\n")
	fmt.Fprintf(&buf, "}\n\n")

	// --- TypedChannelFromContext ---
	fmt.Fprintf(&buf, "// TypedChannelFromContext extracts the raw channel from the context and wraps it\n")
	fmt.Fprintf(&buf, "// in a TypedChannel for type-safe operations.\n")
	fmt.Fprintf(&buf, "func TypedChannelFromContext(ctx context.Context) *TypedChannel {\n")
	fmt.Fprintf(&buf, "\treturn &TypedChannel{raw: channel.FromContext(ctx)}\n")
	fmt.Fprintf(&buf, "}\n\n")

	// --- Send(ctx, msg ServerMessage) error ---
	fmt.Fprintf(&buf, "// Send marshals a ServerMessage and sends it over the channel.\n")
	fmt.Fprintf(&buf, "func (tc *TypedChannel) Send(ctx context.Context, msg ServerMessage) error {\n")
	fmt.Fprintf(&buf, "\tdata, err := json.Marshal(msg)\n")
	fmt.Fprintf(&buf, "\tif err != nil {\n")
	fmt.Fprintf(&buf, "\t\treturn fmt.Errorf(\"marshal %%s: %%w\", msg.TypeName(), err)\n")
	fmt.Fprintf(&buf, "\t}\n")
	fmt.Fprintf(&buf, "\treturn tc.raw.Send(ctx, msg.TypeName(), data)\n")
	fmt.Fprintf(&buf, "}\n\n")

	// --- Convenience Send<Type> methods ---
	for _, msg := range fromServerMsgs {
		fmt.Fprintf(&buf, "// Send%s is a convenience method that sends a %s message.\n", msg.TypeName, msg.TypeName)
		fmt.Fprintf(&buf, "func (tc *TypedChannel) Send%s(ctx context.Context, msg *%s) error {\n", msg.TypeName, msg.TypeName)
		fmt.Fprintf(&buf, "\treturn tc.Send(ctx, msg)\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	// --- Type-specific Receive<Type> methods for non-dispatch FromClient types ---
	for _, msg := range fromClientMidStream {
		fmt.Fprintf(&buf, "// Receive%s blocks until a %s message arrives from the client.\n", msg.TypeName, msg.TypeName)
		fmt.Fprintf(&buf, "func (tc *TypedChannel) Receive%s(ctx context.Context) (*%s, error) {\n", msg.TypeName, msg.TypeName)
		fmt.Fprintf(&buf, "\tdata, err := tc.raw.Receive(ctx, %q)\n", msg.TypeName)
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\treturn nil, err\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tvar msg %s\n", msg.TypeName)
		fmt.Fprintf(&buf, "\tif err := json.Unmarshal(data, &msg); err != nil {\n")
		fmt.Fprintf(&buf, "\t\treturn nil, fmt.Errorf(\"unmarshal %s: %%w\", err)\n", msg.TypeName)
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\treturn &msg, nil\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	// --- ClientMessageHandler + ReceiveAny (only if mid-stream types exist) ---
	if hasMidStreamClient {
		// ClientMessageHandler struct
		fmt.Fprintf(&buf, "// ClientMessageHandler holds handler functions for each mid-stream client message type.\n")
		fmt.Fprintf(&buf, "// All fields must be non-nil; use validate() to check.\n")
		fmt.Fprintf(&buf, "type ClientMessageHandler struct {\n")
		for _, msg := range fromClientMidStream {
			fmt.Fprintf(&buf, "\tOn%s func(ctx context.Context, msg *%s) error\n", msg.TypeName, msg.TypeName)
		}
		fmt.Fprintf(&buf, "}\n\n")

		// validate method
		fmt.Fprintf(&buf, "// validate panics if any handler function is nil.\n")
		fmt.Fprintf(&buf, "func (h *ClientMessageHandler) validate() {\n")
		for _, msg := range fromClientMidStream {
			fmt.Fprintf(&buf, "\tif h.On%s == nil {\n", msg.TypeName)
			fmt.Fprintf(&buf, "\t\tpanic(\"ClientMessageHandler.On%s must not be nil\")\n", msg.TypeName)
			fmt.Fprintf(&buf, "\t}\n")
		}
		fmt.Fprintf(&buf, "}\n\n")

		// ReceiveAny method
		fmt.Fprintf(&buf, "// ReceiveAny blocks until any client message arrives, then dispatches it to the\n")
		fmt.Fprintf(&buf, "// appropriate handler in the ClientMessageHandler. All handler fields must be non-nil.\n")
		fmt.Fprintf(&buf, "func (tc *TypedChannel) ReceiveAny(ctx context.Context, h ClientMessageHandler) error {\n")
		fmt.Fprintf(&buf, "\th.validate()\n")
		fmt.Fprintf(&buf, "\ttypeName, data, err := tc.raw.ReceiveAny(ctx)\n")
		fmt.Fprintf(&buf, "\tif err != nil {\n")
		fmt.Fprintf(&buf, "\t\treturn err\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\tswitch typeName {\n")
		for _, msg := range fromClientMidStream {
			fmt.Fprintf(&buf, "\tcase %q:\n", msg.TypeName)
			fmt.Fprintf(&buf, "\t\tvar msg %s\n", msg.TypeName)
			fmt.Fprintf(&buf, "\t\tif err := json.Unmarshal(data, &msg); err != nil {\n")
			fmt.Fprintf(&buf, "\t\t\treturn fmt.Errorf(\"unmarshal %s: %%w\", err)\n", msg.TypeName)
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\treturn h.On%s(ctx, &msg)\n", msg.TypeName)
		}
		fmt.Fprintf(&buf, "\tdefault:\n")
		fmt.Fprintf(&buf, "\t\treturn fmt.Errorf(\"unknown client message type: %%s\", typeName)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	// Ensure fmt and json imports are used. The generated code always uses them,
	// so no need for blank imports.

	// Suppress unused import warnings if no messages of certain types exist.
	// In practice, every valid channel has at least one FromServer and one FromClient,
	// so the imports are always used. But just in case, we add usage guarantees.
	if len(fromServerMsgs) == 0 && !hasMidStreamClient {
		fmt.Fprintf(&buf, "var _ = json.Marshal\n")
		fmt.Fprintf(&buf, "var _ = fmt.Sprintf\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted source for debugging
		return buf.Bytes(), fmt.Errorf("failed to format generated channel code for %s: %w\nunformatted:\n%s", ch.Name, err, buf.String())
	}

	return formatted, nil
}

// packageNameFromImportPath extracts the last segment of an import path as the package name.
func packageNameFromImportPath(importPath string) string {
	parts := strings.Split(importPath, "/")
	return parts[len(parts)-1]
}
