package channelgen

import (
	"bytes"
	"fmt"

	"github.com/shipq/shipq/codegen"
	"github.com/shipq/shipq/codegen/tsutil"
)

// GenerateReactChannelHooks generates the React integration layer for channels
// (react/shipq-channels.ts). It produces a React hook per frontend channel that
// wraps the base dispatch function with useState, useRef, useEffect cleanup,
// and useCallback for stable references.
func GenerateReactChannelHooks(channels []codegen.SerializedChannelInfo) ([]byte, error) {
	// Filter to frontend-only channels
	var frontendChannels []codegen.SerializedChannelInfo
	for _, ch := range channels {
		if ch.Visibility == "frontend" {
			frontendChannels = append(frontendChannels, ch)
		}
	}

	if len(frontendChannels) == 0 {
		return []byte("// No frontend channels defined.\n"), nil
	}

	var buf bytes.Buffer

	// Header
	buf.WriteString("// Code generated by shipq. DO NOT EDIT.\n\n")

	// React imports
	buf.WriteString("import { useEffect, useRef, useCallback, useState } from \"react\";\n")

	// Collect all type/function imports from the base channel client
	buf.WriteString("import {\n")
	for _, ch := range frontendChannels {
		writeReactChannelImports(&buf, ch)
	}
	buf.WriteString("} from \"../shipq-channels\";\n")

	// Generate per-channel hooks
	for _, ch := range frontendChannels {
		if err := generateReactChannelHook(&buf, ch); err != nil {
			return nil, fmt.Errorf("generate react hook for channel %q: %w", ch.Name, err)
		}
	}

	return buf.Bytes(), nil
}

// writeReactChannelImports writes the import lines for a single channel's types
// and dispatch function from the base channel client.
func writeReactChannelImports(buf *bytes.Buffer, ch codegen.SerializedChannelInfo) {
	pascalName := tsutil.ToPascalCase(ch.Name)

	// Import channel interface type
	fmt.Fprintf(buf, "  type %sChannel,\n", pascalName)

	// Import all message types
	for _, msg := range ch.Messages {
		fmt.Fprintf(buf, "  type %s,\n", msg.TypeName)
	}

	// Import dispatch function
	fmt.Fprintf(buf, "  dispatch%s,\n", pascalName)
}

// generateReactChannelHook generates the React hook for a single channel.
func generateReactChannelHook(buf *bytes.Buffer, ch codegen.SerializedChannelInfo) error {
	pascalName := tsutil.ToPascalCase(ch.Name)
	camelName := tsutil.ToCamelCase(ch.Name)
	hookName := "use" + pascalName

	// Classify messages
	var fromServerMsgs []codegen.SerializedMessageInfo
	var fromClientDispatch *codegen.SerializedMessageInfo
	var fromClientMidStream []codegen.SerializedMessageInfo

	for i := range ch.Messages {
		msg := &ch.Messages[i]
		switch msg.Direction {
		case "server_to_client":
			fromServerMsgs = append(fromServerMsgs, *msg)
		case "client_to_server":
			if msg.IsDispatch {
				fromClientDispatch = msg
			} else {
				fromClientMidStream = append(fromClientMidStream, *msg)
			}
		}
	}

	if fromClientDispatch == nil {
		return fmt.Errorf("channel %q has no dispatch message", ch.Name)
	}

	buf.WriteString(fmt.Sprintf("\n// ─── %s ───\n", hookName))

	// Generate options interface
	fmt.Fprintf(buf, "\nexport interface %sOptions {\n", hookName)
	fmt.Fprintf(buf, "  /** Called when the channel is connected and ready */\n")
	fmt.Fprintf(buf, "  onReady?: (channel: %sChannel) => void;\n", pascalName)
	fmt.Fprintf(buf, "  /** Called on dispatch or connection error */\n")
	fmt.Fprintf(buf, "  onError?: (error: Error) => void;\n")
	for _, msg := range fromServerMsgs {
		fmt.Fprintf(buf, "  /** Called when a %s message is received */\n", msg.TypeName)
		fmt.Fprintf(buf, "  on%s?: (msg: %s) => void;\n", msg.TypeName, msg.TypeName)
	}
	buf.WriteString("}\n")

	// Generate return interface
	fmt.Fprintf(buf, "\nexport interface %sReturn {\n", hookName)
	fmt.Fprintf(buf, "  /** The channel instance, or null if not yet connected */\n")
	fmt.Fprintf(buf, "  channel: %sChannel | null;\n", pascalName)
	fmt.Fprintf(buf, "  /** Whether the channel is currently connecting */\n")
	fmt.Fprintf(buf, "  isConnecting: boolean;\n")
	fmt.Fprintf(buf, "  /** Any error that occurred during dispatch */\n")
	fmt.Fprintf(buf, "  error: Error | null;\n")
	fmt.Fprintf(buf, "  /** Dispatch (connect) with the given request */\n")
	fmt.Fprintf(buf, "  dispatch: (req: %s) => void;\n", fromClientDispatch.TypeName)
	for _, msg := range fromClientMidStream {
		camelMsg := tsutil.ToCamelCase(msg.TypeName)
		fmt.Fprintf(buf, "  /** Send a mid-stream %s */\n", msg.TypeName)
		fmt.Fprintf(buf, "  send%s: (msg: %s) => void;\n", msg.TypeName, msg.TypeName)
		_ = camelMsg // used for doc only
	}
	fmt.Fprintf(buf, "  /** Disconnect the channel */\n")
	fmt.Fprintf(buf, "  disconnect: () => void;\n")
	buf.WriteString("}\n")

	// Generate the hook function
	fmt.Fprintf(buf, "\nexport function %s(options?: %sOptions): %sReturn {\n", hookName, hookName, hookName)

	// Refs and state
	fmt.Fprintf(buf, "  const channelRef = useRef<%sChannel | null>(null);\n", pascalName)
	fmt.Fprintf(buf, "  const [channel, setChannel] = useState<%sChannel | null>(null);\n", pascalName)
	buf.WriteString("  const [isConnecting, setIsConnecting] = useState(false);\n")
	buf.WriteString("  const [error, setError] = useState<Error | null>(null);\n")
	buf.WriteString("\n")

	// Store latest callbacks in refs to avoid stale closures
	buf.WriteString("  // Store latest callbacks in refs to avoid stale closures\n")
	buf.WriteString("  const optionsRef = useRef(options);\n")
	buf.WriteString("  optionsRef.current = options;\n")
	buf.WriteString("\n")

	// Cleanup on unmount
	buf.WriteString("  // Cleanup on unmount\n")
	buf.WriteString("  useEffect(() => {\n")
	buf.WriteString("    return () => {\n")
	buf.WriteString("      channelRef.current?.unsubscribe();\n")
	buf.WriteString("    };\n")
	buf.WriteString("  }, []);\n")
	buf.WriteString("\n")

	// dispatch callback
	_ = camelName
	fmt.Fprintf(buf, "  const dispatch = useCallback(async (req: %s) => {\n", fromClientDispatch.TypeName)
	buf.WriteString("    // Disconnect existing channel if any\n")
	buf.WriteString("    channelRef.current?.unsubscribe();\n")
	buf.WriteString("    setIsConnecting(true);\n")
	buf.WriteString("    setError(null);\n")
	buf.WriteString("\n")
	buf.WriteString("    try {\n")
	fmt.Fprintf(buf, "      const ch = await dispatch%s(req);\n", pascalName)
	buf.WriteString("      channelRef.current = ch;\n")
	buf.WriteString("      setChannel(ch);\n")
	buf.WriteString("      setIsConnecting(false);\n")
	buf.WriteString("\n")

	// Wire up FromServer handlers
	buf.WriteString("      // Wire up FromServer handlers\n")
	for _, msg := range fromServerMsgs {
		fmt.Fprintf(buf, "      ch.on%s((msg) => optionsRef.current?.on%s?.(msg));\n", msg.TypeName, msg.TypeName)
	}
	buf.WriteString("\n")
	buf.WriteString("      optionsRef.current?.onReady?.(ch);\n")

	buf.WriteString("    } catch (err) {\n")
	buf.WriteString("      const e = err instanceof Error ? err : new Error(String(err));\n")
	buf.WriteString("      setError(e);\n")
	buf.WriteString("      setIsConnecting(false);\n")
	buf.WriteString("      optionsRef.current?.onError?.(e);\n")
	buf.WriteString("    }\n")
	buf.WriteString("  }, []);\n")
	buf.WriteString("\n")

	// send* callbacks for mid-stream messages
	for _, msg := range fromClientMidStream {
		fmt.Fprintf(buf, "  const send%s = useCallback((msg: %s) => {\n", msg.TypeName, msg.TypeName)
		fmt.Fprintf(buf, "    channelRef.current?.send%s(msg);\n", msg.TypeName)
		buf.WriteString("  }, []);\n")
		buf.WriteString("\n")
	}

	// disconnect callback
	buf.WriteString("  const disconnect = useCallback(() => {\n")
	buf.WriteString("    channelRef.current?.unsubscribe();\n")
	buf.WriteString("    channelRef.current = null;\n")
	buf.WriteString("    setChannel(null);\n")
	buf.WriteString("  }, []);\n")
	buf.WriteString("\n")

	// Return object
	buf.WriteString("  return { channel, isConnecting, error, dispatch,")
	for _, msg := range fromClientMidStream {
		fmt.Fprintf(buf, " send%s,", msg.TypeName)
	}
	buf.WriteString(" disconnect };\n")
	buf.WriteString("}\n")

	return nil
}
