package channelgen

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"strings"

	"github.com/shipq/shipq/codegen"
)

// GenerateIntegrationTests generates the Go source code for integration tests
// that exercise each channel's dispatch handler using MockQueue (synchronous,
// no Redis) and TestRecorder (in-memory, no Centrifugo).
//
// The generated file is written to channels/spec/zz_generated_integration_test.go.
func GenerateIntegrationTests(channels []codegen.SerializedChannelInfo, modulePath, shipqRoot string) error {
	code, err := GenerateIntegrationTestCode(channels, modulePath)
	if err != nil {
		return fmt.Errorf("generate integration test code: %w", err)
	}

	specDir := filepath.Join(shipqRoot, "channels", "spec")
	if err := codegen.EnsureDir(specDir); err != nil {
		return fmt.Errorf("create channels/spec directory: %w", err)
	}

	outputPath := filepath.Join(specDir, "zz_generated_integration_test.go")
	if _, err := codegen.WriteFileIfChanged(outputPath, code); err != nil {
		return fmt.Errorf("write integration test file: %w", err)
	}

	return nil
}

// GenerateIntegrationTestCode generates the Go source code for integration tests.
// Exported separately for unit testing the generator itself.
func GenerateIntegrationTestCode(channels []codegen.SerializedChannelInfo, modulePath string) ([]byte, error) {
	var buf bytes.Buffer

	channelImport := modulePath + "/shipq/lib/channel"

	// Collect channel package imports
	type channelMeta struct {
		ch                  codegen.SerializedChannelInfo
		dispatchMsg         *codegen.SerializedMessageInfo
		fromServerMsgs      []codegen.SerializedMessageInfo
		fromClientMidStream []codegen.SerializedMessageInfo
	}

	var metas []channelMeta
	importSet := make(map[string]bool)

	for _, ch := range channels {
		var dispatch *codegen.SerializedMessageInfo
		var fromServer []codegen.SerializedMessageInfo
		var midStream []codegen.SerializedMessageInfo

		for i := range ch.Messages {
			msg := &ch.Messages[i]
			switch msg.Direction {
			case "server_to_client":
				fromServer = append(fromServer, *msg)
			case "client_to_server":
				if msg.IsDispatch {
					dispatch = msg
				} else {
					midStream = append(midStream, *msg)
				}
			}
		}

		if dispatch == nil {
			continue
		}

		metas = append(metas, channelMeta{
			ch:                  ch,
			dispatchMsg:         dispatch,
			fromServerMsgs:      fromServer,
			fromClientMidStream: midStream,
		})

		if ch.PackagePath != "" {
			importSet[ch.PackagePath] = true
		}
	}

	if len(metas) == 0 {
		// Nothing to generate
		return []byte("//go:build integration\n\n// Code generated by shipq. DO NOT EDIT.\npackage spec\n"), nil
	}

	// --- File header ---
	buf.WriteString("//go:build integration\n\n")
	buf.WriteString("// Code generated by shipq. DO NOT EDIT.\n")
	buf.WriteString("package spec\n\n")

	// --- Imports ---
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"testing\"\n")
	buf.WriteString("\n")
	fmt.Fprintf(&buf, "\t%q\n", channelImport)
	buf.WriteString("\n")

	for _, m := range metas {
		if m.ch.PackagePath != "" && importSet[m.ch.PackagePath] {
			fmt.Fprintf(&buf, "\t%s %q\n", m.ch.PackageName, m.ch.PackagePath)
			delete(importSet, m.ch.PackagePath) // avoid duplicates
		}
	}

	buf.WriteString(")\n\n")

	// --- Generate test functions ---
	for _, m := range metas {
		hasMidStream := len(m.fromClientMidStream) > 0
		testName := integrationTestName(m.ch.Name)

		fmt.Fprintf(&buf, "func %s(t *testing.T) {\n", testName)

		// Set up MockQueue and TestRecorder
		buf.WriteString("\trecorder := channel.NewTestRecorder()\n")
		buf.WriteString("\tqueue := channel.NewMockQueue()\n")
		buf.WriteString("\n")

		// Register handler on MockQueue
		fmt.Fprintf(&buf, "\tif err := queue.RegisterTask(%q, func(payload string) error {\n", m.ch.Name)
		buf.WriteString("\t\tvar dp channel.DispatchPayload\n")
		buf.WriteString("\t\tif err := json.Unmarshal([]byte(payload), &dp); err != nil {\n")
		buf.WriteString("\t\t\treturn err\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\n")
		buf.WriteString("\t\tscopedName := channel.ComputeChannelID(dp.ChannelName, dp.AccountID, dp.JobID, dp.IsPublic)\n")
		buf.WriteString("\t\tincoming, cleanup, err := recorder.Subscribe(scopedName, \"test-worker\")\n")
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString("\t\t\treturn err\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tdefer cleanup()\n")
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "\t\tch := channel.NewChannel(dp.ChannelName, dp.JobID, dp.AccountID, dp.OrgID, %v, recorder, incoming, cleanup)\n", m.ch.IsPublic)
		buf.WriteString("\t\tctx := channel.WithChannel(context.Background(), ch)\n")
		buf.WriteString("\n")

		// Deserialize the dispatch request
		dispatchType := m.ch.PackageName + "." + m.dispatchMsg.TypeName
		fmt.Fprintf(&buf, "\t\tvar req %s\n", dispatchType)
		buf.WriteString("\t\tif err := json.Unmarshal(dp.Request, &req); err != nil {\n")
		buf.WriteString("\t\t\treturn err\n")
		buf.WriteString("\t\t}\n")

		// For bidirectional channels: pre-queue incoming messages before calling handler
		if hasMidStream {
			buf.WriteString("\n")
			buf.WriteString("\t\t// Pre-queue mid-stream client messages so the handler can receive them\n")
			for _, mid := range m.fromClientMidStream {
				midType := m.ch.PackageName + "." + mid.TypeName
				fmt.Fprintf(&buf, "\t\trecorder.EnqueueIncoming(%q, %s{})\n", mid.TypeName, midType)
			}
		}

		// Call the handler
		buf.WriteString("\n")
		handlerRef := m.ch.PackageName + "." + m.dispatchMsg.HandlerName
		fmt.Fprintf(&buf, "\t\treturn %s(ctx, &req)\n", handlerRef)
		buf.WriteString("\t}); err != nil {\n")
		buf.WriteString("\t\tt.Fatalf(\"RegisterTask failed: %v\", err)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\n")

		// Build and dispatch a test payload
		buf.WriteString("\t// Build a test dispatch payload\n")
		fmt.Fprintf(&buf, "\treqJSON, err := json.Marshal(%s{", dispatchType)
		writeTestFieldValues(&buf, m.dispatchMsg.Fields)
		buf.WriteString("})\n")
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\tt.Fatalf(\"marshal request: %v\", err)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\n")

		buf.WriteString("\tdp := channel.DispatchPayload{\n")
		buf.WriteString("\t\tJobID:       \"test-job-1\",\n")
		fmt.Fprintf(&buf, "\t\tChannelName: %q,\n", m.ch.Name)
		if !m.ch.IsPublic {
			buf.WriteString("\t\tAccountID:   1,\n")
			buf.WriteString("\t\tOrgID:       1,\n")
		}
		fmt.Fprintf(&buf, "\t\tIsPublic:    %v,\n", m.ch.IsPublic)
		buf.WriteString("\t\tRequest:     reqJSON,\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tdpJSON, err := json.Marshal(dp)\n")
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\tt.Fatalf(\"marshal dispatch payload: %v\", err)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\n")

		// Enqueue task (synchronous execution via MockQueue)
		fmt.Fprintf(&buf, "\tif err := queue.SendTask(%q, string(dpJSON), channel.TaskOptions{}); err != nil {\n", m.ch.Name)
		buf.WriteString("\t\tt.Fatalf(\"SendTask failed: %v\", err)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\n")

		// Assert that expected server messages were sent
		buf.WriteString("\t// Verify expected server messages were sent\n")
		for _, srv := range m.fromServerMsgs {
			fmt.Fprintf(&buf, "\tif !recorder.HasSent(%q) {\n", srv.TypeName)
			fmt.Fprintf(&buf, "\t\tt.Errorf(\"expected %s message to be sent\")\n", srv.TypeName)
			buf.WriteString("\t}\n")
		}

		// For public channels, verify no account_id scoping
		if m.ch.IsPublic {
			buf.WriteString("\n")
			buf.WriteString("\t// Public channel: verify no account scoping\n")
			buf.WriteString("\tif dp.AccountID != 0 {\n")
			buf.WriteString("\t\tt.Errorf(\"expected AccountID=0 for public channel, got %d\", dp.AccountID)\n")
			buf.WriteString("\t}\n")
		}

		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted for debugging
		return buf.Bytes(), fmt.Errorf("format integration test code: %w\nunformatted:\n%s", err, buf.String())
	}

	return formatted, nil
}

// integrationTestName produces a test function name for a channel.
// e.g., "email" -> "TestIntegration_Email_Dispatch"
func integrationTestName(channelName string) string {
	return "TestIntegration_" + capitalizeFirst(channelName) + "_Dispatch"
}

// capitalizeFirst capitalizes the first letter of a string.
func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// writeTestFieldValues writes zero-value field initializers for struct fields.
// This produces minimal test payloads like {To: "test", Amount: 0}.
func writeTestFieldValues(buf *bytes.Buffer, fields []codegen.SerializedFieldInfo) {
	if len(fields) == 0 {
		return
	}
	for i, f := range fields {
		if i > 0 {
			buf.WriteString(", ")
		}
		fmt.Fprintf(buf, "%s: %s", f.Name, testZeroValue(f.Type))
	}
}

// testZeroValue returns a suitable test value for a Go type string.
func testZeroValue(goType string) string {
	switch goType {
	case "string":
		return `"test"`
	case "int", "int8", "int16", "int32", "int64":
		return "1"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "1"
	case "float32", "float64":
		return "1.0"
	case "bool":
		return "true"
	default:
		if strings.HasPrefix(goType, "[]") {
			return "nil"
		}
		if strings.HasPrefix(goType, "*") {
			return "nil"
		}
		if strings.HasPrefix(goType, "map[") {
			return "nil"
		}
		return `"test"`
	}
}
