// Code generated by portsql. DO NOT EDIT.
package migrations

import (
	"context"
	"database/sql"
	_ "embed"

	"github.com/portsql/portsql/src/migrate"
)

//go:embed schema.json
var schemaJSON []byte

// Plan returns the migration plan reconstructed from the embedded schema.
func Plan() (*migrate.MigrationPlan, error) {
	return migrate.PlanFromJSON(schemaJSON)
}

// Run executes all pending migrations. Safe to call on every app startup.
// The dialect is auto-detected from the database connection.
func Run(ctx context.Context, db *sql.DB, dialect string) error {
	plan, err := Plan()
	if err != nil {
		return err
	}
	return migrate.Run(ctx, db, plan, dialect)
}
