// Code generated by shipq. DO NOT EDIT.

import { useEffect, useRef, useCallback, useState } from "react";
import {
  type EmailNotificationChannel,
  type SendEmailRequest,
  type SendEmailResult,
  dispatchEmailNotification,
  type ChatbotChannel,
  type StartChat,
  type ToolCallApproval,
  type BotMessage,
  type ToolCallRequest,
  type StreamingToken,
  type ChatFinished,
  dispatchChatbot,
  type AssistantChannel,
  type AssistantQuery,
  type AssistantAnswer,
  dispatchAssistant,
} from "../shipq-channels";

// ─── useEmailNotification ───

export interface useEmailNotificationOptions {
  /** Called when the channel is connected and ready */
  onReady?: (channel: EmailNotificationChannel) => void;
  /** Called on dispatch or connection error */
  onError?: (error: Error) => void;
  /** Called when a SendEmailResult message is received */
  onSendEmailResult?: (msg: SendEmailResult) => void;
}

export interface useEmailNotificationReturn {
  /** The channel instance, or null if not yet connected */
  channel: EmailNotificationChannel | null;
  /** Whether the channel is currently connecting */
  isConnecting: boolean;
  /** Any error that occurred during dispatch */
  error: Error | null;
  /** Dispatch (connect) with the given request */
  dispatch: (req: SendEmailRequest) => void;
  /** Disconnect the channel */
  disconnect: () => void;
}

export function useEmailNotification(options?: useEmailNotificationOptions): useEmailNotificationReturn {
  const channelRef = useRef<EmailNotificationChannel | null>(null);
  const [channel, setChannel] = useState<EmailNotificationChannel | null>(null);
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  // Store latest callbacks in refs to avoid stale closures
  const optionsRef = useRef(options);
  optionsRef.current = options;

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      channelRef.current?.unsubscribe();
    };
  }, []);

  const dispatch = useCallback(async (req: SendEmailRequest) => {
    // Disconnect existing channel if any
    channelRef.current?.unsubscribe();
    setIsConnecting(true);
    setError(null);

    try {
      const ch = await dispatchEmailNotification(req);
      channelRef.current = ch;
      setChannel(ch);
      setIsConnecting(false);

      // Wire up FromServer handlers
      ch.onSendEmailResult((msg) => optionsRef.current?.onSendEmailResult?.(msg));

      optionsRef.current?.onReady?.(ch);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      setError(e);
      setIsConnecting(false);
      optionsRef.current?.onError?.(e);
    }
  }, []);

  const disconnect = useCallback(() => {
    channelRef.current?.unsubscribe();
    channelRef.current = null;
    setChannel(null);
  }, []);

  return { channel, isConnecting, error, dispatch, disconnect };
}

// ─── useChatbot ───

export interface useChatbotOptions {
  /** Called when the channel is connected and ready */
  onReady?: (channel: ChatbotChannel) => void;
  /** Called on dispatch or connection error */
  onError?: (error: Error) => void;
  /** Called when a BotMessage message is received */
  onBotMessage?: (msg: BotMessage) => void;
  /** Called when a ToolCallRequest message is received */
  onToolCallRequest?: (msg: ToolCallRequest) => void;
  /** Called when a StreamingToken message is received */
  onStreamingToken?: (msg: StreamingToken) => void;
  /** Called when a ChatFinished message is received */
  onChatFinished?: (msg: ChatFinished) => void;
}

export interface useChatbotReturn {
  /** The channel instance, or null if not yet connected */
  channel: ChatbotChannel | null;
  /** Whether the channel is currently connecting */
  isConnecting: boolean;
  /** Any error that occurred during dispatch */
  error: Error | null;
  /** Dispatch (connect) with the given request */
  dispatch: (req: StartChat) => void;
  /** Send a mid-stream ToolCallApproval */
  sendToolCallApproval: (msg: ToolCallApproval) => void;
  /** Disconnect the channel */
  disconnect: () => void;
}

export function useChatbot(options?: useChatbotOptions): useChatbotReturn {
  const channelRef = useRef<ChatbotChannel | null>(null);
  const [channel, setChannel] = useState<ChatbotChannel | null>(null);
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  // Store latest callbacks in refs to avoid stale closures
  const optionsRef = useRef(options);
  optionsRef.current = options;

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      channelRef.current?.unsubscribe();
    };
  }, []);

  const dispatch = useCallback(async (req: StartChat) => {
    // Disconnect existing channel if any
    channelRef.current?.unsubscribe();
    setIsConnecting(true);
    setError(null);

    try {
      const ch = await dispatchChatbot(req);
      channelRef.current = ch;
      setChannel(ch);
      setIsConnecting(false);

      // Wire up FromServer handlers
      ch.onBotMessage((msg) => optionsRef.current?.onBotMessage?.(msg));
      ch.onToolCallRequest((msg) => optionsRef.current?.onToolCallRequest?.(msg));
      ch.onStreamingToken((msg) => optionsRef.current?.onStreamingToken?.(msg));
      ch.onChatFinished((msg) => optionsRef.current?.onChatFinished?.(msg));

      optionsRef.current?.onReady?.(ch);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      setError(e);
      setIsConnecting(false);
      optionsRef.current?.onError?.(e);
    }
  }, []);

  const sendToolCallApproval = useCallback((msg: ToolCallApproval) => {
    channelRef.current?.sendToolCallApproval(msg);
  }, []);

  const disconnect = useCallback(() => {
    channelRef.current?.unsubscribe();
    channelRef.current = null;
    setChannel(null);
  }, []);

  return { channel, isConnecting, error, dispatch, sendToolCallApproval, disconnect };
}

// ─── useAssistant ───

export interface useAssistantOptions {
  /** Called when the channel is connected and ready */
  onReady?: (channel: AssistantChannel) => void;
  /** Called on dispatch or connection error */
  onError?: (error: Error) => void;
  /** Called when a AssistantAnswer message is received */
  onAssistantAnswer?: (msg: AssistantAnswer) => void;
}

export interface useAssistantReturn {
  /** The channel instance, or null if not yet connected */
  channel: AssistantChannel | null;
  /** Whether the channel is currently connecting */
  isConnecting: boolean;
  /** Any error that occurred during dispatch */
  error: Error | null;
  /** Dispatch (connect) with the given request */
  dispatch: (req: AssistantQuery) => void;
  /** Disconnect the channel */
  disconnect: () => void;
}

export function useAssistant(options?: useAssistantOptions): useAssistantReturn {
  const channelRef = useRef<AssistantChannel | null>(null);
  const [channel, setChannel] = useState<AssistantChannel | null>(null);
  const [isConnecting, setIsConnecting] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  // Store latest callbacks in refs to avoid stale closures
  const optionsRef = useRef(options);
  optionsRef.current = options;

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      channelRef.current?.unsubscribe();
    };
  }, []);

  const dispatch = useCallback(async (req: AssistantQuery) => {
    // Disconnect existing channel if any
    channelRef.current?.unsubscribe();
    setIsConnecting(true);
    setError(null);

    try {
      const ch = await dispatchAssistant(req);
      channelRef.current = ch;
      setChannel(ch);
      setIsConnecting(false);

      // Wire up FromServer handlers
      ch.onAssistantAnswer((msg) => optionsRef.current?.onAssistantAnswer?.(msg));

      optionsRef.current?.onReady?.(ch);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      setError(e);
      setIsConnecting(false);
      optionsRef.current?.onError?.(e);
    }
  }, []);

  const disconnect = useCallback(() => {
    channelRef.current?.unsubscribe();
    channelRef.current = null;
    setChannel(null);
  }, []);

  return { channel, isConnecting, error, dispatch, disconnect };
}
