// Code generated by shipq. DO NOT EDIT.

import { writable, type Readable } from "svelte/store";
import { onDestroy } from "svelte";
import {
  type EmailNotificationChannel,
  type SendEmailRequest,
  type SendEmailResult,
  dispatchEmailNotification,
  type ChatbotChannel,
  type StartChat,
  type ToolCallApproval,
  type BotMessage,
  type ToolCallRequest,
  type StreamingToken,
  type ChatFinished,
  dispatchChatbot,
  type AssistantChannel,
  type AssistantQuery,
  type AssistantAnswer,
  dispatchAssistant,
} from "../shipq-channels";

// ─── createEmailNotificationChannel ───

export interface EmailNotificationChannelOptions {
  onSendEmailResult?: (msg: SendEmailResult) => void;
  onError?: (error: Error) => void;
}

export interface EmailNotificationChannelStore {
  channel: Readable<EmailNotificationChannel | null>;
  isConnecting: Readable<boolean>;
  error: Readable<Error | null>;
  dispatch: (req: SendEmailRequest) => Promise<void>;
  disconnect: () => void;
}

export function createEmailNotificationChannel(
  options?: EmailNotificationChannelOptions,
): EmailNotificationChannelStore {
  const channel = writable<EmailNotificationChannel | null>(null);
  const isConnecting = writable(false);
  const error = writable<Error | null>(null);
  let currentChannel: EmailNotificationChannel | null = null;
  let currentOptions = options;

  // Auto-cleanup on component destroy
  onDestroy(() => {
    currentChannel?.unsubscribe();
  });

  async function dispatch(req: SendEmailRequest): Promise<void> {
    currentChannel?.unsubscribe();
    isConnecting.set(true);
    error.set(null);

    try {
      const ch = await dispatchEmailNotification(req);
      currentChannel = ch;
      channel.set(ch);
      isConnecting.set(false);

      ch.onSendEmailResult((msg) => currentOptions?.onSendEmailResult?.(msg));
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      error.set(e);
      isConnecting.set(false);
      currentOptions?.onError?.(e);
    }
  }

  function disconnect(): void {
    currentChannel?.unsubscribe();
    currentChannel = null;
    channel.set(null);
  }

  return {
    channel: { subscribe: channel.subscribe },
    isConnecting: { subscribe: isConnecting.subscribe },
    error: { subscribe: error.subscribe },
    dispatch,
    disconnect,
  };
}

// ─── createChatbotChannel ───

export interface ChatbotChannelOptions {
  onBotMessage?: (msg: BotMessage) => void;
  onToolCallRequest?: (msg: ToolCallRequest) => void;
  onStreamingToken?: (msg: StreamingToken) => void;
  onChatFinished?: (msg: ChatFinished) => void;
  onError?: (error: Error) => void;
}

export interface ChatbotChannelStore {
  channel: Readable<ChatbotChannel | null>;
  isConnecting: Readable<boolean>;
  error: Readable<Error | null>;
  dispatch: (req: StartChat) => Promise<void>;
  sendToolCallApproval: (msg: ToolCallApproval) => void;
  disconnect: () => void;
}

export function createChatbotChannel(
  options?: ChatbotChannelOptions,
): ChatbotChannelStore {
  const channel = writable<ChatbotChannel | null>(null);
  const isConnecting = writable(false);
  const error = writable<Error | null>(null);
  let currentChannel: ChatbotChannel | null = null;
  let currentOptions = options;

  // Auto-cleanup on component destroy
  onDestroy(() => {
    currentChannel?.unsubscribe();
  });

  async function dispatch(req: StartChat): Promise<void> {
    currentChannel?.unsubscribe();
    isConnecting.set(true);
    error.set(null);

    try {
      const ch = await dispatchChatbot(req);
      currentChannel = ch;
      channel.set(ch);
      isConnecting.set(false);

      ch.onBotMessage((msg) => currentOptions?.onBotMessage?.(msg));
      ch.onToolCallRequest((msg) => currentOptions?.onToolCallRequest?.(msg));
      ch.onStreamingToken((msg) => currentOptions?.onStreamingToken?.(msg));
      ch.onChatFinished((msg) => currentOptions?.onChatFinished?.(msg));
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      error.set(e);
      isConnecting.set(false);
      currentOptions?.onError?.(e);
    }
  }

  function sendToolCallApproval(msg: ToolCallApproval): void {
    currentChannel?.sendToolCallApproval(msg);
  }

  function disconnect(): void {
    currentChannel?.unsubscribe();
    currentChannel = null;
    channel.set(null);
  }

  return {
    channel: { subscribe: channel.subscribe },
    isConnecting: { subscribe: isConnecting.subscribe },
    error: { subscribe: error.subscribe },
    dispatch,
    sendToolCallApproval,
    disconnect,
  };
}

// ─── createAssistantChannel ───

export interface AssistantChannelOptions {
  onAssistantAnswer?: (msg: AssistantAnswer) => void;
  onError?: (error: Error) => void;
}

export interface AssistantChannelStore {
  channel: Readable<AssistantChannel | null>;
  isConnecting: Readable<boolean>;
  error: Readable<Error | null>;
  dispatch: (req: AssistantQuery) => Promise<void>;
  disconnect: () => void;
}

export function createAssistantChannel(
  options?: AssistantChannelOptions,
): AssistantChannelStore {
  const channel = writable<AssistantChannel | null>(null);
  const isConnecting = writable(false);
  const error = writable<Error | null>(null);
  let currentChannel: AssistantChannel | null = null;
  let currentOptions = options;

  // Auto-cleanup on component destroy
  onDestroy(() => {
    currentChannel?.unsubscribe();
  });

  async function dispatch(req: AssistantQuery): Promise<void> {
    currentChannel?.unsubscribe();
    isConnecting.set(true);
    error.set(null);

    try {
      const ch = await dispatchAssistant(req);
      currentChannel = ch;
      channel.set(ch);
      isConnecting.set(false);

      ch.onAssistantAnswer((msg) => currentOptions?.onAssistantAnswer?.(msg));
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      error.set(e);
      isConnecting.set(false);
      currentOptions?.onError?.(e);
    }
  }

  function disconnect(): void {
    currentChannel?.unsubscribe();
    currentChannel = null;
    channel.set(null);
  }

  return {
    channel: { subscribe: channel.subscribe },
    isConnecting: { subscribe: isConnecting.subscribe },
    error: { subscribe: error.subscribe },
    dispatch,
    disconnect,
  };
}
