package queryrunner

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/shipq/shipq/db/portsql/query"
	"github.com/shipq/shipq/db/portsql/query/compile"
	"github.com/shipq/shipq/dbstrings"
	"github.com/shipq/shipq/dburl"
)

// UnifiedRunnerConfig holds all information needed to generate the runner.
type UnifiedRunnerConfig struct {
	ModulePath  string
	Dialect     string // "postgres", "mysql", "sqlite"
	UserQueries []query.SerializedQuery
}

// GenerateUnifiedRunner generates the complete runner for a dialect.
// This produces shipq/queries/<dialect>/runner.go
func GenerateUnifiedRunner(cfg UnifiedRunnerConfig) ([]byte, error) {
	var buf bytes.Buffer

	// Get the compiler for this dialect
	compiler, err := getCompiler(cfg.Dialect)
	if err != nil {
		return nil, err
	}
	// Collect all query info for code generation
	userQueryInfo, err := compileUserQueries(cfg.UserQueries, compiler)
	if err != nil {
		return nil, err
	}

	// Collect imports
	imports := collectRunnerImports(cfg, userQueryInfo)

	// Write header
	buf.WriteString("// Code generated by shipq. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", cfg.Dialect))

	// Write imports
	writeImports(&buf, imports)

	// SQLite stores datetime/json values as text; helpers convert scan intermediates.
	if cfg.Dialect == dburl.DialectSQLite {
		writeSQLiteScanHelpers(&buf)
	}

	// MySQL and SQLite JSON_OBJECT outputs TINYINT(1) bools as 0/1 instead of
	// true/false. Emit a small helper to patch the raw JSON before unmarshal.
	if jsonAggNeedsBoolFix(cfg.Dialect, userQueryInfo) {
		writeJSONBoolFixHelper(&buf)
	}

	// Write Querier interface
	writeQuerierInterface(&buf)

	// Write QueryRunner struct
	writeQueryRunnerStruct(&buf, userQueryInfo, cfg)

	// Write NewQueryRunner constructor
	writeNewQueryRunner(&buf, userQueryInfo, cfg)

	// Write WithTx method
	writeWithTx(&buf, userQueryInfo, cfg)

	// Write WithDB method
	writeWithDB(&buf, userQueryInfo, cfg)

	// Write user-defined query methods
	for _, qi := range userQueryInfo {
		if err := writeUserQueryMethod(&buf, qi, cfg); err != nil {
			return nil, err
		}
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted for debugging
		return buf.Bytes(), fmt.Errorf("failed to format runner.go: %w (unformatted output returned)", err)
	}

	return formatted, nil
}

// GenerateSharedTypes generates the types.go file with param/result structs.
// This produces shipq/queries/types.go
func GenerateSharedTypes(cfg UnifiedRunnerConfig) ([]byte, error) {
	var buf bytes.Buffer

	// Compile user queries to get type information
	compiler, err := getCompiler(cfg.Dialect)
	if err != nil {
		return nil, err
	}

	userQueryInfo, err := compileUserQueries(cfg.UserQueries, compiler)
	if err != nil {
		return nil, err
	}

	// Collect imports needed for types
	imports := collectTypesImports(userQueryInfo, cfg)

	// Always need context for RunnerFromContext
	imports["context"] = true

	// Always need database/sql for TxRunner
	imports["database/sql"] = true

	// Need encoding/base64 and encoding/json for cursor helpers (paginated queries)
	for _, qi := range userQueryInfo {
		if qi.ReturnType == query.ReturnPaginated {
			imports["encoding/base64"] = true
			imports["encoding/json"] = true
			break
		}
	}

	// Write header
	buf.WriteString("// Code generated by shipq. DO NOT EDIT.\n")
	buf.WriteString("package queries\n\n")

	// Write imports if any
	if len(imports) > 0 {
		writeImports(&buf, imports)
	}

	// Write TxRunner struct
	writeTxRunner(&buf)

	// Write context helpers for runner access
	writeContextHelpers(&buf, cfg, userQueryInfo)

	// Write user query types
	for _, qi := range userQueryInfo {
		writeUserQueryTypes(&buf, qi)
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted for debugging
		return buf.Bytes(), fmt.Errorf("failed to format types.go: %w (unformatted output returned)", err)
	}

	return formatted, nil
}

// writeTxRunner writes the TxRunner struct that wraps a Runner backed by a transaction.
func writeTxRunner(buf *bytes.Buffer) {
	buf.WriteString("// =============================================================================\n")
	buf.WriteString("// Transaction Support\n")
	buf.WriteString("// =============================================================================\n\n")

	buf.WriteString("// TxRunner is a Runner backed by a database transaction.\n")
	buf.WriteString("// Use BeginTx on a Runner to obtain one, then call Commit or Rollback.\n")
	buf.WriteString("type TxRunner struct {\n")
	buf.WriteString("\tRunner\n")
	buf.WriteString("\tTx *sql.Tx\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// Commit commits the underlying transaction.\n")
	buf.WriteString("func (t *TxRunner) Commit() error { return t.Tx.Commit() }\n\n")

	buf.WriteString("// Rollback aborts the underlying transaction.\n")
	buf.WriteString("// It is safe to call after Commit — the driver returns sql.ErrTxDone.\n")
	buf.WriteString("func (t *TxRunner) Rollback() error { return t.Tx.Rollback() }\n\n")
}

// writeContextHelpers writes the RunnerFromContext and NewContextWithRunner functions.
func writeContextHelpers(buf *bytes.Buffer, cfg UnifiedRunnerConfig, userQueries []userQueryInfo) {
	buf.WriteString("// =============================================================================\n")
	buf.WriteString("// Context Helpers\n")
	buf.WriteString("// =============================================================================\n\n")

	buf.WriteString("type contextKey struct{}\n\n")

	// Generate the Runner interface with all CRUD and user-defined query methods
	buf.WriteString("// Runner is the interface that all dialect-specific runners implement.\n")
	buf.WriteString("// This allows handlers to work with any database dialect.\n")
	buf.WriteString("type Runner interface {\n")

	// Add method signatures for user-defined queries
	for _, qi := range userQueries {
		switch qi.ReturnType {
		case query.ReturnOne:
			buf.WriteString(fmt.Sprintf("\t%s(ctx context.Context, params %sParams) (*%sResult, error)\n", qi.Name, qi.Name, qi.Name))
		case query.ReturnMany:
			buf.WriteString(fmt.Sprintf("\t%s(ctx context.Context, params %sParams) ([]%sResult, error)\n", qi.Name, qi.Name, qi.Name))
		case query.ReturnExec:
			buf.WriteString(fmt.Sprintf("\t%s(ctx context.Context, params %sParams) (sql.Result, error)\n", qi.Name, qi.Name))
		case query.ReturnPaginated:
			buf.WriteString(fmt.Sprintf("\t%s(ctx context.Context, params %sParams) (*%sResult, error)\n", qi.Name, qi.Name, qi.Name))
		}
	}

	// BeginTx method on the Runner interface
	buf.WriteString("\tBeginTx(ctx context.Context) (*TxRunner, error)\n")

	buf.WriteString("}\n\n")

	buf.WriteString("// NewContextWithRunner returns a new context with the QueryRunner attached.\n")
	buf.WriteString("func NewContextWithRunner(ctx context.Context, runner Runner) context.Context {\n")
	buf.WriteString("\treturn context.WithValue(ctx, contextKey{}, runner)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// RunnerFromContext extracts the QueryRunner from the context.\n")
	buf.WriteString("// Panics if no runner is present (indicates middleware misconfiguration).\n")
	buf.WriteString("func RunnerFromContext(ctx context.Context) Runner {\n")
	buf.WriteString("\trunner := ctx.Value(contextKey{})\n")
	buf.WriteString("\tif runner == nil {\n")
	buf.WriteString("\t\tpanic(\"queries: no runner in context - ensure middleware calls NewContextWithRunner\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn runner.(Runner)\n")
	buf.WriteString("}\n\n")
}

// =============================================================================
// Internal Types
// =============================================================================

// userQueryInfo holds compiled information about a user-defined query.
type userQueryInfo struct {
	Name         string
	ReturnType   query.QueryReturnType
	QueryKind    string // "select", "insert", "update", "delete"
	TableName    string // from AST.FromTable.Name (used for MySQL INSERT fallback)
	SQL          string
	HasReturning bool     // true if AST had RETURNING columns (compiled away for MySQL)
	ParamOrder   []string // Parameter names in SQL order (may have duplicates)
	Params       []paramInfo
	Results      []resultInfo

	// Paginated query fields (only set when ReturnType == ReturnPaginated)
	CursorSQL        string                   // SQL with cursor WHERE clause injected
	CursorParamOrder []string                 // Parameter names in SQL order for cursor SQL
	CursorColumns    []query.SerializedColumn // Cursor column metadata

	// Bulk insert fields (only set when ReturnType == ReturnBulkExec)
	BulkPrefix       string   // e.g. `INSERT INTO "t" ("a", "b") VALUES `
	BulkParamsPerRow int      // number of params per row
	BulkParamNames   []string // param names per row (template order)
	BulkSuffix       string   // e.g. ` RETURNING "public_id"` or ""
	BulkDialect      string   // "postgres", "mysql", "sqlite"
}

type paramInfo struct {
	Name   string
	GoType string
}

type resultInfo struct {
	Name        string // Field name (PascalCase)
	GoType      string
	Column      string           // Original column name
	JSONAggCols []jsonAggColInfo // non-nil when this is a json_agg field
}

// jsonAggColInfo describes a single column inside a json_agg aggregate.
type jsonAggColInfo struct {
	Name   string // original column name (e.g., "name")
	GoType string // Go type (e.g., "string", "*string")
}

// =============================================================================
// Compiler Helpers
// =============================================================================

func getCompiler(dialect string) (*compile.Compiler, error) {
	switch dialect {
	case dburl.DialectPostgres:
		return compile.NewCompiler(compile.Postgres), nil
	case dburl.DialectMySQL:
		return compile.NewCompiler(compile.MySQL), nil
	case dburl.DialectSQLite:
		return compile.NewCompiler(compile.SQLite), nil
	default:
		return nil, fmt.Errorf("unsupported dialect: %s", dialect)
	}
}

func getDialect(dialect string) (compile.Dialect, error) {
	switch dialect {
	case dburl.DialectPostgres:
		return compile.Postgres, nil
	case dburl.DialectMySQL:
		return compile.MySQL, nil
	case dburl.DialectSQLite:
		return compile.SQLite, nil
	default:
		return nil, fmt.Errorf("unsupported dialect: %s", dialect)
	}
}

func compileUserQueries(queries []query.SerializedQuery, compiler *compile.Compiler) ([]userQueryInfo, error) {
	result := make([]userQueryInfo, 0, len(queries))

	dialectName := compiler.DialectName()

	for _, sq := range queries {
		// Deserialize the AST
		ast := query.DeserializeAST(sq.AST)
		if ast == nil {
			return nil, fmt.Errorf("failed to deserialize AST for query %s", sq.Name)
		}

		// Reject unsupported INSERT ... SELECT combinations
		if ast.InsertSource != nil {
			if sq.ReturnType == query.ReturnBulkExec {
				return nil, fmt.Errorf(
					"query %s: INSERT ... SELECT cannot use ReturnBulkExec "+
						"(row count is determined by the subquery, not a params slice)",
					sq.Name)
			}
			if dialectName == "mysql" && len(sq.AST.Returning) > 0 {
				return nil, fmt.Errorf(
					"query %s: INSERT ... SELECT ... RETURNING is not supported on MySQL "+
						"(MySQL does not support RETURNING)",
					sq.Name)
			}
		}

		// Compile to SQL
		sql, paramOrder, err := compiler.Compile(ast)
		if err != nil {
			return nil, fmt.Errorf("failed to compile query %s: %w", sq.Name, err)
		}

		// Extract parameters (deduplicated, in definition order)
		var params []paramInfo
		if sq.ReturnType == query.ReturnBulkExec {
			// For bulk queries, extract params from first row only (template)
			params = extractBulkParams(sq.AST)
		} else {
			params = extractParams(sq.AST)
		}

		// Extract result columns for SELECT queries
		var results []resultInfo
		if sq.ReturnType == query.ReturnOne || sq.ReturnType == query.ReturnMany || sq.ReturnType == query.ReturnPaginated {
			results = extractResults(sq.AST, sq.Name)
		}

		qi := userQueryInfo{
			Name:         sq.Name,
			ReturnType:   sq.ReturnType,
			QueryKind:    sq.AST.Kind,
			TableName:    sq.AST.FromTable.Name,
			SQL:          sql,
			HasReturning: len(sq.AST.Returning) > 0,
			ParamOrder:   paramOrder,
			Params:       params,
			Results:      results,
		}

		// For bulk exec queries, compute the prefix/suffix/template parts
		if sq.ReturnType == query.ReturnBulkExec {
			if err := compileBulkInsertParts(&qi, ast, compiler, dialectName); err != nil {
				return nil, fmt.Errorf("failed to compile bulk insert parts for query %s: %w", sq.Name, err)
			}
		}

		// For paginated queries, recompile the base SQL with ORDER BY + LIMIT,
		// then compile a second SQL variant with cursor WHERE injected.
		if sq.ReturnType == query.ReturnPaginated && len(sq.CursorColumns) > 0 {
			qi.CursorColumns = sq.CursorColumns

			// Recompile base SQL with ORDER BY + LIMIT added
			baseAST := query.DeserializeAST(query.SerializeAST(ast))
			addPaginationToAST(baseAST, sq.CursorColumns)
			baseSQL, baseParamOrder, err := compiler.Compile(baseAST)
			if err != nil {
				return nil, fmt.Errorf("failed to compile paginated base SQL for query %s: %w", sq.Name, err)
			}
			qi.SQL = baseSQL
			qi.ParamOrder = baseParamOrder

			// Compile cursor variant (base WHERE + cursor WHERE + ORDER BY + LIMIT)
			cursorAST := buildCursorAST(ast, sq.CursorColumns)
			cursorSQL, cursorParamOrder, err := compiler.Compile(cursorAST)
			if err != nil {
				return nil, fmt.Errorf("failed to compile cursor SQL for query %s: %w", sq.Name, err)
			}
			qi.CursorSQL = cursorSQL
			qi.CursorParamOrder = cursorParamOrder
		}

		result = append(result, qi)
	}

	// Sort by name for deterministic output
	sort.Slice(result, func(i, j int) bool {
		return result[i].Name < result[j].Name
	})

	return result, nil
}

// addPaginationToAST adds ORDER BY (cursor cols DESC) and LIMIT to an AST.
// This modifies the AST in place and returns it for convenience.
func addPaginationToAST(ast *query.AST, cursorCols []query.SerializedColumn) *query.AST {
	// Add ORDER BY cursor columns with direction from serialized metadata.
	// Ascending: false (zero value) means descending, preserving backward compat.
	for _, col := range cursorCols {
		ast.OrderBy = append(ast.OrderBy, query.OrderByExpr{
			Expr: query.ColumnExpr{Column: query.SimpleColumn{
				Table_:  col.Table,
				Name_:   col.Name,
				GoType_: col.GoType,
			}},
			Desc: !col.Ascending,
		})
	}
	// Add LIMIT param
	ast.Limit = query.ParamExpr{Name: "__limit", GoType: "int"}
	return ast
}

// buildCursorAST creates a copy of the base AST with cursor WHERE clause injected.
// For cursor columns [created_at, id], generates:
//
//	(created_at < ? OR (created_at = ? AND id < ?))
func buildCursorAST(baseAST *query.AST, cursorCols []query.SerializedColumn) *query.AST {
	// Deep copy: re-serialize + deserialize the original (before pagination was added)
	serialized := query.SerializeAST(baseAST)
	ast := query.DeserializeAST(serialized)

	// Add pagination (ORDER BY + LIMIT)
	addPaginationToAST(ast, cursorCols)

	// Build cursor WHERE clause
	cursorWhere := buildCursorWhereExpr(cursorCols)

	// AND the cursor WHERE into the existing WHERE
	if ast.Where != nil {
		ast.Where = query.BinaryExpr{
			Left:  ast.Where,
			Op:    query.OpAnd,
			Right: cursorWhere,
		}
	} else {
		ast.Where = cursorWhere
	}

	return ast
}

// buildCursorWhereExpr builds the keyset pagination expression.
// For descending columns [a, b]: (a < ? OR (a = ? AND b < ?))
// For ascending columns [a, b]: (a > ? OR (a = ? AND b > ?))
// For columns [a]: (a < ?) or (a > ?) depending on direction.
func buildCursorWhereExpr(cols []query.SerializedColumn) query.Expr {
	if len(cols) == 0 {
		return nil
	}

	// Descending uses OpLt (<) to page backward through time.
	// Ascending uses OpGt (>) to page forward through time.
	cursorOp := func(col query.SerializedColumn) query.BinaryOp {
		if col.Ascending {
			return query.OpGt
		}
		return query.OpLt
	}

	if len(cols) == 1 {
		return query.BinaryExpr{
			Left: query.ColumnExpr{Column: query.SimpleColumn{
				Table_:  cols[0].Table,
				Name_:   cols[0].Name,
				GoType_: cols[0].GoType,
			}},
			Op:    cursorOp(cols[0]),
			Right: query.ParamExpr{Name: "__cursor_" + cols[0].Name, GoType: cols[0].GoType},
		}
	}

	// Multi-column: (a < ?_a) OR (a = ?_a AND b < ?_b)  [descending]
	//           or: (a > ?_a) OR (a = ?_a AND b > ?_b)  [ascending]
	first := cols[0]
	firstCol := query.ColumnExpr{Column: query.SimpleColumn{
		Table_: first.Table, Name_: first.Name, GoType_: first.GoType,
	}}
	firstParam := query.ParamExpr{Name: "__cursor_" + first.Name, GoType: first.GoType}

	// Left branch: a < ? (or a > ? for ascending)
	leftBranch := query.BinaryExpr{Left: firstCol, Op: cursorOp(first), Right: firstParam}

	// Right branch: a = ? AND (recurse on remaining cols)
	eqExpr := query.BinaryExpr{Left: firstCol, Op: query.OpEq, Right: firstParam}
	innerWhere := buildCursorWhereExpr(cols[1:])

	rightBranch := query.BinaryExpr{
		Left:  eqExpr,
		Op:    query.OpAnd,
		Right: innerWhere,
	}

	return query.BinaryExpr{
		Left:  leftBranch,
		Op:    query.OpOr,
		Right: rightBranch,
	}
}

// compileBulkInsertParts computes the prefix, per-row param count/names, and suffix
// for a bulk insert query. It splits the compiled single-row SQL at " VALUES "
// and extracts the per-row template.
func compileBulkInsertParts(qi *userQueryInfo, ast *query.AST, compiler *compile.Compiler, dialectName string) error {
	// The SQL was compiled with the template row(s). We need to extract the prefix and suffix.
	// Strategy: compile a single-row version, then split on " VALUES "
	singleRowAST := *ast
	if len(ast.InsertRows) > 0 {
		singleRowAST.InsertRows = ast.InsertRows[:1] // just the first row
	}
	singleSQL, singleParamOrder, err := compiler.Compile(&singleRowAST)
	if err != nil {
		return fmt.Errorf("compiling single-row template: %w", err)
	}

	// Split on " VALUES "
	valuesIdx := strings.Index(singleSQL, " VALUES ")
	if valuesIdx == -1 {
		return fmt.Errorf("could not find VALUES clause in compiled SQL: %s", singleSQL)
	}

	qi.BulkPrefix = singleSQL[:valuesIdx+len(" VALUES ")]
	qi.BulkParamsPerRow = len(singleParamOrder)
	qi.BulkParamNames = singleParamOrder
	qi.BulkDialect = dialectName

	// The suffix is everything after the closing paren of the VALUES tuple.
	// For single-row: "INSERT INTO t (a) VALUES ($1) RETURNING id"
	// The values part is everything from " VALUES " to the end, minus the suffix.
	afterValues := singleSQL[valuesIdx+len(" VALUES "):]
	// Find the closing paren of the tuple
	parenDepth := 0
	suffixStart := -1
	for i, ch := range afterValues {
		if ch == '(' {
			parenDepth++
		} else if ch == ')' {
			parenDepth--
			if parenDepth == 0 {
				suffixStart = i + 1
				break
			}
		}
	}
	if suffixStart >= 0 && suffixStart < len(afterValues) {
		qi.BulkSuffix = afterValues[suffixStart:]
	}

	return nil
}

func extractParams(ast *query.SerializedAST) []paramInfo {
	if ast == nil {
		return nil
	}

	// Use Params from the AST if available
	if len(ast.Params) > 0 {
		params := make([]paramInfo, len(ast.Params))
		for i, p := range ast.Params {
			params[i] = paramInfo{
				Name:   p.Name,
				GoType: p.GoType,
			}
		}
		return params
	}

	// Otherwise, walk the AST to find parameters
	seen := make(map[string]bool)
	var params []paramInfo

	walkSerializedAST(ast, func(expr *query.SerializedExpr) {
		if expr.Type == "param" && expr.Param != nil {
			if !seen[expr.Param.Name] {
				seen[expr.Param.Name] = true
				params = append(params, paramInfo{
					Name:   expr.Param.Name,
					GoType: expr.Param.GoType,
				})
			}
		}
	})

	return params
}

// extractBulkParams extracts unique parameters from the first row of InsertRows only.
// For bulk queries, all rows have the same parameter shape by definition.
func extractBulkParams(ast *query.SerializedAST) []paramInfo {
	if ast == nil || len(ast.InsertRows) == 0 {
		return nil
	}

	seen := make(map[string]bool)
	var params []paramInfo

	firstRow := ast.InsertRows[0]
	for i := range firstRow {
		walkSerializedExpr(&firstRow[i], func(expr *query.SerializedExpr) {
			if expr.Type == "param" && expr.Param != nil {
				if !seen[expr.Param.Name] {
					seen[expr.Param.Name] = true
					params = append(params, paramInfo{
						Name:   expr.Param.Name,
						GoType: expr.Param.GoType,
					})
				}
			}
		})
	}

	return params
}

// leftJoinedTables returns the set of table names (or aliases) that appear
// in LEFT JOIN clauses. Columns selected from these tables can be NULL even
// when the column itself is declared NOT NULL, so their Go types must be
// made nullable (pointer) in the result struct.
func leftJoinedTables(ast *query.SerializedAST) map[string]bool {
	tables := make(map[string]bool)
	if ast == nil {
		return tables
	}
	for _, j := range ast.Joins {
		if j.Type == "LEFT" || j.Type == "FULL" {
			name := j.Table.Name
			if j.Table.Alias != "" {
				name = j.Table.Alias
			}
			tables[name] = true
		}
	}
	return tables
}

// makeNullable prepends "*" to a Go type if it is not already nullable.
// Types that are already pointers, slices, or the catch-all "any" are
// returned unchanged.
func makeNullable(goType string) string {
	if goType == "" || goType == "any" {
		return goType
	}
	if goType[0] == '*' || goType[0] == '[' {
		return goType
	}
	return "*" + goType
}

func extractResults(ast *query.SerializedAST, queryName string) []resultInfo {
	if ast == nil {
		return nil
	}

	// Determine which tables are LEFT/FULL JOINed so we can make their
	// selected columns nullable.
	leftTables := leftJoinedTables(ast)

	// For SELECT queries, use SelectCols
	if len(ast.SelectCols) > 0 {
		results := make([]resultInfo, 0, len(ast.SelectCols))

		for _, col := range ast.SelectCols {
			var name, colName, goType string
			var jsonAggCols []jsonAggColInfo

			// Determine the field name
			if col.Alias != "" {
				name = dbstrings.ToPascalCase(col.Alias)
				colName = col.Alias
			} else if col.Expr.Type == "column" && col.Expr.Column != nil {
				name = dbstrings.ToPascalCase(col.Expr.Column.Name)
				colName = col.Expr.Column.Name
				goType = col.Expr.Column.GoType
			} else {
				// For expressions without alias, generate a name
				name = fmt.Sprintf("Col%d", len(results)+1)
				colName = name
			}

			// Handle json_agg: generate typed nested struct slice
			if col.Expr.Type == "json_agg" && col.Expr.JSONAgg != nil {
				itemTypeName := queryName + dbstrings.ToPascalCase(col.Expr.JSONAgg.FieldName) + "Item"
				goType = "[]" + itemTypeName

				// Disambiguate duplicate column names by prefixing with table name.
				// e.g., roles.name + organizations.name → "name" and "organization_name"
				nameCount := make(map[string]int)
				for _, c := range col.Expr.JSONAgg.Columns {
					nameCount[c.Name]++
				}

				jsonAggCols = make([]jsonAggColInfo, len(col.Expr.JSONAgg.Columns))
				for i, c := range col.Expr.JSONAgg.Columns {
					colGoType := c.GoType
					if colGoType == "" {
						colGoType = "any"
					}
					colName := c.Name
					if nameCount[c.Name] > 1 && c.Table != "" {
						// Disambiguate: use singular(table)_column (e.g., "organization_name")
						colName = dbstrings.ToSingular(c.Table) + "_" + c.Name
					}
					jsonAggCols[i] = jsonAggColInfo{
						Name:   colName,
						GoType: colGoType,
					}
				}
			}

			// Determine the Go type (skip for json_agg, already set above)
			if goType == "" {
				goType = inferGoType(&col.Expr)
			}
			if goType == "" {
				goType = "any"
			}

			// If this column comes from a LEFT JOINed table, its value
			// can be NULL at runtime even though the column definition
			// says NOT NULL. Promote the Go type to a pointer.
			if col.Expr.Type == "column" && col.Expr.Column != nil {
				colTable := col.Expr.Column.Table
				if leftTables[colTable] {
					goType = makeNullable(goType)
				}
			}

			results = append(results, resultInfo{
				Name:        name,
				GoType:      goType,
				Column:      colName,
				JSONAggCols: jsonAggCols,
			})
		}

		return results
	}

	// For INSERT/UPDATE with RETURNING, use Returning columns
	if len(ast.Returning) > 0 {
		results := make([]resultInfo, 0, len(ast.Returning))

		for _, col := range ast.Returning {
			goType := col.GoType
			if goType == "" {
				goType = "any"
			}

			results = append(results, resultInfo{
				Name:   dbstrings.ToPascalCase(col.Name),
				GoType: goType,
				Column: col.Name,
			})
		}

		return results
	}

	return nil
}

func inferGoType(expr *query.SerializedExpr) string {
	if expr == nil {
		return "any"
	}

	switch expr.Type {
	case "column":
		if expr.Column != nil {
			return expr.Column.GoType
		}
	case "literal":
		switch expr.Literal.(type) {
		case string:
			return "string"
		case float64:
			return "float64"
		case bool:
			return "bool"
		case nil:
			return "any"
		}
	case "aggregate":
		if expr.Aggregate != nil {
			switch expr.Aggregate.Func {
			case "COUNT":
				return "int64"
			case "SUM", "AVG":
				return "float64"
			case "MIN", "MAX":
				if expr.Aggregate.Arg != nil {
					return inferGoType(expr.Aggregate.Arg)
				}
			}
		}
	case "func":
		// Common functions
		if expr.Func != nil {
			switch expr.Func.Name {
			case "NOW":
				return "time.Time"
			case "LOWER", "UPPER", "TRIM", "CONCAT":
				return "string"
			case "COALESCE":
				if len(expr.Func.Args) > 0 {
					return inferGoType(&expr.Func.Args[0])
				}
			}
		}
	case "exists":
		return "bool"
	}

	return "any"
}

// walkSerializedAST walks all expressions in a serialized AST.
func walkSerializedAST(ast *query.SerializedAST, fn func(*query.SerializedExpr)) {
	if ast == nil {
		return
	}

	// Walk select columns
	for i := range ast.SelectCols {
		walkSerializedExpr(&ast.SelectCols[i].Expr, fn)
	}

	// Walk joins
	for i := range ast.Joins {
		walkSerializedExpr(&ast.Joins[i].Condition, fn)
	}

	// Walk where
	if ast.Where != nil {
		walkSerializedExpr(ast.Where, fn)
	}

	// Walk having
	if ast.Having != nil {
		walkSerializedExpr(ast.Having, fn)
	}

	// Walk order by
	for i := range ast.OrderBy {
		walkSerializedExpr(&ast.OrderBy[i].Expr, fn)
	}

	// Walk limit/offset
	if ast.Limit != nil {
		walkSerializedExpr(ast.Limit, fn)
	}
	if ast.Offset != nil {
		walkSerializedExpr(ast.Offset, fn)
	}

	// Walk INSERT values (all rows)
	for ri := range ast.InsertRows {
		for ci := range ast.InsertRows[ri] {
			walkSerializedExpr(&ast.InsertRows[ri][ci], fn)
		}
	}

	// Walk INSERT source query (INSERT ... SELECT)
	if ast.InsertSource != nil {
		walkSerializedAST(ast.InsertSource, fn)
	}

	// Walk set clauses
	for i := range ast.SetClauses {
		walkSerializedExpr(&ast.SetClauses[i].Value, fn)
	}

	// Walk CTEs
	for i := range ast.CTEs {
		walkSerializedAST(ast.CTEs[i].Query, fn)
	}

	// Walk set operations
	if ast.SetOp != nil {
		walkSerializedAST(ast.SetOp.Left, fn)
		walkSerializedAST(ast.SetOp.Right, fn)
	}
}

func walkSerializedExpr(expr *query.SerializedExpr, fn func(*query.SerializedExpr)) {
	if expr == nil {
		return
	}

	fn(expr)

	switch expr.Type {
	case "binary":
		if expr.Binary != nil {
			walkSerializedExpr(&expr.Binary.Left, fn)
			walkSerializedExpr(&expr.Binary.Right, fn)
		}
	case "unary":
		if expr.Unary != nil {
			walkSerializedExpr(&expr.Unary.Expr, fn)
		}
	case "func":
		if expr.Func != nil {
			for i := range expr.Func.Args {
				walkSerializedExpr(&expr.Func.Args[i], fn)
			}
		}
	case "list":
		for i := range expr.List {
			walkSerializedExpr(&expr.List[i], fn)
		}
	case "aggregate":
		if expr.Aggregate != nil && expr.Aggregate.Arg != nil {
			walkSerializedExpr(expr.Aggregate.Arg, fn)
		}
	case "subquery":
		walkSerializedAST(expr.Subquery, fn)
	case "exists":
		if expr.Exists != nil {
			walkSerializedAST(expr.Exists.Subquery, fn)
		}
	}
}

// =============================================================================
// Import Collection
// =============================================================================

func collectRunnerImports(cfg UnifiedRunnerConfig, queries []userQueryInfo) map[string]bool {
	imports := make(map[string]bool)

	// Always needed
	imports["context"] = true
	imports["database/sql"] = true
	imports["fmt"] = true // BeginTx uses fmt.Errorf

	// Types package import
	imports[cfg.ModulePath+"/shipq/queries"] = true

	// Bulk exec queries need strings and fmt for runtime SQL building
	for _, qi := range queries {
		if qi.ReturnType == query.ReturnBulkExec {
			imports["strings"] = true
			imports["fmt"] = true
			imports["database/sql/driver"] = true
			break
		}
	}

	// SQLite needs extra imports for scan helpers (parseSQLiteTime, etc.)
	// Non-SQLite dialects reference time.Time and json.RawMessage only via the
	// shared queries package types, so the runner itself doesn't import them.
	// Note: json.RawMessage columns in SQLite are scanned via []byte(raw.String),
	// which does NOT require encoding/json. The json_agg block below handles the
	// cases that actually call json.Unmarshal.
	if cfg.Dialect == dburl.DialectSQLite {
		imports["fmt"] = true
		imports["time"] = true
	}

	// All dialects need encoding/json when any query has json_agg fields
	// (for json.Unmarshal of the aggregated JSON string into typed slices).
	for _, qi := range queries {
		for _, r := range qi.Results {
			if len(r.JSONAggCols) > 0 {
				imports["encoding/json"] = true
			}
		}
	}

	// MySQL/SQLite bool-fix helper uses strings.ReplaceAll.
	if jsonAggNeedsBoolFix(cfg.Dialect, queries) {
		imports["strings"] = true
	}

	// Paginated queries need fmt for fmt.Sprint when building cursors,
	// and time for time.RFC3339Nano when formatting time.Time cursor fields.
	for _, qi := range queries {
		if qi.ReturnType == query.ReturnPaginated {
			imports["fmt"] = true
			for _, col := range qi.CursorColumns {
				if col.GoType == "time.Time" {
					imports["time"] = true
				}
			}
		}
	}

	return imports
}

func collectTypesImports(queries []userQueryInfo, cfg UnifiedRunnerConfig) map[string]bool {
	imports := make(map[string]bool)

	// Check user queries
	for _, qi := range queries {
		// Runner interface needs database/sql for Exec-type queries
		if qi.ReturnType == query.ReturnExec || qi.ReturnType == query.ReturnBulkExec {
			imports["database/sql"] = true
		}
		for _, p := range qi.Params {
			if needsTimeImport(p.GoType) {
				imports["time"] = true
			}
			if needsJSONImport(p.GoType) {
				imports["encoding/json"] = true
			}
		}
		for _, r := range qi.Results {
			if needsTimeImport(r.GoType) {
				imports["time"] = true
			}
			if needsJSONImport(r.GoType) {
				imports["encoding/json"] = true
			}
		}
	}

	return imports
}

func needsTimeImport(goType string) bool {
	return strings.Contains(goType, "time.Time")
}

func needsJSONImport(goType string) bool {
	return strings.Contains(goType, "json.RawMessage")
}

// =============================================================================
// Code Generation Helpers
// =============================================================================

func writeImports(buf *bytes.Buffer, imports map[string]bool) {
	if len(imports) == 0 {
		return
	}

	// Sort imports
	importList := make([]string, 0, len(imports))
	for imp := range imports {
		importList = append(importList, imp)
	}
	sort.Strings(importList)

	// Separate standard library and third-party imports
	var stdImports, thirdPartyImports []string
	for _, imp := range importList {
		if isStdLib(imp) {
			stdImports = append(stdImports, imp)
		} else {
			thirdPartyImports = append(thirdPartyImports, imp)
		}
	}

	buf.WriteString("import (\n")
	for _, imp := range stdImports {
		buf.WriteString(fmt.Sprintf("\t%q\n", imp))
	}
	if len(stdImports) > 0 && len(thirdPartyImports) > 0 {
		buf.WriteString("\n")
	}
	for _, imp := range thirdPartyImports {
		buf.WriteString(fmt.Sprintf("\t%q\n", imp))
	}
	buf.WriteString(")\n\n")
}

func isStdLib(pkg string) bool {
	// Simple heuristic: standard library packages don't have dots in the first component
	if strings.Contains(pkg, "/") {
		firstComponent := strings.Split(pkg, "/")[0]
		return !strings.Contains(firstComponent, ".")
	}
	return !strings.Contains(pkg, ".")
}

func writeQuerierInterface(buf *bytes.Buffer) {
	buf.WriteString(`// Querier is the interface for database operations.
// Both *sql.DB and *sql.Tx implement this interface.
type Querier interface {
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row
}

`)
}

func writeQueryRunnerStruct(buf *bytes.Buffer, queries []userQueryInfo, cfg UnifiedRunnerConfig) {
	buf.WriteString(`// QueryRunner executes queries against the database.
// Create with NewQueryRunner(db) and use WithTx(tx) for transactions.
type QueryRunner struct {
	db Querier

`)

	// User query SQL fields
	if len(queries) > 0 {
		buf.WriteString("\t// User-defined query SQL\n")
		for _, qi := range queries {
			if qi.ReturnType == query.ReturnBulkExec {
				prefix := dbstrings.ToLowerCamel(qi.Name) + "BulkPrefix"
				suffix := dbstrings.ToLowerCamel(qi.Name) + "BulkSuffix"
				ppr := dbstrings.ToLowerCamel(qi.Name) + "BulkParamsPerRow"
				buf.WriteString(fmt.Sprintf("\t%s string\n", prefix))
				buf.WriteString(fmt.Sprintf("\t%s string\n", suffix))
				buf.WriteString(fmt.Sprintf("\t%s int\n", ppr))
			} else {
				fieldName := dbstrings.ToLowerCamel(qi.Name) + "SQL"
				buf.WriteString(fmt.Sprintf("\t%s string\n", fieldName))
				if qi.ReturnType == query.ReturnPaginated {
					cursorFieldName := dbstrings.ToLowerCamel(qi.Name) + "CursorSQL"
					buf.WriteString(fmt.Sprintf("\t%s string\n", cursorFieldName))
				}
			}
		}
	}

	buf.WriteString("}\n\n")
}

func writeNewQueryRunner(buf *bytes.Buffer, queries []userQueryInfo, cfg UnifiedRunnerConfig) {
	buf.WriteString(`// NewQueryRunner creates a QueryRunner for this dialect.
// All SQL strings are selected once at construction time.
func NewQueryRunner(db Querier) *QueryRunner {
	return &QueryRunner{
		db: db,

`)

	// User query SQL values
	if len(queries) > 0 {
		buf.WriteString("\t\t// User-defined queries\n")
		for _, qi := range queries {
			if qi.ReturnType == query.ReturnBulkExec {
				prefix := dbstrings.ToLowerCamel(qi.Name) + "BulkPrefix"
				suffix := dbstrings.ToLowerCamel(qi.Name) + "BulkSuffix"
				ppr := dbstrings.ToLowerCamel(qi.Name) + "BulkParamsPerRow"
				buf.WriteString(fmt.Sprintf("\t\t%s: %q,\n", prefix, qi.BulkPrefix))
				buf.WriteString(fmt.Sprintf("\t\t%s: %q,\n", suffix, qi.BulkSuffix))
				buf.WriteString(fmt.Sprintf("\t\t%s: %d,\n", ppr, qi.BulkParamsPerRow))
			} else {
				fieldName := dbstrings.ToLowerCamel(qi.Name) + "SQL"
				buf.WriteString(fmt.Sprintf("\t\t%s: %q,\n", fieldName, qi.SQL))
				if qi.ReturnType == query.ReturnPaginated {
					cursorFieldName := dbstrings.ToLowerCamel(qi.Name) + "CursorSQL"
					buf.WriteString(fmt.Sprintf("\t\t%s: %q,\n", cursorFieldName, qi.CursorSQL))
				}
			}
		}
	}

	buf.WriteString("\t}\n}\n\n")
}

func writeWithTx(buf *bytes.Buffer, queries []userQueryInfo, cfg UnifiedRunnerConfig) {
	buf.WriteString(`// WithTx returns a new QueryRunner using the given transaction.
// SQL strings are copied (no recomputation).
func (r *QueryRunner) WithTx(tx *sql.Tx) *QueryRunner {
	return &QueryRunner{
		db: tx,

`)

	// Copy all query SQL (user-defined and CRUD queries are unified)
	if len(queries) > 0 {
		for _, qi := range queries {
			if qi.ReturnType == query.ReturnBulkExec {
				prefix := dbstrings.ToLowerCamel(qi.Name) + "BulkPrefix"
				suffix := dbstrings.ToLowerCamel(qi.Name) + "BulkSuffix"
				ppr := dbstrings.ToLowerCamel(qi.Name) + "BulkParamsPerRow"
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", prefix, prefix))
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", suffix, suffix))
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", ppr, ppr))
			} else {
				fieldName := dbstrings.ToLowerCamel(qi.Name) + "SQL"
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", fieldName, fieldName))
				if qi.ReturnType == query.ReturnPaginated {
					cursorFieldName := dbstrings.ToLowerCamel(qi.Name) + "CursorSQL"
					buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", cursorFieldName, cursorFieldName))
				}
			}
		}
	}

	buf.WriteString("\t}\n}\n\n")

	// BeginTx method on QueryRunner — satisfies the Runner interface
	writeBeginTx(buf)
}

// writeBeginTx emits the BeginTx method on QueryRunner.
func writeBeginTx(buf *bytes.Buffer) {
	buf.WriteString(`// BeginTx starts a new database transaction and returns a TxRunner
// that wraps a transactional copy of this QueryRunner.
// If the underlying db is already a *sql.Tx, BeginTx returns an error.
func (r *QueryRunner) BeginTx(ctx context.Context) (*queries.TxRunner, error) {
	sqlDB, ok := r.db.(*sql.DB)
	if !ok {
		return nil, fmt.Errorf("BeginTx: underlying db is already a transaction")
	}
	tx, err := sqlDB.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	return &queries.TxRunner{
		Runner: r.WithTx(tx),
		Tx:     tx,
	}, nil
}

`)
}

func writeWithDB(buf *bytes.Buffer, queries []userQueryInfo, cfg UnifiedRunnerConfig) {
	buf.WriteString(`// WithDB returns a new QueryRunner using a different Querier.
func (r *QueryRunner) WithDB(db Querier) *QueryRunner {
	return &QueryRunner{
		db: db,

`)

	// Copy all query SQL (user-defined and CRUD queries are unified)
	if len(queries) > 0 {
		for _, qi := range queries {
			if qi.ReturnType == query.ReturnBulkExec {
				prefix := dbstrings.ToLowerCamel(qi.Name) + "BulkPrefix"
				suffix := dbstrings.ToLowerCamel(qi.Name) + "BulkSuffix"
				ppr := dbstrings.ToLowerCamel(qi.Name) + "BulkParamsPerRow"
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", prefix, prefix))
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", suffix, suffix))
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", ppr, ppr))
			} else {
				fieldName := dbstrings.ToLowerCamel(qi.Name) + "SQL"
				buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", fieldName, fieldName))
				if qi.ReturnType == query.ReturnPaginated {
					cursorFieldName := dbstrings.ToLowerCamel(qi.Name) + "CursorSQL"
					buf.WriteString(fmt.Sprintf("\t\t%s: r.%s,\n", cursorFieldName, cursorFieldName))
				}
			}
		}
	}

	buf.WriteString("\t}\n}\n\n")
}

func writeUserQueryMethod(buf *bytes.Buffer, qi userQueryInfo, cfg UnifiedRunnerConfig) error {
	typesPackage := "queries"

	switch qi.ReturnType {
	case query.ReturnBulkExec:
		writeBulkExecMethod(buf, qi, cfg)
		return nil

	case query.ReturnOne:
		// Returns (*Result, error)
		paramType := fmt.Sprintf("%s.%sParams", typesPackage, qi.Name)
		resultType := fmt.Sprintf("%s.%sResult", typesPackage, qi.Name)

		buf.WriteString(fmt.Sprintf("// %s executes the user-defined query and returns at most one result.\n", qi.Name))
		buf.WriteString(fmt.Sprintf("func (r *QueryRunner) %s(ctx context.Context, params %s) (*%s, error) {\n", qi.Name, paramType, resultType))

		// Build args slice
		writeArgsSlice(buf, qi)

		sqlField := dbstrings.ToLowerCamel(qi.Name) + "SQL"
		isMySQL := cfg.Dialect == dburl.DialectMySQL
		isSQLite := cfg.Dialect == dburl.DialectSQLite
		isMySQLInsertReturning := isMySQL && qi.QueryKind == string(query.InsertQuery) && qi.HasReturning

		if isMySQLInsertReturning {
			// MySQL doesn't support RETURNING. Use ExecContext + LastInsertId + follow-up SELECT.
			writeMySQLInsertReturningOne(buf, qi, sqlField, resultType, cfg)
		} else {
			// Postgres, SQLite, or non-INSERT: use QueryRowContext with RETURNING
			buf.WriteString(fmt.Sprintf("\trow := r.db.QueryRowContext(ctx, r.%s, args...)\n\n", sqlField))

			// Scan result
			buf.WriteString(fmt.Sprintf("\tvar result %s\n", resultType))
			// Declare temp vars for json_agg fields (all dialects)
			for _, r := range qi.Results {
				if len(r.JSONAggCols) > 0 {
					tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
					buf.WriteString(fmt.Sprintf("\tvar %s string\n", tmp))
				}
			}
			if isSQLite {
				for _, r := range qi.Results {
					if len(r.JSONAggCols) > 0 {
						continue // already handled above
					}
					if !isSQLiteSpecialResultGoType(r.GoType) {
						continue
					}
					tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
					switch r.GoType {
					case "time.Time":
						buf.WriteString(fmt.Sprintf("\tvar %s string\n", tmp))
					case "*time.Time", "json.RawMessage", "*json.RawMessage":
						buf.WriteString(fmt.Sprintf("\tvar %s sql.NullString\n", tmp))
					}
				}
			}
			buf.WriteString("\tif err := row.Scan(\n")
			for _, r := range qi.Results {
				if len(r.JSONAggCols) > 0 {
					tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
					buf.WriteString(fmt.Sprintf("\t\t&%s,\n", tmp))
					continue
				}
				if isSQLite && isSQLiteSpecialResultGoType(r.GoType) {
					tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
					buf.WriteString(fmt.Sprintf("\t\t&%s,\n", tmp))
					continue
				}
				buf.WriteString(fmt.Sprintf("\t\t&result.%s,\n", r.Name))
			}
			buf.WriteString("\t); err != nil {\n")
			buf.WriteString("\t\tif err == sql.ErrNoRows {\n")
			buf.WriteString("\t\t\treturn nil, nil\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			// Unmarshal json_agg fields (all dialects)
			needsBoolFix := cfg.Dialect == dburl.DialectMySQL || cfg.Dialect == dburl.DialectSQLite
			for _, r := range qi.Results {
				if len(r.JSONAggCols) == 0 {
					continue
				}
				tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
				// Fix MySQL/SQLite numeric bools (0/1) before unmarshal
				if needsBoolFix && jsonAggColsHaveBool(r.JSONAggCols) {
					boolFields := jsonAggBoolFieldNames(r.JSONAggCols)
					buf.WriteString(fmt.Sprintf("\t%s = fixJSONBoolFields(%s, %s)\n", tmp, tmp, boolFields))
				}
				buf.WriteString(fmt.Sprintf("\tif err := json.Unmarshal([]byte(%s), &result.%s); err != nil {\n", tmp, r.Name))
				buf.WriteString("\t\treturn nil, err\n")
				buf.WriteString("\t}\n")
			}
			if isSQLite {
				for _, r := range qi.Results {
					if len(r.JSONAggCols) > 0 {
						continue // already handled above
					}
					if !isSQLiteSpecialResultGoType(r.GoType) {
						continue
					}
					tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
					switch r.GoType {
					case "time.Time":
						buf.WriteString(fmt.Sprintf("\tparsed%s, err := parseSQLiteTime(%s)\n", r.Name, tmp))
						buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
						buf.WriteString(fmt.Sprintf("\tresult.%s = parsed%s\n", r.Name, r.Name))
					case "*time.Time":
						buf.WriteString(fmt.Sprintf("\tparsed%s, err := parseSQLiteNullTime(%s)\n", r.Name, tmp))
						buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
						buf.WriteString(fmt.Sprintf("\tresult.%s = parsed%s\n", r.Name, r.Name))
					case "json.RawMessage":
						buf.WriteString(fmt.Sprintf("\tif %s.Valid {\n\t\tresult.%s = []byte(%s.String)\n\t}\n", tmp, r.Name, tmp))
					case "*json.RawMessage":
						buf.WriteString(fmt.Sprintf("\tif %s.Valid {\n\t\tv := json.RawMessage(%s.String)\n\t\tresult.%s = &v\n\t}\n", tmp, tmp, r.Name))
					}
				}
			}
			buf.WriteString("\treturn &result, nil\n")
		}
		buf.WriteString("}\n\n")

	case query.ReturnMany:
		// Returns ([]Result, error)
		paramType := fmt.Sprintf("%s.%sParams", typesPackage, qi.Name)
		resultType := fmt.Sprintf("%s.%sResult", typesPackage, qi.Name)

		buf.WriteString(fmt.Sprintf("// %s executes the user-defined query and returns all results.\n", qi.Name))
		buf.WriteString(fmt.Sprintf("func (r *QueryRunner) %s(ctx context.Context, params %s) ([]%s, error) {\n", qi.Name, paramType, resultType))

		// Build args slice
		writeArgsSlice(buf, qi)

		// Execute query
		sqlField := dbstrings.ToLowerCamel(qi.Name) + "SQL"
		buf.WriteString(fmt.Sprintf("\trows, err := r.db.QueryContext(ctx, r.%s, args...)\n", sqlField))
		buf.WriteString("\tif err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tdefer rows.Close()\n\n")

		isSQLite := cfg.Dialect == dburl.DialectSQLite
		// Scan results
		buf.WriteString(fmt.Sprintf("\tvar results []%s\n", resultType))
		buf.WriteString("\tfor rows.Next() {\n")
		buf.WriteString(fmt.Sprintf("\t\tvar item %s\n", resultType))
		// Declare temp vars for json_agg fields (all dialects)
		for _, r := range qi.Results {
			if len(r.JSONAggCols) > 0 {
				tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
				buf.WriteString(fmt.Sprintf("\t\tvar %s string\n", tmp))
			}
		}
		if isSQLite {
			for _, r := range qi.Results {
				if len(r.JSONAggCols) > 0 {
					continue // already handled above
				}
				if !isSQLiteSpecialResultGoType(r.GoType) {
					continue
				}
				tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
				switch r.GoType {
				case "time.Time":
					buf.WriteString(fmt.Sprintf("\t\tvar %s string\n", tmp))
				case "*time.Time", "json.RawMessage", "*json.RawMessage":
					buf.WriteString(fmt.Sprintf("\t\tvar %s sql.NullString\n", tmp))
				}
			}
		}
		buf.WriteString("\t\tif err := rows.Scan(\n")
		for _, r := range qi.Results {
			if len(r.JSONAggCols) > 0 {
				tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
				buf.WriteString(fmt.Sprintf("\t\t\t&%s,\n", tmp))
				continue
			}
			if isSQLite && isSQLiteSpecialResultGoType(r.GoType) {
				tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
				buf.WriteString(fmt.Sprintf("\t\t\t&%s,\n", tmp))
				continue
			}
			buf.WriteString(fmt.Sprintf("\t\t\t&item.%s,\n", r.Name))
		}
		buf.WriteString("\t\t); err != nil {\n")
		buf.WriteString("\t\t\treturn nil, err\n")
		buf.WriteString("\t\t}\n")
		// Unmarshal json_agg fields (all dialects)
		needsBoolFix := cfg.Dialect == dburl.DialectMySQL || cfg.Dialect == dburl.DialectSQLite
		for _, r := range qi.Results {
			if len(r.JSONAggCols) == 0 {
				continue
			}
			tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
			// Fix MySQL/SQLite numeric bools (0/1) before unmarshal
			if needsBoolFix && jsonAggColsHaveBool(r.JSONAggCols) {
				boolFields := jsonAggBoolFieldNames(r.JSONAggCols)
				buf.WriteString(fmt.Sprintf("\t\t%s = fixJSONBoolFields(%s, %s)\n", tmp, tmp, boolFields))
			}
			buf.WriteString(fmt.Sprintf("\t\tif err := json.Unmarshal([]byte(%s), &item.%s); err != nil {\n", tmp, r.Name))
			buf.WriteString("\t\t\treturn nil, err\n")
			buf.WriteString("\t\t}\n")
		}
		if isSQLite {
			for _, r := range qi.Results {
				if len(r.JSONAggCols) > 0 {
					continue // already handled above
				}
				if !isSQLiteSpecialResultGoType(r.GoType) {
					continue
				}
				tmp := dbstrings.ToLowerCamel(r.Name) + "Raw"
				switch r.GoType {
				case "time.Time":
					buf.WriteString(fmt.Sprintf("\t\tparsed%s, err := parseSQLiteTime(%s)\n", r.Name, tmp))
					buf.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
					buf.WriteString(fmt.Sprintf("\t\titem.%s = parsed%s\n", r.Name, r.Name))
				case "*time.Time":
					buf.WriteString(fmt.Sprintf("\t\tparsed%s, err := parseSQLiteNullTime(%s)\n", r.Name, tmp))
					buf.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
					buf.WriteString(fmt.Sprintf("\t\titem.%s = parsed%s\n", r.Name, r.Name))
				case "json.RawMessage":
					buf.WriteString(fmt.Sprintf("\t\tif %s.Valid {\n\t\t\titem.%s = []byte(%s.String)\n\t\t}\n", tmp, r.Name, tmp))
				case "*json.RawMessage":
					buf.WriteString(fmt.Sprintf("\t\tif %s.Valid {\n\t\t\tv := json.RawMessage(%s.String)\n\t\t\titem.%s = &v\n\t\t}\n", tmp, tmp, r.Name))
				}
			}
		}
		buf.WriteString("\t\tresults = append(results, item)\n")
		buf.WriteString("\t}\n\n")

		buf.WriteString("\tif err := rows.Err(); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn results, nil\n")
		buf.WriteString("}\n\n")

	case query.ReturnExec:
		// Returns (sql.Result, error)
		paramType := fmt.Sprintf("%s.%sParams", typesPackage, qi.Name)

		buf.WriteString(fmt.Sprintf("// %s executes the user-defined query without returning rows.\n", qi.Name))
		buf.WriteString(fmt.Sprintf("func (r *QueryRunner) %s(ctx context.Context, params %s) (sql.Result, error) {\n", qi.Name, paramType))

		// Build args slice
		writeArgsSlice(buf, qi)

		// Execute query
		sqlField := dbstrings.ToLowerCamel(qi.Name) + "SQL"
		buf.WriteString(fmt.Sprintf("\treturn r.db.ExecContext(ctx, r.%s, args...)\n", sqlField))
		buf.WriteString("}\n\n")

	case query.ReturnPaginated:
		writePaginatedMethod(buf, qi, cfg)
	}

	return nil
}

// writeMySQLInsertReturningOne generates the MySQL-specific pattern for INSERT
// queries that want to return columns (which other dialects handle via RETURNING).
// MySQL doesn't support RETURNING, so we:
// 1. ExecContext the INSERT
// 2. Get the auto-increment ID via LastInsertId()
// 3. SELECT the desired columns using that ID
func writeMySQLInsertReturningOne(buf *bytes.Buffer, qi userQueryInfo, sqlField, resultType string, cfg UnifiedRunnerConfig) {
	mysqlDialect, _ := getDialect(dburl.DialectMySQL)
	quotedTable := quoteIdentifier(qi.TableName, mysqlDialect)

	// Step 1: ExecContext
	buf.WriteString(fmt.Sprintf("\texecResult, err := r.db.ExecContext(ctx, r.%s, args...)\n", sqlField))
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n\n")

	// Step 2: LastInsertId
	buf.WriteString("\tinsertedID, err := execResult.LastInsertId()\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n\n")

	// Step 3: SELECT the returning columns
	var quotedCols []string
	for _, r := range qi.Results {
		quotedCols = append(quotedCols, quoteIdentifier(r.Column, mysqlDialect))
	}
	selectSQL := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ?",
		strings.Join(quotedCols, ", "),
		quotedTable,
		quoteIdentifier("id", mysqlDialect))

	buf.WriteString(fmt.Sprintf("\trow := r.db.QueryRowContext(ctx, %q, insertedID)\n\n", selectSQL))

	// Scan result
	buf.WriteString(fmt.Sprintf("\tvar result %s\n", resultType))
	buf.WriteString("\tif err := row.Scan(\n")
	for _, r := range qi.Results {
		buf.WriteString(fmt.Sprintf("\t\t&result.%s,\n", r.Name))
	}
	buf.WriteString("\t); err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn &result, nil\n")
}

func writeArgsSlice(buf *bytes.Buffer, qi userQueryInfo) {
	if len(qi.ParamOrder) == 0 {
		buf.WriteString("\targs := []any{}\n")
		return
	}

	buf.WriteString("\targs := []any{\n")
	for _, paramName := range qi.ParamOrder {
		buf.WriteString(fmt.Sprintf("\t\tparams.%s,\n", dbstrings.ToPascalCase(paramName)))
	}
	buf.WriteString("\t}\n")
}

// writePaginatedMethod generates the cursor-paginated method for a query.
func writePaginatedMethod(buf *bytes.Buffer, qi userQueryInfo, cfg UnifiedRunnerConfig) {
	typesPackage := "queries"
	name := qi.Name
	paramType := fmt.Sprintf("%s.%sParams", typesPackage, name)
	itemType := fmt.Sprintf("%s.%sItem", typesPackage, name)
	resultType := fmt.Sprintf("%s.%sResult", typesPackage, name)
	cursorType := fmt.Sprintf("%s.%sCursor", typesPackage, name)
	sqlField := dbstrings.ToLowerCamel(name) + "SQL"
	cursorSQLField := dbstrings.ToLowerCamel(name) + "CursorSQL"

	isSQLite := cfg.Dialect == dburl.DialectSQLite

	buf.WriteString(fmt.Sprintf("// %s fetches paginated results with cursor support.\n", name))
	buf.WriteString(fmt.Sprintf("func (r *QueryRunner) %s(ctx context.Context, params %s) (*%s, error) {\n", name, paramType, resultType))

	// Handle pagination params
	buf.WriteString("\tlimit := params.Limit\n")
	buf.WriteString("\tif limit <= 0 {\n")
	buf.WriteString("\t\tlimit = 20\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tfetchLimit := limit + 1\n\n")

	// Build args and pick SQL based on cursor presence
	buf.WriteString("\tvar sqlStr string\n")
	buf.WriteString("\tvar args []any\n\n")

	buf.WriteString("\tif params.Cursor != nil {\n")
	buf.WriteString(fmt.Sprintf("\t\tsqlStr = r.%s\n", cursorSQLField))

	// Build cursor args: user params first, then cursor params, then __limit
	buf.WriteString("\t\targs = []any{\n")
	for _, paramName := range qi.CursorParamOrder {
		if strings.HasPrefix(paramName, "__cursor_") {
			colName := strings.TrimPrefix(paramName, "__cursor_")
			fieldName := dbstrings.ToPascalCase(colName)
			buf.WriteString(fmt.Sprintf("\t\t\tparams.Cursor.%s,\n", fieldName))
		} else if paramName == "__limit" {
			buf.WriteString("\t\t\tfetchLimit,\n")
		} else {
			buf.WriteString(fmt.Sprintf("\t\t\tparams.%s,\n", dbstrings.ToPascalCase(paramName)))
		}
	}
	buf.WriteString("\t\t}\n")

	buf.WriteString("\t} else {\n")
	buf.WriteString(fmt.Sprintf("\t\tsqlStr = r.%s\n", sqlField))

	// Build base args: user params, then __limit
	buf.WriteString("\t\targs = []any{\n")
	for _, paramName := range qi.ParamOrder {
		if paramName == "__limit" {
			buf.WriteString("\t\t\tfetchLimit,\n")
		} else {
			buf.WriteString(fmt.Sprintf("\t\t\tparams.%s,\n", dbstrings.ToPascalCase(paramName)))
		}
	}
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")

	// Execute query
	buf.WriteString("\trows, err := r.db.QueryContext(ctx, sqlStr, args...)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer rows.Close()\n\n")

	// Scan rows
	buf.WriteString(fmt.Sprintf("\tvar items []%s\n", itemType))
	buf.WriteString("\tfor rows.Next() {\n")
	buf.WriteString(fmt.Sprintf("\t\tvar item %s\n", itemType))

	// SQLite intermediate scan variables
	if isSQLite {
		for _, r := range qi.Results {
			scanType := sqliteScanType(r.GoType)
			if scanType != "" {
				tmp := dbstrings.ToLowerCamel(r.Column) + "Raw"
				buf.WriteString(fmt.Sprintf("\t\tvar %s %s\n", tmp, scanType))
			}
		}
	}

	buf.WriteString("\t\tif err := rows.Scan(\n")
	for _, r := range qi.Results {
		if isSQLite {
			scanType := sqliteScanType(r.GoType)
			if scanType != "" {
				tmp := dbstrings.ToLowerCamel(r.Column) + "Raw"
				buf.WriteString(fmt.Sprintf("\t\t\t&%s,\n", tmp))
				continue
			}
		}
		buf.WriteString(fmt.Sprintf("\t\t\t&item.%s,\n", r.Name))
	}
	buf.WriteString("\t\t); err != nil {\n")
	buf.WriteString("\t\t\treturn nil, err\n")
	buf.WriteString("\t\t}\n")

	// SQLite type conversions
	if isSQLite {
		for _, r := range qi.Results {
			scanType := sqliteScanType(r.GoType)
			if scanType == "" {
				continue
			}
			tmp := dbstrings.ToLowerCamel(r.Column) + "Raw"
			switch r.GoType {
			case "time.Time":
				buf.WriteString(fmt.Sprintf("\t\tparsed%s, err := parseSQLiteTime(%s)\n", r.Name, tmp))
				buf.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
				buf.WriteString(fmt.Sprintf("\t\titem.%s = parsed%s\n", r.Name, r.Name))
			case "*time.Time":
				buf.WriteString(fmt.Sprintf("\t\tparsed%s, err := parseSQLiteNullTime(%s)\n", r.Name, tmp))
				buf.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
				buf.WriteString(fmt.Sprintf("\t\titem.%s = parsed%s\n", r.Name, r.Name))
			case "json.RawMessage":
				buf.WriteString(fmt.Sprintf("\t\tif %s.Valid {\n\t\t\titem.%s = []byte(%s.String)\n\t\t}\n", tmp, r.Name, tmp))
			case "*json.RawMessage":
				buf.WriteString(fmt.Sprintf("\t\tif %s.Valid {\n\t\t\tv := json.RawMessage(%s.String)\n\t\t\titem.%s = &v\n\t\t}\n", tmp, tmp, r.Name))
			}
		}
	}

	buf.WriteString("\t\titems = append(items, item)\n")
	buf.WriteString("\t}\n\n")

	buf.WriteString("\tif err := rows.Err(); err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n\n")

	// Build result with pagination
	buf.WriteString(fmt.Sprintf("\tresult := &%s{}\n", resultType))
	buf.WriteString("\tif len(items) > limit {\n")
	buf.WriteString("\t\t// We fetched one extra to detect next page\n")
	buf.WriteString("\t\tresult.Items = items[:limit]\n")
	buf.WriteString("\t\tlastItem := items[limit-1]\n")
	buf.WriteString(fmt.Sprintf("\t\tresult.NextCursor = &%s{\n", cursorType))
	for _, col := range qi.CursorColumns {
		fieldName := dbstrings.ToPascalCase(col.Name)
		if col.GoType == "time.Time" {
			if isSQLite {
				// SQLite stores timestamps via strftime('%Y-%m-%dT%H:%M:%fZ','now')
				// which always produces exactly 3 fractional digits (e.g. ".000").
				// time.RFC3339Nano trims trailing zeros, producing a different
				// string that breaks lexicographic cursor comparisons in SQLite.
				buf.WriteString(fmt.Sprintf("\t\t\t%s: lastItem.%s.UTC().Format(\"2006-01-02T15:04:05.000Z\"),\n", fieldName, fieldName))
			} else {
				buf.WriteString(fmt.Sprintf("\t\t\t%s: lastItem.%s.UTC().Format(time.RFC3339Nano),\n", fieldName, fieldName))
			}
		} else {
			buf.WriteString(fmt.Sprintf("\t\t\t%s: fmt.Sprint(lastItem.%s),\n", fieldName, fieldName))
		}
	}
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t} else {\n")
	buf.WriteString("\t\tresult.Items = items\n")
	buf.WriteString("\t}\n\n")

	buf.WriteString("\treturn result, nil\n")
	buf.WriteString("}\n\n")
}

// sqliteScanType returns the intermediate scan type for SQLite, or "" if direct scan is fine.
func sqliteScanType(goType string) string {
	switch goType {
	case "time.Time":
		return "string"
	case "*time.Time":
		return "sql.NullString"
	case "json.RawMessage", "*json.RawMessage":
		return "sql.NullString"
	default:
		return ""
	}
}

// writeBulkExecMethod generates the bulk insert method that builds SQL at runtime.
func writeBulkExecMethod(buf *bytes.Buffer, qi userQueryInfo, cfg UnifiedRunnerConfig) {
	typesPackage := "queries"
	paramType := fmt.Sprintf("%s.%sParams", typesPackage, qi.Name)
	prefixField := dbstrings.ToLowerCamel(qi.Name) + "BulkPrefix"
	suffixField := dbstrings.ToLowerCamel(qi.Name) + "BulkSuffix"
	pprField := dbstrings.ToLowerCamel(qi.Name) + "BulkParamsPerRow"

	buf.WriteString(fmt.Sprintf("// %s executes a multi-row INSERT.\n", qi.Name))
	buf.WriteString(fmt.Sprintf("// Pass an empty slice for a no-op (returns driver.RowsAffected(0)).\n"))
	buf.WriteString(fmt.Sprintf("func (r *QueryRunner) %s(ctx context.Context, params []%s) (sql.Result, error) {\n", qi.Name, paramType))
	buf.WriteString("\tif len(params) == 0 {\n")
	buf.WriteString("\t\treturn driver.RowsAffected(0), nil\n")
	buf.WriteString("\t}\n\n")

	// Build SQL and args at runtime
	buf.WriteString("\tvar sb strings.Builder\n")
	buf.WriteString(fmt.Sprintf("\tsb.WriteString(r.%s)\n", prefixField))
	buf.WriteString(fmt.Sprintf("\targs := make([]any, 0, len(params)*r.%s)\n", pprField))
	buf.WriteString("\tfor i, p := range params {\n")
	buf.WriteString("\t\tif i > 0 {\n")
	buf.WriteString("\t\t\tsb.WriteString(\", \")\n")
	buf.WriteString("\t\t}\n")

	isPostgres := cfg.Dialect == "postgres"

	if isPostgres {
		// Postgres needs $N placeholders renumbered per row
		buf.WriteString(fmt.Sprintf("\t\tbase := i * r.%s\n", pprField))
		buf.WriteString("\t\tsb.WriteString(\"(\")\n")
		buf.WriteString(fmt.Sprintf("\t\tfor j := 0; j < r.%s; j++ {\n", pprField))
		buf.WriteString("\t\t\tif j > 0 {\n")
		buf.WriteString("\t\t\t\tsb.WriteString(\", \")\n")
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tfmt.Fprintf(&sb, \"$%d\", base+j+1)\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tsb.WriteString(\")\")\n")
	} else {
		// MySQL/SQLite: all placeholders are ?, so the row template is static
		buf.WriteString("\t\tsb.WriteString(\"(\")\n")
		buf.WriteString(fmt.Sprintf("\t\tfor j := 0; j < r.%s; j++ {\n", pprField))
		buf.WriteString("\t\t\tif j > 0 {\n")
		buf.WriteString("\t\t\t\tsb.WriteString(\", \")\n")
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tsb.WriteString(\"?\")\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\tsb.WriteString(\")\")\n")
	}

	// Append args from the params struct in the template order
	for _, paramName := range qi.BulkParamNames {
		buf.WriteString(fmt.Sprintf("\t\targs = append(args, p.%s)\n", dbstrings.ToPascalCase(paramName)))
	}

	buf.WriteString("\t}\n")
	buf.WriteString(fmt.Sprintf("\tsb.WriteString(r.%s)\n", suffixField))
	buf.WriteString("\treturn r.db.ExecContext(ctx, sb.String(), args...)\n")
	buf.WriteString("}\n\n")
}

func writeUserQueryTypes(buf *bytes.Buffer, qi userQueryInfo) {
	if qi.ReturnType == query.ReturnPaginated {
		writePaginatedTypes(buf, qi)
		return
	}

	// Write params struct
	buf.WriteString(fmt.Sprintf("// %sParams are the parameters for the %s query.\n", qi.Name, qi.Name))
	if qi.ReturnType == query.ReturnBulkExec {
		buf.WriteString(fmt.Sprintf("// Each element represents one row in the bulk insert.\n"))
	}
	buf.WriteString(fmt.Sprintf("type %sParams struct {\n", qi.Name))
	for _, p := range qi.Params {
		buf.WriteString(fmt.Sprintf("\t%s %s\n", dbstrings.ToPascalCase(p.Name), p.GoType))
	}
	buf.WriteString("}\n\n")

	// Write result struct for SELECT queries
	if qi.ReturnType == query.ReturnOne || qi.ReturnType == query.ReturnMany {
		buf.WriteString(fmt.Sprintf("// %sResult is the result type for the %s query.\n", qi.Name, qi.Name))
		buf.WriteString(fmt.Sprintf("type %sResult struct {\n", qi.Name))
		for _, r := range qi.Results {
			buf.WriteString(fmt.Sprintf("\t%s %s\n", r.Name, r.GoType))
		}
		buf.WriteString("}\n\n")

		// Write nested struct types for json_agg fields
		for _, r := range qi.Results {
			if len(r.JSONAggCols) == 0 {
				continue
			}
			itemTypeName := r.GoType[2:] // strip leading "[]"
			buf.WriteString(fmt.Sprintf("// %s is a nested type for the %s JSON aggregate.\n", itemTypeName, r.Column))
			buf.WriteString(fmt.Sprintf("type %s struct {\n", itemTypeName))
			for _, c := range r.JSONAggCols {
				jsonTag := c.Name
				if strings.HasPrefix(c.GoType, "*") {
					jsonTag += ",omitempty"
				}
				buf.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", dbstrings.ToPascalCase(c.Name), c.GoType, jsonTag))
			}
			buf.WriteString("}\n\n")
		}
	}
}

// writePaginatedTypes generates cursor, params, item, and result types for a paginated query.
func writePaginatedTypes(buf *bytes.Buffer, qi userQueryInfo) {
	name := qi.Name // e.g. "ListPosts"

	// Cursor type
	cursorType := name + "Cursor"
	buf.WriteString(fmt.Sprintf("// %s holds pagination state for %s.\n", cursorType, name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", cursorType))
	for _, col := range qi.CursorColumns {
		fieldName := dbstrings.ToPascalCase(col.Name)
		// Cursor fields are always stored as strings for JSON serialization
		buf.WriteString(fmt.Sprintf("\t%s string `json:%q`\n", fieldName, col.Name))
	}
	buf.WriteString("}\n\n")

	// Encode cursor function
	encodeFunc := "Encode" + name + "Cursor"
	buf.WriteString(fmt.Sprintf("// %s encodes a cursor to a base64 string.\n", encodeFunc))
	buf.WriteString(fmt.Sprintf("func %s(cursor *%s) string {\n", encodeFunc, cursorType))
	buf.WriteString("\tif cursor == nil {\n")
	buf.WriteString("\t\treturn \"\"\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdata, _ := json.Marshal(cursor)\n")
	buf.WriteString("\treturn base64.StdEncoding.EncodeToString(data)\n")
	buf.WriteString("}\n\n")

	// Decode cursor function
	decodeFunc := "Decode" + name + "Cursor"
	buf.WriteString(fmt.Sprintf("// %s decodes a base64 string to a cursor.\n", decodeFunc))
	buf.WriteString(fmt.Sprintf("func %s(encoded string) *%s {\n", decodeFunc, cursorType))
	buf.WriteString("\tif encoded == \"\" {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdata, err := base64.StdEncoding.DecodeString(encoded)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString(fmt.Sprintf("\tvar cursor %s\n", cursorType))
	buf.WriteString("\tif err := json.Unmarshal(data, &cursor); err != nil {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn &cursor\n")
	buf.WriteString("}\n\n")

	// Params type: user-defined params + Limit + Cursor
	paramsType := name + "Params"
	buf.WriteString(fmt.Sprintf("// %s are the parameters for %s.\n", paramsType, name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", paramsType))
	for _, p := range qi.Params {
		buf.WriteString(fmt.Sprintf("\t%s %s\n", dbstrings.ToPascalCase(p.Name), p.GoType))
	}
	buf.WriteString("\tLimit  int\n")
	buf.WriteString(fmt.Sprintf("\tCursor *%s\n", cursorType))
	buf.WriteString("}\n\n")

	// Item type (from SELECT columns)
	itemType := name + "Item"
	buf.WriteString(fmt.Sprintf("// %s is a single item in the %s result.\n", itemType, name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", itemType))
	for _, r := range qi.Results {
		buf.WriteString(fmt.Sprintf("\t%s %s\n", r.Name, r.GoType))
	}
	buf.WriteString("}\n\n")

	// Result type (wrapper with Items + NextCursor)
	resultType := name + "Result"
	buf.WriteString(fmt.Sprintf("// %s is the result of %s.\n", resultType, name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", resultType))
	buf.WriteString(fmt.Sprintf("\tItems      []%s\n", itemType))
	buf.WriteString(fmt.Sprintf("\tNextCursor *%s\n", cursorType))
	buf.WriteString("}\n\n")
}

func quoteIdentifier(name string, dialect compile.Dialect) string {
	return dialect.QuoteIdentifier(name)
}

// =============================================================================
// Helper Functions
// =============================================================================

func singular(name string) string {
	return dbstrings.ToSingular(name)
}

func isSQLiteSpecialResultGoType(goType string) bool {
	return goType == "time.Time" || goType == "*time.Time" || goType == "json.RawMessage" || goType == "*json.RawMessage"
}

// jsonAggColsHaveBool returns true if any column in the json_agg has a bool Go type.
func jsonAggColsHaveBool(cols []jsonAggColInfo) bool {
	for _, c := range cols {
		if c.GoType == "bool" || c.GoType == "*bool" {
			return true
		}
	}
	return false
}

// jsonAggNeedsBoolFix returns true if the dialect is MySQL or SQLite and any
// query has json_agg columns with bool fields.
func jsonAggNeedsBoolFix(dialect string, queries []userQueryInfo) bool {
	if dialect != dburl.DialectMySQL && dialect != dburl.DialectSQLite {
		return false
	}
	for _, qi := range queries {
		for _, r := range qi.Results {
			if jsonAggColsHaveBool(r.JSONAggCols) {
				return true
			}
		}
	}
	return false
}

// jsonAggBoolFieldNames returns a Go literal string for the slice of bool field
// names in a json_agg, e.g. `[]string{"should_text", "is_active"}`.
func jsonAggBoolFieldNames(cols []jsonAggColInfo) string {
	var names []string
	for _, c := range cols {
		if c.GoType == "bool" || c.GoType == "*bool" {
			names = append(names, fmt.Sprintf("%q", c.Name))
		}
	}
	return "[]string{" + strings.Join(names, ", ") + "}"
}

// writeJSONBoolFixHelper emits a fixJSONBoolFields function into the generated
// runner. MySQL and SQLite JSON_OBJECT outputs TINYINT(1) boolean columns as
// numeric 0/1 instead of JSON true/false, which breaks json.Unmarshal into
// Go bool fields.
func writeJSONBoolFixHelper(buf *bytes.Buffer) {
	buf.WriteString(`// fixJSONBoolFields patches raw JSON from JSON_OBJECT so that boolean fields
// encoded as 0/1 (MySQL/SQLite TINYINT) become true/false before unmarshal.
func fixJSONBoolFields(raw string, boolFields []string) string {
	for _, f := range boolFields {
		raw = strings.ReplaceAll(raw, "\""+f+"\": 0", "\""+f+"\": false")
		raw = strings.ReplaceAll(raw, "\""+f+"\": 1", "\""+f+"\": true")
		raw = strings.ReplaceAll(raw, "\""+f+"\":0", "\""+f+"\":false")
		raw = strings.ReplaceAll(raw, "\""+f+"\":1", "\""+f+"\":true")
	}
	return raw
}

`)
}

func writeSQLiteScanHelpers(buf *bytes.Buffer) {
	buf.WriteString(`// parseSQLiteTime parses SQLite datetime/timestamp text values.
func parseSQLiteTime(s string) (time.Time, error) {
	formats := []string{
		"2006-01-02 15:04:05",
		"2006-01-02 15:04:05.000",
		"2006-01-02T15:04:05",
		"2006-01-02T15:04:05Z",
		time.RFC3339,
		time.RFC3339Nano,
	}
	for _, format := range formats {
		if t, err := time.Parse(format, s); err == nil {
			return t, nil
		}
	}
	return time.Time{}, fmt.Errorf("invalid sqlite datetime value %q", s)
}

func parseSQLiteNullTime(ns sql.NullString) (*time.Time, error) {
	if !ns.Valid || ns.String == "" {
		return nil, nil
	}
	t, err := parseSQLiteTime(ns.String)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

`)
}
